### PR TITLE
deps: update miniupnp to 2.3.0

### PR DESCRIPTION
**Pull request by ckerr**
When building our own miniupnpc instead of using the system library, build version 2.3.0.

Happily the API changes that have built up since the last time we updated (API version 14 -> API version 17, detailed at https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/apiversions.txt) all seem to be additive and compatible with our existing code, so no code changes were made in libtransmission.

This PR does make one other change though: it replaces the `transmission/miniupnpc` submodule with `transmission/miniupnp` simply to make future upkeep easier. as the latter is forked from the upstream miniupnp repo. (miniupnp**c** is a subdirectory in the miniupnp monorepo).

### CODE REVIEW

**Review by Coeur — CHANGES_REQUESTED** [review]
While I support this submodule change,

Let's delay merging this until building from Xcode is resolved.
As it is, there would be an issue of the type:
>'miniupnpcstrings.h' file not found

I've resolved this build issue in #3021.

I recommend merging #3021 first, otherwise we are stacking regressions on building from Xcode.

**Review by Coeur — APPROVED** [review]

**Comment by ckerr** [comment]
I don't understand these Windows build failures and may need more time to look into this one.

**Comment by fxcoudert** [comment]
It seems miniupnd is creating `third-party/miniupnpc/lib/libminiupnpc.lib` but the transmission is trying to link `third-party\miniupnpc\lib\miniupnpc.lib` (no `lib` before the library name).

**Comment by Pentaphon** [comment]
> I don't understand these Windows build failures and may need more time to look into this one.

I might be wrong, but @depler has a [daemon fork for Windows](https://github.com/depler/transmission-vs) so he might be of help here.

**Comment by depler** [comment]
@Pentaphon, I don't use compiled libs in my project (except OpenSSL), so `miniupnp` is included as raw source code in my fork

**Comment by Coeur** [comment]
Hello @ckerr, when can we get this update?
In current version, which is using miniupnp 2.0 from 2017, there are runtime errors of type:
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/User/Developer/transmission/third-party/miniupnpc/minissdpc.c:863:6 in 
/Users/User/Developer/transmission/third-party/miniupnpc/minissdpc.c:865:6: runtime error: index 83 out of bounds for type 'char[3]'

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2576:77 in 
/Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2576:77: runtime error: store to misaligned address 0x000109e73704 for type 'UTPSocket *', which requires 8 byte alignment
0x000109e73704: note: pointer points here
  a7 41 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ff ff ff ff 00 00 00 00  00 00 00 00 00 00 00 00
```

So updating to a newer version of miniupnp is desired.

**Comment by ckerr** [comment]
> Hello @ckerr, when can we get this update?

I've been kind of busy the past few days. If you want to work on this patch and get it green I'd be happy to merge it :green_heart:

**Comment by GaryElshaw** [comment]
Possibly a hint? There have been some unresolved issues with cmake and miniupnpc since back in January. https://github.com/miniupnp/miniupnp/pull/591

**Comment by GaryElshaw** [comment]
New news

@ckerr @Coeur 

https://github.com/transmission/transmission/issues/3181#issuecomment-1328157770

**Comment by GaryElshaw** [comment]
Charles, can you please try again, this was updated again in Nvember with the cmake issues sorted. @ckerr

**Comment by ckerr** [comment]
https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/VERSION is on 2.3.3 now. This probably should just be started again from scratch.

**Pull request closed without merging**
