### PR TITLE
refactor: use evhttp public accessors in rpc server

### PR DESCRIPTION
**Pull request by tearfur**
Use evhttp public accessors instead of private implementation details in rpc server code.

### CODE REVIEW

**Comment by reardonia** [comment]
> Use evhttp public accessors instead of private implementation details in rpc server code.

Since you are in this code, a related question: with libevent, it seems that evhttp events are treated differently than "pure" events created with `event_new()` or `event_assign()`.  In particular, there is no `struct event *` embedded in `struct evhttp`, even libevent-internal objects like `struct evhttp_connection`. 

But "pure" events and evhttp events use the same event_base.  What I'm trying to figure out is how libevent handles priority for evhttp vs pure events that share a single event_base.

I ask this because I was exploring the use of event_priority_set() to make RPC events higher priority than the rest of events handled in the main event loop. As far as I can tell, there is no way to do this. It seems as if evhttp events do not follow or respect priority settings. Very confusing to me since, as I said, they share same event_base.

**Comment by tearfur** [comment]
I have no idea, maybe you can ask over in the libevent project.

**Comment by reardonia** [comment]
> I have no idea, maybe you can ask over in the libevent project.

It turns out that evhttp are ultimately resolved as default bufferevent objects and take on the default priority.  I have a draft PR that leverages this to improve RPC performance that I post shortly.

**Review by ckerr — APPROVED** [review]

**Comment by tearfur** [comment]
Needs re-review because I made some changes to resolve the merge conflict.

**Review by ckerr — APPROVED** [review]

**Pull request merged**
