### PR TITLE
fix: 'enumerated and non-enumerated type' warnings

### PR DESCRIPTION
**Pull request by ckerr**
Simple change to silence warnings, changes the offending enums to be constexprs. There is still more cleanup work to update other enums; this just addresses the ones causing compiler warnings

### CODE REVIEW

**Comment by stefanos82** [comment]
Instead of doing

```c++
namespace
{

constexpr int MAX_PEX_PEER_COUNT = 50;

} // unnamed namespace
```
you could go away with `enum : int { MAX_PEX_PEER_COUNT = 50 };`

**Comment by mikedld** [comment]
@stefanos82, it's not an enumeration though, so why do that and confuse people?

> Being able to do something is not by itself a good reason for doing it.
-- "The C++ Programming Language", Bjarne Stroustrup

**Comment by stefanos82** [comment]
> @stefanos82, it's not an enumeration though, so why do that and confuse people?

Oh you mean you have isolated only `MAX_PEX_PEER_COUNT` from the entire unnamed enumerator and declared it as of type `int`?

**Comment by ckerr** [comment]
The reason I originally used enums was to have a compile-time constant value. Two idiomatic ways of doing that in older ANSI C was #defines and enums, and I chose enums so that debuggers would be able to pick up the symbolic name. IMO `constexpr` is the idiomatic way of doing this in C++ -- we should probably migrate more of our constants form enums to constexpr.

...that said, TIL `enum : int { ... }` which is pretty cool :smiley:

**Comment by stefanos82** [comment]
> The reason I originally used enums was to have a compile-time constant value. Two idiomatic ways of doing that in older ANSI C were #defines and enums, and I chose enums so that debuggers would be able to pick up the symbolic name. IMO `constexpr` is the idiomatic way of doing this in C++ -- as @mikedld points out, it's less confusing since these fields that were changed aren't enumerating anything in the first place.
> 
> ...that said, TIL `enum : int { ... }` which is pretty cool smiley

Yeah, C++ introduced very useful mechanisms for enumerators that fixed its past behavior that were borrowed from C; now we have 3 different enumeration mechanisms, well technically it's 2 + 1 complement of the newest one: 

 - unscoped enumerations
 - scoped enumerations
 - using-enum declaration

You can read more here https://en.cppreference.com/w/cpp/language/enum

**Pull request merged**
