### PR TITLE
feat: Align active filter macOS

### PR DESCRIPTION
**Pull request by Coeur**
Fix: #101

Simplified code change of the solution found by @Harm133 in #3922.

### CODE REVIEW

**Comment by Harm133** [comment]
Yes, I prefer this change way over all the changes my PR had :smile: !
Just tested and all the issues encountered with my changes are not present here

**Comment by Coeur** [comment]
Let's note there is a wording change consequence to this change:
Instead of saying "**Propagating to 0 of X peers**", it says "**Stalled**".

**Comment by GaryElshaw** [comment]
LGTM!

**Comment by Coeur** [comment]
Sorting by activity isn't optimal when using groups. I'll try to adapt to avoid the "stalled" wording.

**Comment by GaryElshaw** [comment]
There's a conflict sorting activity when groups are used? That's an issue.

**Comment by Coeur** [comment]
I mean that without this change, sorting by activity was showing:
- Group 1 actives
- Group 1 inactives
- Group 2 actives
- Group 2 inactives
- ...

I've addressed the "stalled" message. Can you try again, Gary?

**Comment by GaryElshaw** [comment]
Binary from TC: 4.0.0-beta.1.dev (6b76318ae0). Seeing some connection issues with usually reliable trackers receiving peers, but saying otherwise. Visually, things look normal.

SCR-20221012-w1a

**Comment by ckerr** [comment]
@GaryElshaw could you give this another test with the new commits?

**Comment by GaryElshaw** [comment]
> @GaryElshaw could you give this another test with the new commits?

Sure thing, but i'm going to need some help trying to understand what it is i am expected or not expected to see with this change, because i don't regularly share more than 20 or so torrents (ie, i don't regularly need the filter bar).

I usually have the sort by activity function on, for this i've chosen sort by queue order.

As you see, if i click on active in the filter bar, should it only be active torrents that are seeding appear at the top? In this case, an active, but unseeding torrent appears at the top. Is this the behaviour this change is meant to make?

SCR-20221020-qr3


Similarly with selecting seeding as te filter bar option, there is no change with what is active and inactively seeding. 

SCR-20221020-qrj

**Comment by Coeur** [comment]
Hum, I would need to see if I can reproduce.

**Comment by Coeur** [comment]
OK, I reproduced the issue, so this is not good to merge as it is.

**Comment by Coeur** [comment]
I've adjusted the refresh conditions: maybe it's resolved now, @GaryElshaw

**Comment by GaryElshaw** [comment]
This is much, much better, Antoine. The only weirdness i've noticed is entering a 'g' in the search area and one of the results didn't contain a 'g' in any of its information.

**Comment by Coeur** [comment]
This PR has no impact on filtering by text. If something doesn't work as expected when filtering, it would be an unrelated issue. Just make sure you're not accidentally filtering by tracker name instead of torrent name.
All in all, I can't do better than this: it's a pretty straightforward change: the `isActive` tab is only listing `transmitting` torrents and is refreshed when `transmitting` status changes.

**Comment by GaryElshaw** [comment]
Yep, was sorting by name. I think this is good to go!

**Review by nevack — APPROVED** [review]
LGTM, I'd go with this

**Comment by ckerr** [comment]
@Coeur or @GaryElshaw could you add a release note for this PR?

**Comment by GaryElshaw** [comment]
Notes: Added the ability to sort by activity using the filter bar.

**Pull request merged**
