### PR TITLE
Replace gear icon with ellipsis in macOS client

### PR DESCRIPTION
**Pull request by GaryElshaw**
Implement the default MacOS ellipsis menu item. As previously discussed, MacOS does this by default for additional menu items. It also needs this to be differentiated from other items in the bar that are buttons. The ellipsis in MacOS iconography relates there are additional dropdown options available.
 
SCR-20220518-iyp --> SCR-20220602-lj3

### CODE REVIEW

**Comment by ckerr** [comment]
I am not really sure what's going on. He closed a handful of his PRs right after I gave him a 3-day timeout  for being hostile to another contributor. So I don't know if he's angry about that timeout or what's going on.

**Comment by sweetppro** [comment]
if the status bar icon is changed, then perhaps all the individual torrent preference icons would also need to be changed for consistency?

Screen Shot 2022-06-05 at 7 29 37 pm

**Review by sweetppro — COMMENTED** [review]
the changes look fine, but I think we need to consider the introduced inconsistency with the individual torrent preference icons
Screen Shot 2022-06-05 at 7 29 37 pm

**Comment by GaryElshaw** [comment]
> the changes look fine, but I think we need to consider the introduced inconsistency with the individual torrent preference icons Screen Shot 2022-06-05 at 7 29 37 pm

Probably *grimace*

**Comment by GaryElshaw** [comment]
Dragonfly is having issues :-(

**Review by ckerr — COMMENTED** [review]
Does macOS support svg icons here; and if so, could this be replaced with an svg instead?

Also, what is the source of this icon and what is its license?

**Comment by GaryElshaw** [comment]
There are no svg icons in the mac client. The icon is from Xcode and SFSymbols.

**Comment by ckerr** [comment]
> There are no svg icons in the mac client.

Is that because svg doesn't work, or because it hasn't been used yet? This UI code is pretty old and predates common use of svg icons.

> The icon is from Xcode and SFSymbols.

OK. What's the name of this SFSymbol?

**Comment by GaryElshaw** [comment]
On the first point - i don't know, but it certainly isn't common.

On the second, as i said with regards to the probable code, ellipsis-fill

**Comment by ckerr** [comment]
OK. According to SF Symbols Explorer it's `ellipsis.circle.fill` which is the inverse version of `ellipsis.circle`

**Comment by GaryElshaw** [comment]
Code-wise, the debate has often centred on the fact that rendering a 3k png is substantially faster than svg. I think Mitch raised something more fundamental with his comment about ditching 10.x support in Transmission.

I mostly build my own Transmission, the deprecation warnings are significant, especially for Controller.mm, but supporting older versions of the OS is important, i think. @coeur will be the best person to sort out whether the deprecations can be better reconciled.

**Comment by GaryElshaw** [comment]
> OK. According to SF Symbols Explorer it's `ellipsis.circle.fill` which is the inverse version of `ellipsis.circle`

Ahhh, indeed. Apologies, my mistake. You're right.

**Comment by ckerr** [comment]
> On the first point - i don't know, but it certainly isn't common.

The reason I asked is because svgs scale very nicely, so instead of having a 1x and 2x png we could probably make do with a single svg file. According to [this site](https://betterprogramming.pub/use-the-new-apple-sf-symbols-in-your-applications-6feb75ef294b) using ⌘E in the SF Symbols app will export the icon in SVG format.

**Comment by GaryElshaw** [comment]
> > On the first point - i don't know, but it certainly isn't common.
> 
> The reason I asked is because svgs scale very nicely, so instead of having a 1x and 2x png we could probably make do with a single svg file. According to [this site](https://betterprogramming.pub/use-the-new-apple-sf-symbols-in-your-applications-6feb75ef294b) using ⌘E in the SF Symbols app will export the icon in SVG format.

Yep, i did that with a lot of the web icons in that web pr because many of the orefs ones are svg. As i said up the thread a bit, it's mostly been avoided because of the cycles incurred rendering it. It's also a bit of a PIA to edit if you're relying on open source image manipulation. Although Apple lets you export these as svg, Apple's own image software won't open them :-(

**Comment by Coeur** [comment]
> Can someone direct me to the code that could change that gear icon? @Coeur @sweetppro @DevilDimon

ActionHover in Images.xcassets

> Code-wise, the debate has often centred on the fact that rendering a 3k png is substantially faster than svg.

It's hard to update all our png files for occasional new display resolutions. A vectorized image or a system image doesn't need update efforts.

> I mostly build my own Transmission, the deprecation warnings are significant, especially for Controller.mm, but supporting older versions of the OS is important, i think. @Coeur will be the best person to sort out whether the deprecations can be better reconciled.

There are no warnings in this pull request. Maybe the topic was about just adding:
```
[NSImage systemSymbol:@"ellipsis.circle.fill" withFallback:@"EllipsisTemplate"]
```

**Comment by GaryElshaw** [comment]
> > Can someone direct me to the code that could change that gear icon? @Coeur @sweetppro @DevilDimon
> 
> ActionHover in Images.xcassets
> 
> > Code-wise, the debate has often centred on the fact that rendering a 3k png is substantially faster than svg.
> 
> It's hard to update all our png files for occasional new display resolutions. A vectorized image or a system image doesn't need update efforts.
> 
> > I mostly build my own Transmission, the deprecation warnings are significant, especially for Controller.mm, but supporting older versions of the OS is important, i think. @Coeur will be the best person to sort out whether the deprecations can be better reconciled.
> 
> There are no warnings in this pull request. Maybe the topic was about just adding:
> 
> ```
> [NSImage systemSymbol:@"ellipsis.circle.fill" withFallback:@"EllipsisTemplate"]
> ```
> 
> > I think Mitch raised something more fundamental with his comment about ditching 10.x support in Transmission.
> 
> We do have indeed multiple fallback icons which could be removed in macOS 11.0. But at this point, Transmission 4.0 beta should be released without dropping any version of macOS. I still see tons of peers on uTorrent and that software is only working on very old 32 bit systems. We can consider dropping those icons in Transmission 5 maybe.

Thanks Antoine, yes, there was more than one topic being discussed here.

**Comment by ckerr** [comment]
As much as I would prefer to upgrade to svg files, the key question IMO is whether svg is supported on older versions of macOS. If we ship svg for modern versions bug have to fall back to png in olderr versions, then in fact we're using more files rather than fewer.

IIRC 10.10 is the oldest version we support. Does anyone know about svg support there? Iff it works, then I'd vote for migrating to svg.

**Comment by GaryElshaw** [comment]
I'll experiment locally and see what happens. No harm/nothing ventured etc.

In the meantime, we have what we have....

**Comment by Coeur** [comment]
I found this:
>https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
>
>Added support for Scalable Vector Graphic (SVG) image assets. These preserve their vector representation with deployment targets of macOS 10.15 or later, iOS 13 or later, and iPadOS 13 or later. (18389814)

So SVG are for **macOS 10.15 or later**

**Comment by Coeur** [comment]
Personally, I'm not sure if the gear or the ellipsis is best. That aesthetic change needs to be reviewed by someone more qualified than me in design questions.

**Comment by GaryElshaw** [comment]
> Personally, I'm not sure if the gear or the ellipsis is best. That aesthetic change needs to be reviewed by someone more qualified than me in design questions.

The ellipsis is the default MacOS icon for this feature in Xcode. I'm not pulling these from thin air :-)

**Comment by Coeur** [comment]
I see. I found three with circled ellipsis and one with a reversed chevron. So it makes sense.

Capture d’écran 2022-06-09 à 23 05 54
Capture d’écran 2022-06-09 à 23 04 38
Capture d’écran 2022-06-09 à 23 04 01
Capture d’écran 2022-06-09 à 23 03 27

**Comment by GaryElshaw** [comment]
> In Xcode, the colour changes with the mode. Shouldn't you provide the icon for the light background by default? Capture d’écran 2022-06-09 à 23 19 35 Capture d’écran 2022-06-09 à 23 19 18

I did do that originally, but the icon next to it is also a 'filled' icon which made it look very skeletal. Also because the background is very dark.

**Comment by Coeur** [comment]
Comparison before/after in light mode:
Capture d’écran 2022-06-09 à 23 28 57
Capture d’écran 2022-06-09 à 23 44 28

OK for me.

**Review by Coeur — APPROVED** [review]

**Comment by GaryElshaw** [comment]
> I found this:
> 
> > https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes
> > Added support for Scalable Vector Graphic (SVG) image assets. These preserve their vector representation with deployment targets of macOS 10.15 or later, iOS 13 or later, and iPadOS 13 or later. (18389814)
> 
> So SVG are for **macOS 10.15 or later**

Then there's something in the codebase that's not allowing svg's?

**Comment by GaryElshaw** [comment]
@ckerr Thumbs up from Antoine.

**Pull request merged**
