### PR TITLE
remove unused Portuguese localization

### LINKED ISSUE #3698: [macOS] Message Log, translations are missing
Preferably before the first beta, translations were available everywhere.
[Transmission-258faf3623](https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-258faf3623.dmg)

- **German**
German

- **Dansk**
Dansk

- **Italiano**
Italiano

- **Nederlands**
Nederlands

### PR DESCRIPTION
**Pull request by Coeur**
This removes the unused pt.lproj folder (we use the pt_PT.lproj folder instead).

### CODE REVIEW

**Comment by Coeur** [comment]
@mikedld @nevack would you like to review this one? I tested it already.

**Review by nevack — APPROVED** [review]
> @mikedld @nevack would you like to review this one? I tested it already.

Very clever solution, I hope it won't introduce new issues, modifying system methods in runtime can be dangerous IMO

**Comment by mikedld** [comment]
It seems to do what's advertized, and it's unlikely we'll ever want empty strings to be valid translations, but I cannot speak to whether it's the right way to go, so not going to either approve or disprove.

To throw another idea in, I could try adjusting the script I'm using to sync translations with Transifex so that those phrases aren't in the .strings file to begin with. From reading the documentation it appears that this would also lead to it returning the key.

**Comment by Coeur** [comment]
Correct @mikedld, removing the translations containing empty strings would be a better fix.

**Comment by mikedld** [comment]
See #4161.

**Comment by Coeur** [comment]
Since it's now handled by Mike's PR, I'm repurposing this PR to just removing the unused Portuguese.

**Review by mikedld — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: none

**Pull request merged**
