### PR TITLE
feat: macOS hide torrent Group icons when in Group view

### PR DESCRIPTION
**Pull request by sweetppro**
Closes: #4952

### CODE REVIEW

**Comment by ckerr** [comment]
@sweetppro https://github.com/transmission/transmission/suites/11078109661/artifacts/563647510 to make CI happy

**Comment by sweetppro** [comment]
> @sweetppro https://github.com/transmission/transmission/suites/11078109661/artifacts/563647510 to make CI happy

oops... I thought I already ran the code style check.
@ckerr thanks

**Comment by GaryElshaw** [comment]
I don't understand this change. I mean, i get it, but it strikes me as being a custom change for the user's preference than a benefit for the wider community.

**Comment by Coeur** [comment]
I would disagree with this change. I have a hundred of torrents in each group, so when I'm scrolling, I'm unable to tell which group I'm in if we remove the dots.

Any alternative solution?

**Review by Coeur — CHANGES_REQUESTED** [review]
Not UI-friendly for those with many torrents in each group.

**Comment by GaryElshaw** [comment]
> so when I'm scrolling, I'm unable to tell which group I'm in if we remove the dots.

Excellent point.

**Comment by svkirillov** [comment]
> so when I'm scrolling, I'm unable to tell which group I'm in if we remove the dots.

That's why I have another suggestion: #4950

**Comment by sweetppro** [comment]
Good point,
I just saw a PR i could quickly write. I have no skin in the game. I never use Groups 😊

**Comment by Coeur** [comment]
@sweetppro the suggestion from #4950 is better and acceptable (pinning the group name so it's always visible). I suggest we close this PR and #4952 in favor of #4950.

**Comment by sweetppro** [comment]
@couer why close? 
this is a direct precursor to that issue. I can probably add that functionality into this PR

**Comment by sweetppro** [comment]
I set the 4.1 milestone on this, so there's no rush to merge

**Comment by GaryElshaw** [comment]
Maybe a title change then?

**Comment by Coeur** [comment]
Yes, we can combine them. But the floating group row has to be implemented before or in the same PR.

**Comment by sweetppro** [comment]
looks like the _easiest_ way to accomplish this is to convert the OutlineView from Cell based to View based.
not a trivial change

**Comment by sweetppro** [comment]
Closed in preference to this more complete solution: #5147

**Pull request closed without merging**
