### PR TITLE
fix macOS statusBar icons

### PR DESCRIPTION
**Pull request by sweetppro**
make macOS status icons consistent across all versions of macOS
Screen Shot 2022-05-19 at 3 47 10 pm

https://github.com/transmission/transmission/pull/3103 https://github.com/transmission/transmission/issues/3100 https://github.com/transmission/transmission/issues/3112

### CODE REVIEW

**Comment by GaryElshaw** [comment]
We have conflicting PR's :-( #3114

**Comment by ckerr** [comment]
@sweetppro and @GaryElshaw can the two of you figure out which PR should be used? :slightly_smiling_face:

**Comment by GaryElshaw** [comment]
@ckerr, @sweetppro's then mine.

**Comment by sweetppro** [comment]
@ckerr They both do different things. mine fixes the icon sizes and makes them consistent across macOS versions.

i didn’t change any icons, as no one else said they wanted to change icons

**Comment by GaryElshaw** [comment]
> @ckerr They both do different things. mine fixes the icon sizes and makes them consistent across macOS versions.

Yep. And mine #3103 is an interim fix, and might as well be merged until this PR is ready.

**Comment by ckerr** [comment]
@Coeur ping

**Review by ckerr — CHANGES_REQUESTED** [review]
FTBFS

```
CMake Error at macosx/CMakeLists.txt:423 (add_executable):
19:10:31     Cannot find source file:
19:10:31   
19:10:31       Images/Images.xcassets/TurtleTemplate.imageset/TurtleTemplate.png
19:10:31   
19:10:31     Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
19:10:31     .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
19:10:31   
19:10:31   
19:10:31   CMake Error at macosx/CMakeLists.txt:423 (add_executable):
[19:10:31 ](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_MacOSX8664/213420?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=213420_598_598&logView=flowAware)    No SOURCES given to target: transmission-mac
```

**Comment by sweetppro** [comment]
> CMake Error at macosx/CMakeLists.txt:423 (add_executable):
> 19:10:31     Cannot find source file:
> 19:10:31   
> 19:10:31       Images/Images.xcassets/TurtleTemplate.imageset/TurtleTemplate.png

@ckerr this is now fixed

**Review by ckerr — APPROVED** [review]

**Comment by GaryElshaw** [comment]
@sweetppro Something has happened to the tortoise's head :-(
TortoiseTemplate
TortoiseTemplate@2x

**Comment by maxz** [comment]
It is highly irregular that you removed someone else from the AUTHORS file. You could have removed the Tortoise comment to make it clear that the current Tortoise is not created by Dean Ostetto, but he still deserves to be credited for his contribution.

**Pull request merged**
