### PR TITLE
Add daemon-startPaused to settings file

### LINKED ISSUE #1575: Add configuration file option corresponding to --paused
It would be nice if the daemon could start with all torrents paused on startup based on a configuration option in `settings.json` instead of just via the argument `--paused`.

### PR DESCRIPTION
**Pull request by curufinwe**
Resolves #1575 .

### CODE REVIEW

**Comment by GaryElshaw** [comment]
@curufinwe Hi Eugen, unfortunately some conflicts have crept in since you submitted your pr, are you able to resolve them?

**Comment by ckerr** [comment]
Oog, looks the rebases I ran somehow picked up some unrelated changes to `third-party`. Not sure why that happened but now it really does need manual intervention. :disappointed: 

@curufinwe please do update this PR to remove the unrelated changes

**Comment by Coeur** [comment]
Superseded by #6728 to resolve the unrelated changes.

**Comment by Coeur** [comment]
Done by #6728

**Pull request closed without merging**
