### PR TITLE
Update all instances of the donation link. Fixes #26.

### LINKED ISSUE #26: Donate link in all clients points to old website
it's https://transmissionbt.com/donate.php  but should be   https://transmissionbt.com/donate/
as is, it gets a 404.
problem found in osx client,
18:32 < CrazyLemon> its not just osx..its also gtk and qt

### PR DESCRIPTION
**Pull request by RobFog**

### CODE REVIEW

**Comment by Slegh** [comment]
Good job ;) approved

**Comment by RobFog** [comment]
I will squash the commits, okay?

**Comment by mikedld** [comment]
Oops, too late :-P

**Comment by RobFog** [comment]
;-) Thanks for accepting the pull request.

**Pull request merged**
