### PR TITLE
transmission: build against openssl 1.1.0

### PR DESCRIPTION
**Pull request by sebastianas**
Signed-off-by: Sebastian Andrzej Siewior sebastian@breakpoint.cc

### CODE REVIEW

**Comment by mikedld** [comment]
Thanks! Please follow existing coding style though, otherwise PR won't even be considered.

**Comment by sebastianas** [comment]
is this better?

**Comment by mikedld** [comment]
Better, but still not perfect. Please put a bit more effort into it, we're not in a hurry here ;)

**Comment by sebastianas** [comment]
On 2016-09-05 16:03:01 [-0700], Mike Gelfand wrote:
> Better, but still not perfect. Please put a bit more effort into it, we're not in a hurry here ;)

Do you have a coding style document? I've looked over it and I made it
fit with some source I saw around it. Or please point me to what is
wrong.

Sebastian

**Comment by mikedld** [comment]
I've made a few adjustments myself in 8c8386a7f3f482a9c917f51d28e0042e55f56b3e. There's no official coding style documentation, but current code generally follows something similar to [GTK+/GNOME coding style](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html.en), except for Mac client.

**Comment by sebastianas** [comment]
thanks

**Pull request merged**
