### PR TITLE
Client-based blocking

### PR DESCRIPTION
**Pull request by Artoria2e5**
There are a bunch of client applications around that basically do nothing but leech, and quite a bunch of users (especially in China where big legitimate companies are making these stuff) want a feature that kills them. The fuller rationale is laid out in #735.

This so far is only the skeleton for you code reviewers to figure out alternatives for some of the weird choices I may have made. Among these is cramming the new blocklist type in the old blocklist chain, since it appears to be an interface for stuff outside of libtransmission and I do not want to break the interfaces yet.

Progress to being ready-to-use:

* libtransmission:
  - [x] behavior (should work already if it compiles)
  - [ ] try to compile it (sorry no regex.h on windows)
  - [ ] interface that makes sense (if we want the front-end to auto-pull it...)
  - [ ] regex implementation on Windows (we are gpl so yeah whatever)
* UI:
  - [ ] macOS
  - [ ] Gtk
  - [ ] Qt
  - [ ] web

<details>
<summary>Peer blocklist documentation</summary>

A peer blocklist is a third-party list of [BitTorrent Peer IDs](https://www.bittorrent.org/beps/bep_0020.html) to block. These can be used to block clients that are believed to be malicious. To allow for variation, they are defined as regular expressions.

[...] Peer blocklist files consists of a set of INSERT STANDARD IN THE FINAL IMPLEMENTATION HERE regular expressions. Each line contains one regular expression that describes the Peer ID you want to block. The regular expressions are anchored by Transmission to match the entire Peer ID.

*Hey, can someone change the current blocklist description too? It does not mention CIDR support.*

[...] Transmission stores blocklists in a folder named blocklists in its configuration folder. The peer blocklists are located the peer subfolder under it.
</details>

### CODE REVIEW

**Comment by Artoria2e5** [comment]
Turning off the draft status to have the CI fire.

**Comment by Artoria2e5** [comment]
I am going to clean this up for cli merge soon, since I just spotted a bunch of XunLei and the slightly less dubious BitComet highest up in my leecher list. Before that I need to settle on a regex library to do byte-level matching.

@transmission dear maintainers, do you have a preference for regex libraries? My preference is somewhere between re2 and libgnu "dfa": 

* re2 is nice and fast, but we will need to introduce another dependency, which is a major change for a PR.
* dfa.c is only in two files, but they ain't small either. I will also need to seek out a pre-GPL3 version, since transmission is still dual-licensed for now.

If you want to suggest any other library, please make sure it can at least be modified to match bytewise. A custom encoding of latin-1 counts.

**Comment by rhn** [comment]
I just wanted to mention that I'm really looking forward to getting this merged. Is there a chance this could be updated for current master branch

**Comment by Artoria2e5** [comment]
I am unfortunately taking an extended hiatus from "computer stuff" with no projected end, so this PR is going to be closed. If anyone wants to build something useful from this rotten pile of code -- go ahead, it's allowed by the license. Sorry.

In the meantime, the parent issue has been closed by @ckerr, although under an argument I would consider erroneous. Just as transmission provides an IP-blocking function without recommending any blocklists, providing just a peer-blocking function without recommending any particular peer should not be illegal. Not that I am a lawyer or I care about this stuff any more.

**Pull request closed without merging**
