### PR TITLE
macOS UI font changes

### PR DESCRIPTION
**Pull request by GaryElshaw**
After opening the can of worms, a follow up pr to create what i was talking about. Although 11 is a reasonably good default font size, it is slightly on the smaller side and can appear disproportionately tiny on small monitors when using a regular weight (the 13" MacBook Air for example, and don't get me started on our 10 and sub-10 point font use).

The idea for these changes is twofold. 

1. Give users a clear means of differentiating between a header, a title, and body text that guides the user to what is a parameter they can change. For example, the majority of the views in this pr use the following rules as a guide:

a: A heading - a bolded +1 font size increase
b: Guidance on a variable the user can change - bold
c: User input fields or spaces - plain/regular text.

2. Increase the ability for users to scan more easily. Different weights give the eye a rest when trying to differentiate data from guidance. 

Because it has come up, please note the diff of the current files and this pr. Aside from font weight or size, there are zero other code changes in this pr.

Here's some shots of some of the revisions.

Statistics
Original
SCR-20220802-i09

This PR
SCR-20220801-nek

Options
Original
SCR-20220802-hzv

This PR
SCR-20220803-lv

General info
Original
SCR-20220802-hyr

This PR
SCR-20220730-n8h

Activity
Original
SCR-20220802-hz1

This PR
SCR-20220731-orc

Options Menu

This PR
SCR-20220731-ttt

Open torrent file
SCR-20220731-ttd

Create torrent file
SCR-20220731-tsq

What do people think? Love it? Hate it? OTT indifference?

### CODE REVIEW

**Comment by Oleg-Chashko** [comment]
Bildschirmfoto 2022-07-30 um 09 38 41

**Comment by GaryElshaw** [comment]
Yes, that is exactly what i was talking about @Oleg-Chashko

**Comment by Oleg-Chashko** [comment]
Problem: different widths in the German localization. Check all localizations to avoid making problems.

Bildschirmfoto 2022-07-30 um 09 54 18

**Review by ckerr — COMMENTED** [review]
> macOS UI font changes

> +2,201 −63 

:thinking:

**Comment by reportxx** [comment]
I really like this.

**Comment by Oleg-Chashko** [comment]
Behavior at first startup:

https://user-images.githubusercontent.com/62497891/182027811-9a0c005e-a82a-46a3-ac49-94d1a8c87dcd.mp4

**Comment by Oleg-Chashko** [comment]
181879665-5c0a3bc6-1d33-41c2-9026-696a42dc428a

**Comment by Oleg-Chashko** [comment]
182021245-818404fb-fdb0-4ae9-a74c-1fd806a23aac

**Comment by Oleg-Chashko** [comment]
182021314-d569a653-92de-44b9-b69c-a9cc3e53359f

**Comment by Oleg-Chashko** [comment]
This change, for some reason, worsened the state of the interface at the moment.
Is it worth it? I don't know, it's up to you to decide.

**Comment by GaryElshaw** [comment]
> This change, for some reason, worsened the state of the interface at the moment. Is it worth it? I don't know, it's up to you to decide.

Some of these changes are explainable and others not so much. If you have a look at the code, there are zero changes to the code base with the exception of the font weight.

**Comment by Oleg-Chashko** [comment]
I used YOUR screenshots of your artifacts. You should know better. 
The last night version without these artifacts. 
I have a neutral attitude on this issue. 
The main thing is not to make it worse than it is.

[Transmission-154d5cf497.dmg](https://build.transmissionbt.com/job/trunk-mac/lastSuccessfulBuild/artifact/release/Transmission-154d5cf497.dmg)

P.S.: Primum non nocere. (©️Hippocrates)

**Comment by nevack** [comment]
Yup, maybe move it to 5.0.0?
It's really good feature for accessibility, but it's really hard to test everything properly.

@GaryElshaw I suggest to split this PR in several changes.

**Comment by GaryElshaw** [comment]
I think this should be in for 4.00, it's not a major change at all. If you look at the files diff, i've gone out of my way to ensure there are zero code changes from what currently exists in the code base with the exception of the font size and weight. 

I was extremely cognisant of potentially getting out of my depth with complex code changes and didn't want to undo any of the work that sweetppro has done.

**Comment by GaryElshaw** [comment]
> 181879665-5c0a3bc6-1d33-41c2-9026-696a42dc428a

Updated: 
SCR-20220801-nek

**Comment by GaryElshaw** [comment]
> > macOS UI font changes
> 
> > +2,201 −63
> 
> 🤔

Now i'm confused :-) What's confusing, Charles? By the way, that MainMenu.xib is not supposed to be there, it was added by mistake, but my git skills are lacking to remove it from the pr. If someone could teach me how to do that, i'd be grateful.

**Comment by ckerr** [comment]
> > > macOS UI font changes
> > 
> > 
> > > +2,201 −63
> > 
> > 
> > thinking
> 
> Now i'm confused :-) What's confusing, Charles? 

I'm confused why font changes take 2000 lines :smile_cat: 

> By the way, that MainMenu.xib is not supposed to be there, it was added by mistake, but my git skills are lacking to remove it from the pr. If someone could teach me how to do that, i'd be grateful.

`$ git rm MainMenu.xib`

**Comment by GaryElshaw** [comment]
> $ git rm MainMenu.xib

I had a bad feeling it couldn't be that simple!

**Comment by Petrprogs** [comment]
> > $ git rm MainMenu.xib
> 
> I had a bad feeling it couldn't be that simple!

I'm always afraid to use git...

**Review by nevack — CHANGES_REQUESTED** [review]
un-rename `MainMenu.xib`

**Comment by ckerr** [comment]
> This change, for some reason, worsened the state of the interface at the moment.

@Oleg-Chashko there have been a few different commits since this comment. Do the issues persist, or are they resolved?

> Yup, maybe move it to 5.0.0? It's really good feature for accessibility, but it's really hard to test everything properly.

@nevack what would be the safest way to move this forward

> +2,201 −63

@GaryElshaw it looks like MainMenu.xib is back. Is this intentional?

**Comment by GaryElshaw** [comment]
> it looks like MainMenu.xib is back. Is this intentional?

I tried the rm process, but git removes it from the branch completely, breaking the test build process :-(

**Comment by Oleg-Chashko** [comment]
> > This change, for some reason, worsened the state of the interface at the moment.
> 
> @Oleg-Chashko there have been a few different commits since this comment. Do the issues persist, or are they resolved?
> 

Checked the first issue, not fixed. I did not check further, so as not to waste time.
After these "improvements", I have no idea where to look for the bug. 
It can pop up everywhere. I'm not ready to look for bugs everywhere.

https://user-images.githubusercontent.com/62497891/182570943-468e6036-47ee-4a4b-a0c1-be489f51e91c.mp4

**Comment by Oleg-Chashko** [comment]
@GaryElshaw

A request to you: 
post the **latest** build with your changes assembled on **your** computer. 
I want to check something. 
I have some doubts.

**Comment by GaryElshaw** [comment]
My local build is seriously customised. I'd recommend using one of the binaries from TeamCity or the GitHub builds.

**Comment by Oleg-Chashko** [comment]
The question was asked because in your build TeamCity v.3.00+75a1f4fd49. 
No changes made from the previous build: macOS disable green maximize button on Inspector window #3563
This is what made me question whether your issue is based on the latest build.

**Comment by GaryElshaw** [comment]
Let's update the branch and see what happens!

**Comment by GaryElshaw** [comment]
Your reckons? @Coeur @fxcoudert

**Review by fxcoudert — CHANGES_REQUESTED** [review]
- I don't think `MainMenu.xib` should be still there
- Almost half of the text in the inspector panels ends up being bold. This is not consistent with typical macOS UI, for example in the System Preferences:
  
Capture d’écran 2022-08-08 à 11 36 45

**Comment by GaryElshaw** [comment]
`MainMenu.xib` being there, at all, is a mistake on my part and shouldn't be there. Sorry about that @fxcoudert :-(

I'm now wondering, instead of font size changes, do we need more space or do we need more direction between between options? The General Preferences is not a bad example, but we don't have these kind of graphical choices, currently, to break up the space like the system prefs window, we're relying entirely on text.

We don't have drop-down menu options, graphical choices, different types of check-boxes, line separation between items etc.

**Comment by RobFog** [comment]
> * Almost half of the text in the inspector panels ends up being bold. This is not consistent with typical macOS UI, for example in the System Preferences:

Absolutely

**Pull request closed without merging**
