### PR TITLE
Increase minimum font size of FileNameCell.mm from 9 to 10

### PR DESCRIPTION
**Pull request by GaryElshaw**
Another minor change to increase legibility.

Original:
SCR-20220804-jql

This pr:
SCR-20220804-4ka

### CODE REVIEW

**Comment by GaryElshaw** [comment]
@woojh3690 Personally, I'm not sure that information needs to be on a separate line, i think it could be good at the end.

SCR-20220804-jql

**Comment by woojh3690** [comment]
@GaryElshaw Cool! Better than my Idea.

**Comment by GaryElshaw** [comment]
> @GaryElshaw Cool! Better than my Idea.

I've logged it in the ideas discussion just in case i forget! https://github.com/transmission/transmission/discussions/3584

**Comment by GaryElshaw** [comment]
@Coeur Antoine, do you have time or interest to make these further changes happen?

**Comment by GaryElshaw** [comment]
Superseded by #3621

**Pull request closed without merging**
