### PR TITLE
[macOS] Revamp Toolbar Segments

### LINKED ISSUE #3498: macOS toolbar icons are inconsistent sizes
It has been like this for a long time, but i was wondering whether we could look at this before beta.

I get the thinking with having different sized icons between what are universal controls and, i guess, 'other', but it also doesn't make much sense to do this in the toolbar when, i think, the correct way to do this would be identical icon sizes, but the universal controls use, as they currently do, the fill icons.

Theoretically we could debate what is a universal control versus localised, but who has time for that, right? Or wrong?

SCR-20220721-ras

### PR DESCRIPTION
**Pull request by nevack**
Fixes #3498
Will be simplified a lot when deployment target is 10.15

image

image

### CODE REVIEW

**Comment by nevack** [comment]
Wanna mention, I have tested that all actions are working as expected, even with menus in Text Only NSToolbar's display mode.
But maybe it's worth checking on macOS 10.13 as minimum target.
I no longer have my Intel mac with me to test on VMs.

**Comment by sweetppro** [comment]
This PR removes the button hover state?
I already tried that in a previous PR then reverted back to the standard toolbar buttons because it gave a non standard toolbar look...

**Comment by nevack** [comment]
> This PR removes the button hover state? I already tried that in a previous PR then reverted back to the standard toolbar buttons because it gave a non standard toolbar look...

Hover works for me.
image

**Comment by sweetppro** [comment]
Hmm odd,
I cloned your repo, and built in Xcode.
Perhaps I checked out the wrong branch, I’ll try again later tonight

**Review by sweetppro — APPROVED** [review]
Yup, that was the issue. I'd checked out your main branch.
This looks good to go
👍

**Comment by GaryElshaw** [comment]
Thanks for your work here, @nevack, but the icons with text got even smaller :-(

SCR-20220724-nzx

This is excellent.

SCR-20220724-o0f

**Comment by nevack** [comment]
They got consistent.

**Comment by GaryElshaw** [comment]
And i'm very grateful!

**Pull request merged**
