### PR TITLE
Imply port 443 for https scheme

### PR DESCRIPTION
**Pull request by BowlesCR**
Attempt to fix transmission/transmission#4782
I'm not set up to compile the project, so this is edited "in the blind".

It also feels wrong to assume HTTP, but I can't figure what other schemes would end up here -- udp:// doesn't have a sane default port.

### CODE REVIEW

**Review by ckerr — CHANGES_REQUESTED** [review]
Thank you for making a PR!

There is a URL parser utility in libtransmission that we can use here; it has the brains to figure out the right port number so that we don't have to hardcode it here!

Could you update the PR to use that; it would look something like `#include <libtransmission/web-utils.h>` up at the top and then this section would be

```diff
     // hostname
     str += inf.st.is_backup ? QStringLiteral("<i>") : QStringLiteral("<b>");
-    auto const url = QUrl(inf.st.announce);
-    str += QStringLiteral("%1:%2").arg(url.host()).arg(url.port(80));
-
+    if (auto const parsed = tr_urlParse(inf.st.announce.toStdString()); parsed)
+    {
+        str += QStringLiteral("%1:%2").arg(QString::fromUtf8(std::data(parsed->host), std::size(parsed->host))).arg(parsed->port);
+    }
     str += inf.st.is_backup ? QStringLiteral("</i>") : QStringLiteral("</b>");
```

**Comment by ckerr** [comment]
Superseded by #4846.

**Comment by BowlesCR** [comment]
Thanks for the feedback, and getting back to it before I did.
Congrats on 4.0!

**Comment by ckerr** [comment]
Yeah, had a busy weekend cleaning up 4.0.0 bugs and just went ahead and did this one too.

@BowlesCR thanks for the bug report and for the PR! Please feel free to report more bugs / submit more patches! :+1:

**Pull request closed without merging**
