### PR TITLE
refactor: use tr_torrent_metainfo in makemeta tests

### PR DESCRIPTION
**Pull request by ckerr**
Replace `tr_info` with `tr_torrent_metainfo` in the makemeta tests.

### CODE REVIEW

**Comment by GScottElshaw** [comment]
In between these commits, I hope Christmas has been kind.

**Comment by GScottElshaw** [comment]
> In between these commits, I hope Christmas has been kind.

Is that a sardonic, No? Or a 'If only you knew'? I've had both :-)

**Comment by ckerr** [comment]
No, not sardonic :smile:

It's a little in limbo for a few days. Have some family coming to town in a bit that I haven't seen in awhile and am looking forward to. Yesterday was fine but Christmas will be when more family is here. :heart:

**Comment by GScottElshaw** [comment]
Excellent. I  always like the expectation of arrival more than the presence. One of my favourite songs, "Short doses, everyone". Christmas in New Zealand is always good - Summer; but i'm not sure if it's age or circumstance, it's the most un-christmas i think i've had.

**Pull request merged**
