### PR TITLE
test: add fuzzers

### PR DESCRIPTION
**Pull request by jvoisin**
As suggested in https://github.com/transmission/transmission/discussions/3703, this is a pull-request to add fuzzing to transmission, by @guidovranken

### CODE REVIEW

**Comment by ckerr** [comment]
That CI failure seems totally unrelated to this PR

**Comment by Pentaphon** [comment]
Looking forward to seeing what the fuzzers pick up. I hope this gets merged soon.

**Review by ckerr — COMMENTED** [review]
@jvoisin thank you for writing this! I'm sorry I didn't review it sooner; I didn't see that you'd marked it as "ready for review." That's my bad. Also, in this or any other future PRs, please feel free to @ me if you need review :smile_cat: 

- `BUILD_FUZZER` has to be manually injected into CMake and isn't documented. Is this intentional? I'm not super familiar with what OSS-Fuzz so maybe `BUILD_FUZZER` is exactly right. DYK what OSS-Fuzz needs?

- It might make sense to move `fuzzers/`  into `tests/libtransmission/` instead of putting them in the libtransmission source directory?

**Comment by ckerr** [comment]
> Looking forward to seeing what the fuzzers pick up. I hope this gets merged soon. I think there's a lot that people just haven't yet found during regular usage.

@Pentaphon any reason that you think that? These fuzzers are nice because they can expose test results upstream to OSS-Fuzz, but in terms of undiscovered issues -- these repeat existing fuzz tests that have been in test for over a year from f79a75c, a134445, e88ebbc, eb33b2f

**Comment by ckerr** [comment]
> Looking forward to seeing what the fuzzers pick up. I hope this gets merged soon. I think there's a lot that people just haven't yet found during regular usage.

@Pentaphon any reason that you think that? These fuzzers are nice because they can expose test results upstream to OSS-Fuzz, but in terms of undiscovered issues -- these repeat existing fuzz tests that have been in `tests/libtransmission/` for over a year from f79a75c, a134445, e88ebbc, eb33b2f 

I don't like the way you repeatedly have vague complaints about the project without specifics, e.g. "I think there's a lot [of bugs] that people just haven't found yet" and "[libtransmission needs an OS cache to perform reliably on modern OS's](https://github.com/transmission/transmission/issues/5622) when you won't define what that means or explain how libtransmission is not performing reliably.

If there is a bug or performance wart or whatever that can be described and measured, obviously that's something worth investigating. But these unsubstantiated, vague complaints aren't actionable, aren't productive, and just feel like you're dumping on the project for whatever personal reason.

**Comment by Pentaphon** [comment]
> I don't like the way you repeatedly have vague complaints about the project without specifics, e.g. "I think there's a lot [of bugs] that people just haven't found yet" and "[libtransmission needs an OS cache to perform reliably on modern OS's](https://github.com/transmission/transmission/issues/5622) when you won't define what that means or explain how libtransmission is not performing reliably.
> 
> If there is a bug or performance wart or whatever that can be described and measured, obviously that's something worth investigating. But these unsubstantiated, vague complaints aren't actionable, aren't productive, and just feel like you're dumping on the project for whatever personal reason.

My apologies if you feel this way, @ckerr but I mean no ill intent. I was simply expressing my enthusiasm for these Google-backed fuzzers because I think they will do a lot of work that the project needs done in the background that users may simply not have the time or knowledge to spot. I welcome any automated tests/reporting that can be done on the project while the humans sleep, so to speak. 

I am not "dumping" on the project. I just want the project to thrive, and large issues such as https://github.com/transmission/transmission/issues/5261 prove that many people are seeing performance issues that are not easy to solve, and things like Google-backed continuous fuzzing may prove pivotal in solving these issues. That's really all I am trying to express. 

I'll try to keep any thoughts that may be misconstrued as negative to myself in the future. Let's not have another back and forth ITT.

**Comment by jvoisin** [comment]
> BUILD_FUZZER has to be manually injected into CMake and isn't documented. Is this intentional? I'm not super familiar with what OSS-Fuzz so maybe BUILD_FUZZER is exactly right. DYK what OSS-Fuzz needs?

I think™ so, yes. Worse case, the nice OSS-Fuzz people will tell us what they're expecting once I/we throw a PR at them to integrate those fuzzers there :)

> It might make sense to move fuzzers/ into tests/libtransmission/ instead of putting them in the libtransmission source directory?

Sure, be my guest :)

**Comment by GaryElshaw** [comment]
I noticed fast_float just added [this](https://github.com/fastfloat/fast_float/pull/217/files). Useful? @ckerr

**Comment by Pentaphon** [comment]
@ckerr Any update on this?

**Review by ckerr — CHANGES_REQUESTED** [review]
Please move the new tests into `tests/libtransmission/`

**Comment by Pentaphon** [comment]
@ckerr my apologies. I thought @jvoisin was giving you permission to move the tests via his "be my guest" comment. Pinging him to hopefully get a response.

**Comment by ckerr** [comment]
@Pentaphon thank you, but FWIW no apologies necessary :smile_cat: I should've moved it as 'change requested' ages ago and appreciate the ping

**Comment by Coeur** [comment]
Assigning to both jvoisin and ckerr, since both of them have write access on this PR to move the files to the desired folder.

**Pull request closed without merging**
