### PR TITLE
Switch from Faenza to Win11 icon theme for Windows/Mac

### PR DESCRIPTION
**Pull request by mikedld**
Faenza doesn't seem to be actively worked on for the past few years, and starts missing some icons (like view-statistics). It also looks a bit outdated (not that it didn't before...)

This also fixes missing icons after #2200 got merged.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Does this require any additional work i can help with, Mike? @mikedld

**Comment by ckerr** [comment]
> Does this require any additional work i can help with, Mike? @mikedld

Can we please table this until after 4.0.0. I feel overwhelmed by all the recent icon PRs.

**Comment by Pentaphon** [comment]
I think this might be a good change to be made in time for 4.0.0 but that's just my opinion. New major version =  new look?

**Comment by Pentaphon** [comment]
> Can we please table this until after 4.0.0. I feel overwhelmed by all the recent icon PRs.

@ckerr since 4.0.0 beta is very close to coming out, do you think you could merge this for 4.0.0 beta so it has a "fresh coat of paint" and feels more like a fresh start for the Windows/Mac builds?

**Comment by Pentaphon** [comment]
Are we sure this icon theme should be delayed until 5.0.0-beta 1? That seems like it could take the better part of a decade if we include several 4.0.x or 4.1.x point changes. There will likely be a Windows 12 by the time 5.0.0 begins beta.

**Comment by ckerr** [comment]
@mikedld wdyt?

**Comment by mikedld** [comment]
This is a draft PR, setting any milestone on it makes little sense. That said, the change is non-functional and could go into any release, provided that it's finalized and tested. If someone wants to pick this up (including choosing a completely different icon theme that suits Windows builds better), be my guest.

**Comment by Pentaphon** [comment]
> If someone wants to pick this up (including choosing a completely different icon theme that suits Windows builds better), be my guest.

I sure hope so because the timing of 4.0.0's release would coincide perfectly with the availability of Win11 and any modern set of icons would look far better than the current outdated icons in 4.0.0-beta2. I see that @GaryElshaw offered to help so maybe he can still help get this PR merged.

**Comment by GaryElshaw** [comment]
Having a look now.

**Comment by GaryElshaw** [comment]
I'm going to break this down into technical and design. And an additional couple of notes i'm including that may or may not be issues that need filing. They're things i think are flaws - and things i'm noticing that also may have nothing to do with this icon set.

### Technical

Up and running on macOS Ventura using Homebrew's qt@5. I haven't been able to get this working with my Manjaro or Ubuntu installs, i think, because of something i have previously installed that required Farenza; and possibly something else within the Transmission code is still selecting Farenza as the default icon set?

The behaviour of launching transmission-qt has somehow changed between the last time i was regularly building the qt version and now. I don't know whether that's code changes on the Transmission side or changes that are specific to Ventura, or changes i've made to my setup. Once upon a time, i could launch the qt version without the terminal being an intrinsic part of using it by making an alias of the binary.

Here's the terminal output while running it:

`garyelshaw@Garys-MacBook-Air ~ % transmission-qt
dbus[7557]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!
qt.qpa.fonts: Populating font family aliases took 230 ms. Replace uses of missing font family ".AppleSystemUIFont" with one that exists to avoid this cost. 
zsh: bus error  transmission-qt
garyelshaw@Garys-MacBook-Air ~ % `

A heads-up issue. Aside from the 230 ms of my life i'm not getting back :-), Preferences/settings are not being saved between sessions.

### Design

Aesthetically, this is a no-brainer and should be merged. It's much more in keeping with the changes made to the web client for 4.0, AND, design-wise, the icon set feels less Windows 11, than an icon set that fits neatly with the simple monochromatic minimalism already happening in the web and macOS clients (something i was trying to do with the qt client on macOS with #3351).

**Some minor flaws**

At some point, it would be great if the project maintainers and contributors spent some time focusing on how the various clients behave with platform-specific Dark and Light modes. I've noticed this with the GTK and QT clients on Linux and macOS.

Here's the new theme in Dark mode on macOS.

SCR-20221212-kna

Yes, everything is actually still there, you are not 'the blind man, in the dark room, looking for the black cat, that isn't there'.

And in Light mode.

SCR-20221212-ko9

Yes, text contrast with the background is an ongoing issue.

I have zero idea what is going on with that blue line at the top or why the title of the top torrent is cut-off.

The padding in the search bar area is also an issue. Why the bar is shoved hard-right like that is a mystery.

SCR-20221212-ktg

The good news. Look how fresh and light the preferences/settings and torrent properties now look.

SCR-20221212-ksn

SCR-20221212-kqc

I'll follow up a little later on some other thoughts.

**Comment by Pentaphon** [comment]
> At some point, it would be great if the project maintainers and contributors spent some time focusing on how the various clients behave with platform-specific Dark and Light modes. I've noticed this with the GTK and QT clients on Linux and macOS.

Question: Windows 11 has light and dark modes, so is there a "Windows 11 dark-mode" icon set to go with this set for light mode? 

@mikedld perhaps this issue could be solved by going back to the original source of these icons and seeing if there's a dark mode set to go with this one. 

As qBittorrent recently showed with their latest 4.5.0 version: there needs to be 2 sets of icons for both dark and light mode instead of depending on 1 set for both modes as they did, which is why they are rolling back their new theme in their next version. We should be aware of that error they made and avoid it.

**Comment by GaryElshaw** [comment]
> Question: Windows 11 has light and dark modes, so is there a "Windows 11 dark-mode" icon set to go with this set for light mode?

Unfortunately, no. https://github.com/yeyushengfan258/Win11-icon-theme

**Comment by GaryElshaw** [comment]
Some suggested changes i'd like some Transmission-user feedback on. The opportunity to sort out the blankness of those folder icons has always bothered me, because it's confusing to me, which is which. Is it a magnet or a torrent file i'm trying to open, and without the tooltip, i wouldn't have a clue.

I've been messing around with some of the icon options by amalgamating different icons.

Opening a magnet could be:

Untitled2

Opening a torrent file could be:

Untitled

Removing a torrent:

Untitled3

**Comment by Pentaphon** [comment]
> Unfortunately, no. https://github.com/yeyushengfan258/Win11-icon-theme

I've requested dark mode over there since he's doing it for Linux desktops and all the major ones have dark mode anyway. Maybe he will be able to provide a dark mode set before 4.0.0 comes out. I'm going to look for new themes in the meantime...

>Some suggested changes i'd like some Transmission-user feedback on. The opportunity to sort out the blankness of those folder icons has always bothered me, because it's confusing to me, which is which. Is it a magnet or a torrent file i'm trying to open, and without the tooltip, i wouldn't have a clue.

Maybe the problem is having the folder in the first place. It looks like one big empty box. So we just need to forget the box. 

1) The open magnet button could just be a simple magnet icon. 

2) The open torrent could just be a that up-down arrow icon without the folder around it.

**Comment by GaryElshaw** [comment]
> Maybe the problem is having the folder in the first place. It looks like one big empty box. So we just need to forget the box.

I did versions of those too :-)

**Comment by Pentaphon** [comment]
> The only reason i'm kinda opposed to Adwaita is purely because it is so tied with Linux. I like the minimalism of the proposed theme. I'm also assuming the light/dark issues are something that will need to be addressed in code as well as icons. The good news is that because we're using a subset, inverting the colours shouldn't be too hard or time-consuming.

You're probably right. I was just keeping that on the table since we do have many Linux users. 

Just came across this new icon set with dark and light icons! It was just released a few months ago so it's even newer. 

https://github.com/kuroehanako/Eleven-icon-theme

**Comment by Pentaphon** [comment]
@GaryElshaw the dev for the original Win11 icon theme says his icons have both light and dark mode. 

https://github.com/yeyushengfan258/Win11-icon-theme/issues/74#issuecomment-1348371215

**Comment by GaryElshaw** [comment]
That appears to be a subset of the icons being used, and also being used on Windows (which may make a difference too).

**Comment by Pentaphon** [comment]
> That appears to be a subset of the icons being used, and also being used on Windows (which may make a difference too).

Are either of the Win11 icon repos viable enough to complete a dark and light theme for Mac and Windows?

**Comment by GaryElshaw** [comment]
I think so, but i'm also trying to keep in mind that having a dark themed icon base is futile if there is no will to code the application to use it.

**Comment by GaryElshaw** [comment]
A little help please @ckerr or @mikedld? It feels like i've almost got this into shape for a pr, but are stuck with getting MainWindow.cc to play ball. Here's what i have so far (on macOS-w/ qt using qt@5).

SCR-20221215-no8

The icon on the far left is to open a torrent file. The current code duplicates the same icon across both opening a torrent file and adding a magnet, so what you can see with the second icon is the torrent icon badged with a magnet icon. I'd like to untangle that and have completely separate icons for torrent and magnet.

Here's the current code.

` // icons
    [snip]
    QIcon const icon_open = icons.getThemeIcon(QStringLiteral("document-open"), QStyle::SP_DialogOpenButton);
    ui_.action_OpenFile->setIcon(icon_open);
    ui_.action_AddURL->setIcon(
        addEmblem(icon_open, QStringList() << QStringLiteral("emblem-web") << QStringLiteral("applications-internet")));
    ui_.action_New->setIcon(icons.getThemeIcon(QStringLiteral("document-new"),`

If i change that to the following, will that work?

`QIcon const icon_open = icons.getThemeIcon(QStringLiteral("document-open"), QStyle::SP_DialogOpenButton);
    QIcon const icon_open = icons.getThemeIcon(QStringLiteral("emblem-web"), QStyle::SP_DialogOpenButton);ui_.action_OpenFile->setIcon(icon_open);
    ui_.action_AddURL->setIcon(;`

**Comment by mikedld** [comment]
Per https://github.com/transmission/transmission/issues/814#issuecomment-454507550, I'd try `insert-link` or some other icon that doesn't require any type of manual overlaying.

**Comment by GaryElshaw** [comment]
`QIcon const icon_open = icons.getThemeIcon(QStringLiteral("insert-link"), QStyle::SP_DialogOpenButton);
    ui_.action_OpenFile->setIcon(icon_open);
    ui_.action_AddURL->setIcon(;`

Unfortunately produces:

`[ 70%] Building CXX object qt/CMakeFiles/transmission-qt.dir/MainWindow.cc.o
/Users/garyelshaw/Documents/GitHub/transmission-primary/qt/MainWindow.cc:152:17: error: redefinition of 'icon_open'
    QIcon const icon_open = icons.getThemeIcon(QStringLiteral("insert-link"), QStyle::SP_DialogOpenButton);
                ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/qt/MainWindow.cc:151:17: note: previous definition is here
    QIcon const icon_open = icons.getThemeIcon(QStringLiteral("document-open"), QStyle::SP_DialogOpenButton);
                ^
/Users/garyelshaw/Documents/GitHub/transmission-primary/qt/MainWindow.cc:154:32: error: expected expression
    ui_.action_AddURL->setIcon(;
                               ^
2 errors generated.
make[2]: *** [qt/CMakeFiles/transmission-qt.dir/MainWindow.cc.o] Error 1
make[1]: *** [qt/CMakeFiles/transmission-qt.dir/all] Error 2
make: *** [all] Error 2`

**Comment by GaryElshaw** [comment]
I'm still struggling to figure out what icon set is being used here on Manjaro _and_ Ubuntu after altering the Application.cc and CMakeLists files.

Screenshot from 2022-12-15 19-57-32

**Comment by Pentaphon** [comment]
> I think so, but i'm also trying to keep in mind that having a dark themed icon base is futile if there is no will to code the application to use it.

As long as you have a new and improved iconset to debut with 4.0.0 and a set of dark themed icons ready to go when somebody finally makes dark mode happen on Windows (and Mac?) then it's totally worth it. Thanks for taking this PR on, Gary. I think the project really needed this theme refresh.

**Comment by GaryElshaw** [comment]
After much gnashing of teeth... this works.

`QIcon const icon_open = icons.getThemeIcon(QStringLiteral("document-open"), QStyle::SP_DialogOpenButton);
    ui_.action_OpenFile->setIcon(icon_open);
    ui_.action_AddURL->setIcon(icons.getThemeIcon(QStringLiteral("insert-link"),`

A little progress. Now to fix that torrent icon and pr...

SCR-20221216-lxr

**Comment by Pentaphon** [comment]
> A little progress. Now to fix that torrent icon and pr...

Besides the torrent icon being too small, the potential issues I see from just that tiny screenshot are: (bear in mind I am not looking at the same thing you are on a real display so I may be wrong)

1) The magnet icon is a lot darker than the other icons, which look "inactive" or too faded by comparison. 
2) The  red "remove" icon is so thin as to be somewhat hard to see compared to the other icons. I would tweak that icon so the lines are thicker or go with another "remove" icon that stands out more. (this could just be screenshot compression, though)
3) I can see some users complaining about the current torrent icon taking up too little space compared to the rest of the icons. It needs to be encircled like in that earlier screenshot where you had it inside a folder. That would give it more a button feel and make it more spatially consistent with the other icons. 

Other than that, I like it. 

Were you able to give Transmission even more icons than it has on 3.0?

3.0 is missing icons for the following menus: 

Edit: Deselect All, Change Session
Torrent:  Queue, Set Location, Verify Local Data, Copy Magnet Link to Keyboard
View: Compact View, 
Help: Statistics, Donate

**Comment by GaryElshaw** [comment]
> 1. The magnet icon is a lot darker than the other icons, which look "inactive" or too faded by comparison.

Yep, that's because there is nothing selected. When a torrent is selected...

SCR-20221216-om9

I'll see if i can amend or replace the 'remove' icon.

**Comment by GaryElshaw** [comment]
Betterer? @Pentaphon 

SCR-20221216-p8b

**Comment by Pentaphon** [comment]
> Betterer? @Pentaphon

Yeah that's better, except that it needs to be adjusted to the same height as all the other icons. I did like that splash of red on the last remove icon but it would probably not work well with dark and light themes, especially considering how thin the lines are. 

I also like how you made the add torrent icon bigger and more distinct. 

This already looks way cleaner than the current theme. Nice work.

**Comment by GaryElshaw** [comment]
> it needs to be adjusted to the same height as all the other icons

Strangely, the measurement of that icon is supposed to be the same as the others. I agree about the former red one, but i'm liking the simple monochrome of this look, and if it ever needs to be changed for a dark theme, reversing to white on black should be easier.

**Comment by Pentaphon** [comment]
> Strangely, the measurement of that icon is supposed to be the same as the others.

Probably just an oversight by the original theme author because even a couple of roughly positioned 0.00 angle red lines shows it is much too big relative to the other icons. I'm sure you can resize it. I don't think it has to be absolutely perfect, but just not glaringly obviously bigger like it is now. 

line

**Comment by ckerr** [comment]
@mikedld looks like Faenza was added in 81c3eebbab09927ed675e92a0db7765907b699b6 back in 2015 with the commit message:

> Use Faenza (1.3.1) as fallback on systems which do not support icon themes

In 2023 are there still "systems which do not support icon themes" in the wild? Could we just ... remove the fallback icon theme altogether?

**Comment by mikedld** [comment]
Windows is one such system, macOS is another.

**Comment by ckerr** [comment]
> Windows is one such system, macOS is another.

Well, I guess if we want to support Windows and macOS :zany_face: 

I must be ignorant on this & it seems like a pretty important concept, so I'm just going to take the looking-like-an-idiot hit to try & learn about this. It seems impossible to me that people could even ship Qt apps without having the OS provide some icon set. How can they possibly look like native applications if they don't plug into the native icons?

**Comment by Pentaphon** [comment]
> Windows is one such system, macOS is another.

I'm pretty sure every Linux distro worth using has fallback system icons. I have yet to see any distro that doesn't.

**Comment by GaryElshaw** [comment]
@Pentaphon I just picked up where Mike left off #4376.

**Comment by ckerr** [comment]
Looks like this is superceded by https://github.com/transmission/transmission/pull/4376

**Comment by ckerr** [comment]
I've reopened this PR since https://github.com/transmission/transmission/pull/4376 has been closed and the user who PR'ed it is banned from the org.

OT1H, this is a 4 year old PR and I'm not trying to make work for anyone by reopening it.

OT2H, it seems like _maybe_ this is still an issue that someone could argue needs attention? If we have missing icons (e.g. view-statistics) then those missing icons should be addressed. So I'm reopening this partially to see if there's still interest in this and to see if there's consensus on whether this is something we should do.

In general I'd like to use as few custom icons as possible. My first thought would be to look at the icons we're bundling, and look at how they're used in the code, and see if there's any way to eliminate any of these. :man_shrugging: The fewer icons we ship ourselves, the more consistent the app will look on all platforms. Though maybe Mike did this back in 2015 when adding Faenza?

**Comment by ckerr** [comment]
> My first thought would be to look at the icons we're bundling, and look at how they're used in the code, and see if there's any way to eliminate any of these. 🤷‍♂️ The fewer icons we ship ourselves, the more consistent the app will look on all platforms.

Some of the lowest-hanging fruit: #7814, #7815

There are some more candidates that _might_ be good for using the Qt6 standard icons. If so, then we could remove our bespoke ones. Documentation is thin, but it looks like the Qt standard icons _might_ be using SF Icon / Fluent under the covers, which would be ideal for us --

@Pentaphon could you try running the PyQt6 script @ https://www.pythonguis.com/faq/built-in-qicons-pyqt/ on Windows and/or macOS and attach a screenshot of the resulting window? I'd like to see how these standard icons look on those platforms.

**Comment by nevack** [comment]
> > My first thought would be to look at the icons we're bundling, and look at how they're used in the code, and see if there's any way to eliminate any of these. 🤷‍♂️ The fewer icons we ship ourselves, the more consistent the app will look on all platforms.
> 
> Some of the lowest-hanging fruit: #7814, #7815
> 
> There are some more candidates that _might_ be good for using the Qt6 standard icons. If so, then we could remove our bespoke ones. Documentation is thin, but it looks like the Qt standard icons _might_ be using SF Icon / Fluent under the covers, which would be ideal for us --
> 
> @Pentaphon could you try running the PyQt6 script @ [pythonguis.com/faq/built-in-qicons-pyqt](https://www.pythonguis.com/faq/built-in-qicons-pyqt/) on Windows and/or macOS and attach a screenshot of the resulting window? I'd like to see how these standard icons look on those platforms.

macOS 26.2

```sh
brew install python pyqt
/opt/homebrew/bin/python3 pyqt6test.py
```

image

**Comment by ckerr** [comment]
We could eliminate a bunch of bundled icons by using some of these in toolbar's status filter dropdown:

| Label | Qt6 Standard icon | replaces Faenza icon |
|---|---|----|
| Active | SP_MediaPlay | system-run |
| Downloading | SP_ArrowDown | go-down |
| Seeding | SP_ArrowUp | go-up |
| Paused | SP_MediaPause | media-playback-pause |
| Finished | (none) | dialog-ok |
| Verifying | SP_BrowserReload | view-refresh |
| Error | SP_MessageBoxWarning | process-stop |

Any blockers here?

**Comment by ckerr** [comment]
sp-yaru

Ubuntu 24.04.3 - GNOME - Yaru theme

**Comment by mikedld** [comment]
I played around with this a couple weeks back, and my current thinking is that it might be better to go with icon fonts provided by the system — since we bundle this icon theme mostly for Windows and Mac, and they already have such fonts. That said, we'll be limited to the icons provided by those fonts which aren't always sufficient, so I'm also considering maybe bundling a single icon font to use on all systems, including *NIX (instead of system icon fonts and icon themes), if that's something others think is worth doing; or at least bundle an icon font to use on Windows and Mac.

The benefit of an icon font is that it's quite easy to support light and dark themes by providing a custom icon engine to render icons using current palette on the fly. This was something I was thinking of doing with SVG by replacing the color(s) in XML before loading, so in this PR I actually had to modify some SVGs to fix them up so that the primary color they use is the same everywhere; all in all it feels like an inferior approach.

**Comment by ckerr** [comment]
Oh hmm this looks very useful:

> Since Qt 6.7, Qt also provides access to the native icon library on macOS, iOS, and Windows 10 and 11.

Docs: https://doc.qt.io/qt-6/qicon.html#fromTheme-1

Commit: https://git.kroket.io/qt/qtbase/commit/9bbfdd6844f986de861336c0a5e3c43dbc8d1898

The only downside I see is that it requires Qt 6.7, but maybe that's not a showstopper?  The main place we need this is on the official Windows builds, and we can control what version is used there.

Maybe we should move this to a tracking issue? @mikedld I think your last comment and this one here are diverging a bit from the initial "Use Win11 icon theme" proposal in this PR

**Comment by Pentaphon** [comment]
> could you try running the PyQt6 script @ https://www.pythonguis.com/faq/built-in-qicons-pyqt/ on Windows and/or macOS and attach a screenshot of the resulting window? I'd like to see how these standard icons look on those platforms.

@ckerr This is from the latest Windows 11. 

win11

**Comment by ckerr** [comment]
Superseded by https://github.com/transmission/transmission/pull/7819

**Pull request closed without merging**
