### PR TITLE
[macOS] Update Preferences window sizing for Russian locale.

### LINKED ISSUE #3284: macOS - Russian localization - Widen the window in width
Russian localization

### PR DESCRIPTION
**Pull request by nevack**
Most of the changes are caused by Xcode touching XIB file.

Fixes #3284

### CODE REVIEW

**Comment by Oleg-Chashko** [comment]
@nevack, I can't check at the moment.

TeamCity (Sanity (Transmission)): _The build queue was paused one hour ago with the comment: Insufficient disk space. Please contact your system administrator._

**Comment by nevack** [comment]
@Oleg-Chashko Locally signed https://disk.yandex.ru/d/K9wlAn7SV74LDw

**Comment by Oleg-Chashko** [comment]
@nevack, 
Is excellent, Test passed ❤️

Screen Shot 2022-06-13 at 21 23 30

**Comment by ckerr** [comment]
Sanity CI has been having difficulty for a few days now; CI failure here is unrelated to PR

**Pull request merged**
