### PR TITLE
fix: macOS gui with Russian l10n does not fit lines of text. (Fixes #1963)

### LINKED ISSUE #1963: The Russian localization does not fit lines of text and etc.
- macOS Big Sur: v.11.6 (20G165)
- Transmission: v.3.00+b0f36a9841

1. (Ни од) -> (Ни одного) - Finish the word completely.
2. (X) -> (None) - Replace (X) with the English word (None).
3. (Нормаль...) -> (Нормальный) - Increase the width of the selection box so that the word fits completely.

Screen Shot 2021-10-15 at none

Screen Shot 2021-10-15 at 17 06 02

### PR DESCRIPTION
**Pull request by Oleg-Chashko**
The Russian localization does not fit lines of text and etc. #1963
Please check the corrections.

137604922-87e72f6a-a21e-4a99-acce-4737afbb1306
Screen Shot 2021-10-17 at 04 00 29
Screen Shot 2021-10-17 at 03 43 39

### CODE REVIEW

**Comment by Oleg-Chashko** [comment]
Fixed: (✕) -> Changed to (No Group) & (None)

Screen Shot 2021-10-17 at 03 02 14

**Comment by Oleg-Chashko** [comment]
Reduced the length of the phrase to fix this problem:
Fixed: Удаленное управление -> Удалённый доступ

Screen Shot 2021-10-17 at 04 38 47

**Comment by valcomm** [comment]
> 
> 
> Reduced the length of the phrase to fix this problem: Fixed: Удаленное управление -> Удалённый доступ
> 
> Screen Shot 2021-10-17 at 04 38 47

 Maybe "Удалённый контроль" would be closer to the meaning?  Just a thought...

**Comment by Oleg-Chashko** [comment]
> > Reduced the length of the phrase to fix this problem: Fixed: Удаленное управление -> Удалённый доступ
> > Screen Shot 2021-10-17 at 04 38 47
> 
> Maybe "Удалённый контроль" would be closer to the meaning? Just a thought...

Perhaps your proposal is better, I agree with that.
But my goal was to make the phrase as short as possible. If not for this goal, I would have left it as it is.

**Comment by ckerr** [comment]
Weird that appveyor is not reporting back in on this. The macOS changes shouldn't affect appveyor at all

**Pull request merged**
