### PR TITLE
feat: update GTK progress bar colours

### PR DESCRIPTION
**Pull request by GaryElshaw**
Another component of some consistency across Transmission clients. This is a look and feel compatibility change that matches #5762. 

Because of the GTK 4 and 3 colour hue diferences, there will be some hue changes in gtkmm 4.11 that will be more reflective of the changes in this pr (see #5858), but i'm happy with the changes in 3 for now, but marking as draft until gtkmm 4.11 is more readily available on the various distros.

GTK3 w/ Arc-Dark theme

Screenshot from 2023-08-17 19-23-53-obfuscated

Arc theme

Screenshot from 2023-08-17 19-24-47-obfuscated

GTK4

Screenshot from 2023-09-04 16-48-11-obfuscated

Transmission error

Screenshot from 2023-11-11 19-11-19-obfuscated

### CODE REVIEW

**Comment by ckerr** [comment]
I'd like a 2nd or even 3rd opinion, but those screenshots look nice to me.

**Comment by GaryElshaw** [comment]
> I'm not super confident in my own UI review abilities, so I'd like a 2nd or even 3rd opinion 😸

@mikedld Happy to give a second or third opinion?

**Review by mikedld — APPROVED** [review]
No text styled with `tr_error_color` on those screenshots so not sure, otherwise LGTM. Will need testing on other themes but probably okay to merge.

**Comment by GaryElshaw** [comment]
@mikedld Error included in the screenshots above.

**Comment by ckerr** [comment]
Pre-emptively saying this to help keep this PR out of inactivity limbo:

I have no idea who has the baton on this PR and who, if anyone, needs to do anything before this is ready to merge.

**Comment by GaryElshaw** [comment]
Mike said it's fine to merge, but i wanted to show the pr is complete.

**Comment by ckerr** [comment]
@mikedld with the updated screenshots, are you still OK to merge?

**Comment by mikedld** [comment]
Not sure why error screenshot doesn't use the same themes the other screenshots (i.e. Arc + Arc Dark), but the answer is still yes, it's good to merge ;)

**Comment by ckerr** [comment]
@GaryElshaw needs a 'Notes:' comment in the description

**Pull request merged**
