### PR TITLE
fixup! refactor: replace tr_info with tr_torrent_metainfo (#2397)

### PR DESCRIPTION
**Pull request by ckerr**
fix: subtle bug that was introduced into `main` last week. If there are two resume files for a single torrent --  one under the old naming scheme, one under the new naming scheme -- then the updated migrate-filename code could cause the newer file to be overwritten with the old one that presumably has older, out-of-date data.

### CODE REVIEW

**Comment by ckerr** [comment]
@mikedld updated in 4b76cdc

**Review by mikedld — APPROVED** [review]

**Comment by ckerr** [comment]
Sanity CI failure is unrelated to PR

**Comment by GScottElshaw** [comment]
Hi @ckerr the issue with File -> Save torrent file as... still exists with 3.00+ (3036a76beb) on MacOS. This issue originated during the tr_info commits.

Screenshot 2022-01-17 at 2 32 57 AM
.

**Comment by ckerr** [comment]
> Hi @ckerr the issue with File -> Save torrent file as... still exists with 3.00+ ([3036a76](https://github.com/transmission/transmission/commit/3036a76bebad6237a494a840d86a8afb122e80e9)) on MacOS. This issue originated during the tr_info commits.

Unless I'm misreading it, I don't think this is related to this PR...? Could you open a separate single-topic issue so this other regression can be tracked on its own?

**Comment by GScottElshaw** [comment]
Yep!

**Pull request merged**
