### PR TITLE
macOS small layout fixes to Info Window

### LINKED ISSUE #3489: [macOS] UI-Torrent Inspector, Improvement of the Activity tab
- At the moment:
3  At the moment

- Example - It is desirable:

3  Example - It is desirable

- Make the size a little bigger, there is free space for that:

noname

### PR DESCRIPTION
**Pull request by sweetppro**
unifies the margin between headers and content on the **Activity** tab and the **Options** tab in the **Info Window**

Fixes #3489.

**The General tab (unchanged):**
general

**Info Window - Activity/Options tabs Current:**
activity old
options old

**Info Window - Activity/Options tabs with this PR:**
activity new
options new

### CODE REVIEW

**Comment by ckerr** [comment]
@transmission/contributors this PR needs a UI review; anyone  wanna give it a go?

**Review by nevack — APPROVED** [review]
LGTM

**Comment by GaryElshaw** [comment]
The layout of the 'Options' tab in this pr looks sweet to me. I think the layout of the 'Activity' tab is a great example of the problem of how we deal with text in preferences.

A .5 or x1 increase in the heading values as well as bolding would help here. There isn't enough variation in the size of the head with the body. And then there's layout.

I'm not trying to be mean to *any one of us*, but from a design perspective with the text layout, it looks like we don't know what we're doing. It looks like we got stuck in what i like to describe as the MS Word hell of styles. Are we centring/justifying/left or right-aligning our text? To me, this looks like all of the above.

marked

Everything, i think, should be left aligned.

### Heading <br>
Parameter 1:
Parameter 2:

Alternatively, without any colon and using the weight of the typography.

### Heading <br>
**Parameter 1** text
**Parameter 2** text

**Comment by ckerr** [comment]
@GaryElshaw IDK, the screenshot you provided seems to have consistent use of `:` and right/left alignment with this Inspector listed in the [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/components/presentation/panels):

hud-style-panel_2x

**Comment by GaryElshaw** [comment]
That's also using a different but similar to what i suggested means of differentiation by using coloured text and different font weights.

Coloured Header

Coloured bold: Plain white text

The part of sweetppro's image i highlighted has 'Dates' and then the 'Added' part is indented. Then we have Downloading under a different header unindented.

It's not just the inconsistencies, it feels like we're cramping everything and bending over backwards so that the text conforms with an imagined symmetrical line of colons, but what the text is representing is dispensable to achieve it.

Some different font weights or would give some relief, i think.

**Review by fxcoudert — APPROVED** [review]

**Pull request merged**
