### PR TITLE
Feature/allow simultaneous downloads multiple peers with same address

### PR DESCRIPTION
**Pull request by krazak**
Transmission appears to ignore multiple peers with the same IP address, only serving them one at a time. I need to seed to multiple peers that are getting NAT-ed behind a shared IP. The tracker correctly recognizes all the peers, but the seeding instance only seems to recognize one at a time.
This change allow multiple atoms with the same IP address (different ports).

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
I really like the idea of this PR but since 4.0.0 is getting really close, I don't want to make any changes like this until 4.0.0 is out the door.

I'll take a look and do review tomorrow. This PR can keep progressing during the 4.0.0 freeze for use sometime after 4.0.0.

**Comment by himabindugit** [comment]
@ckerr do you know when this 4.0.0 will get released? do you have any ETA?

**Comment by ckerr** [comment]
> @ckerr do you know when this 4.0.0 will get released? do you have any ETA?

There's a discussion thread for it [here](https://github.com/transmission/transmission/discussions/3803).

**Comment by krazak** [comment]
@ckerr I tried to replace the transmission-daemon binary within our application docker container to test out the changes for this PR, however I was not successful.  I still see the ".c" files referenced in the log files (and not ".cc").  The clean way to do this is to generate the RPM package for CentOS and update the Dockerfile to install the package.  Is there some documentation you can provide that explains how I can generate the RPM package for CentOS.

I have run the following commands successfully:
```
$ git clone https://github.com/transmission/transmission Transmission
$ cd Transmission
$ git submodule update --init --recursive
$ mkdir build
$ cd build
$ # Use -DCMAKE_BUILD_TYPE=RelWithDebInfo to build optimized binary.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ make
```
I did see in your CI job that you are building a package for Fedora-36:
https://github.com/transmission/transmission/actions/runs/4018315504/jobs/6905317282

I just need to figure out who to do this for Centos7.  Please advise.  Thanks!

**Comment by tearfur** [comment]
Closed in favour of #5619.

**Pull request closed without merging**
