### PR TITLE
fix: "Unrecognized colorspace number -1"

### PR DESCRIPTION
**Pull request by Coeur**
Same as #5219 (March 14, 2023), but that fix was accidentally reverted in #5147 (created on March 5, merged on June 27).

### CODE REVIEW

**Review by ckerr — APPROVED** [review]
Good catch, thanks for re-submitting

**Review by sweetppro — APPROVED** [review]
Looks good

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
When I try to merge, I get this GH error message:

> Merge attempt failed
Head branch is out of date. Review and try the merge again.

**Comment by ckerr** [comment]
Superseded by https://github.com/transmission/transmission/pull/6049 because GitHub is acting goofy on this PR and I don't understand why :confused:

**Pull request closed without merging**
