### PR TITLE
symbolic tray icon for GTK client

### LINKED ISSUE #3312: [GNOME] Transmission should use monochrome tray icon
While I haven't used Plasma or really any other DE in a while, and therefore don't know there style, I know that on GNOME, tray icons are monochrome, and Transmission's isn't. This really isn't too important, or much of an issue, but it would be nice if it could fit in with everything else. Again, not much of an issue. Below's a screenshot, with some extensions, but it would look similar without them (just no transparent panel).
image

### PR DESCRIPTION
**Pull request by GaryElshaw**
Fixing conflicts with #3339. This PR resolves #3312.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
CI fail replicates https://github.com/transmission/transmission/pull/3347#issuecomment-1173266837

**Comment by GaryElshaw** [comment]
@ckerr Same pr as #3339 without the late conflicts.

**Comment by nevack** [comment]
> @ckerr Same pr as #3339 it just resolves the introduced conflicts.

You don't need to recreate PR for that.
Just use rebase, please.

**Comment by GaryElshaw** [comment]
I tried, but the git client rejected it.

**Comment by nevack** [comment]
> I tried, but the git client rejected it.

What exactly do you mean here?

**Comment by ckerr** [comment]
@nevack is right that it would've been better to resolve the conflicts in the previous branch but this PR isn't a dealbreaker for me and I don't want to get sidetracked on a git discussion. :slightly_smiling_face: 

Much more importantly, I don't fully understand this issue or this PR:

- When I run transmission-gtk from the installed Debian package, I get the same icon that @AppleMayExist screenshotted in https://github.com/transmission/transmission/issues/3312#issue-1274365507. :neutral_face: 
- When I build transmission-gtk from this PR, I correctly get a monochrome icon :tada: 
- When I build transmission-gtk from `main`, I correctly get a monochrome icon :open_mouth: 
- When I build transmission-gtk from the `3.00` tag, I correctly get a monochrome icon :dizzy_face:  


So:

1. I don't understand why this is different in the packaged version
2. I don't know how to test this PR since it seems to be working in `main` as wel
3. I don't really understand what's broken or why this PR fixes it

What I'd like to see is a concise explanation of the root problem of the bug, why this PR fixes it, and how I can test it on my own.

Marking this PR as 'needs clarification' pending an explanation of the above questions because I am confused

**Comment by GaryElshaw** [comment]
The icon that *should* be appearing in main that you are seeing should be the following. It's the same one as in issue #3312, yep? Black, white and red.

SCR-20220705-6q0

This pr is for a standard white GTK tray icon as Nevack screenshot below (icon second from left).

icon-change

**Comment by ckerr** [comment]
> The icon that should be appearing in main that you are seeing should be the following. It's the same one as in issue #3312, yep? Black, white and red.

No. As I just said, I'm getting the monochrome icon in this PR, and also in `main`, and also when building `3.00` from source:

main-screenshot

> - When I run transmission-gtk from the installed Debian package, I get the same icon that @AppleMayExist screenshotted in https://github.com/transmission/transmission/issues/3312#issue-1274365507. :neutral_face: 
> - When I build transmission-gtk from this PR, I correctly get a monochrome icon :tada: 
> - When I build transmission-gtk from `main`, I correctly get a monochrome icon :open_mouth: 
> - When I build transmission-gtk from the `3.00` tag, I correctly get a monochrome icon :dizzy_face:  
>
> So:
>
> 1. I don't understand why this is different in the packaged version
> 2. I don't know how to test this PR since it seems to be working in `main` as well
> 3. I don't really understand what's broken or why this PR fixes it
> 
> What I'd like to see is a concise explanation of the root problem of the bug, why this PR fixes it, and how I can test it on my own.

**Comment by GaryElshaw** [comment]
This PR is totally different with transparency where the black was, hopefully making it fit into whatever theme is being used. It's a kinda reverse hicolor_apps_symbolic_transmission-symbolic.svg.

Here's the Rawr: https://raw.githubusercontent.com/transmission/transmission/e45a8372f39e969c712ecb31b507453ea8a95f10/gtk/icons/hicolor_apps_scalable_transmission-tray-icon.svg

**Comment by ckerr** [comment]
Here is a screenshot of what I'm seeing when I run this PR. Note the hash is https://github.com/transmission/transmission/pull/3403/commits/e45a8372f39e969c712ecb31b507453ea8a95f10, the latest commit from this PR.

gtk-tray-icon-pr

>> - When I run transmission-gtk from the installed Debian package, I get the same icon that @AppleMayExist screenshotted in https://github.com/transmission/transmission/issues/3312#issue-1274365507. :neutral_face: 
>> - When I build transmission-gtk from this PR, I correctly get a monochrome icon :tada: 
>> - When I build transmission-gtk from `main`, I correctly get a monochrome icon :open_mouth: 
>> - When I build transmission-gtk from the `3.00` tag, I correctly get a monochrome icon :dizzy_face:  
>>
>> So:
>>
>> 1. I don't understand why this is different in the packaged version
>> 2. I don't know how to test this PR since it seems to be working in `main` as well
>> 3. I don't really understand what's broken or why this PR fixes it
>> 
>> What I'd like to see is a concise explanation of the root problem of the bug, why this PR fixes it, and how I can test it on my own.

**Comment by GaryElshaw** [comment]
That's not the tray icon.

**Comment by ckerr** [comment]
>>> What I'd like to see is a concise explanation of the root problem of the bug, why this PR fixes it, and how I can test it on my own.

**Comment by ckerr** [comment]
> That's not the tray icon.

What is it? Why does it appear / disappear when I click on `Prefs > Desktop > Show Transmission icon in the notification area`? Where should I look for the tray icon?

**Comment by GaryElshaw** [comment]
The root problem is that the Transmission tray icon is not monochromatic, it is red, black and white, while other GTK tray icons are white. Ours sticks out and doesn't play nicely in the tray.

The image you posted is the about information, this pr doesn't touch the icon for the application or the about dialog, it is uniquely for the GTK tray.

**Review by ckerr — CHANGES_REQUESTED** [review]
Needs explanation about what the root cause of the bug is, how this PR fixes it, and what I can test to confirm that this PR works but `main` does not

**Comment by ckerr** [comment]
> The root problem is that the Transmission tray icon is not monochromatic, it is red, black and white, while other GTK tray icons are white. Ours sticks out and doesn't play nicely in the tray.
> 
> The image you posted is the about information, this pr doesn't touch the icon for the application or the about dialog, it is uniquely for the GTK tray.

The About dialog is only there to show the commit hash. The important part is the tray icon:

tray-icon

What I am trying to understand is

1. Why I get that icon any time I build from this branch, or from main, or from the 3.00 tag, but not when I run the system-installed transmission-gtk package.
2. Why this PR is a fix when I see the same tray icon in this PR and in main
3. How I can test this PR to see behavior different from main

I feel like I've explained this several times already but maybe I didn't make the system tray icon clear in the screenshots?

**Comment by GaryElshaw** [comment]
Now i understand. I couldn't see the tree from the very large forest.

I don't know why that icon is showing up when building using this pr, this is a totally different icon.

**Comment by ckerr** [comment]
Also: I've spent the last hour now testing this PR, building various versions of Transmission  to compare it against, and also writing & rewriting my findings in this PR, less than 12 hours after the contributor discussion about how much of the project's oxygen is being taken up by icon PRs.

@GaryElshaw since you offered in that thread to "spend time fixing [any problems]", please do some research on this and update this PR when there are solid answers. Linux is free and can be installed on VMs.

**Comment by GaryElshaw** [comment]
Any guidance on the best way to install these last remaining dependencies on ubuntu?

`Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.50.1;giomm-2.4>=2.26.0'
--   No package 'gtkmm-3.0' found
--   No package 'glibmm-2.4' found
--   No package 'giomm-2.4' found
`

**Comment by ckerr** [comment]
I've marked this PR as a draft. Please [follow these guidelines](https://github.com/transmission/transmission/pull/3347#issuecomment-1175222406) about when to flag this as ready for review. Thank you!

**Comment by GaryElshaw** [comment]
I have ubuntu installed, have the binaries built, but are stumbling to get the dependencies for the gui client. Is there an efficient way for me to get these modules installed?

-- Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.50.1;giomm-2.4>=2.26.0'
--   No package 'gtkmm-3.0' found

**Comment by ckerr** [comment]
@GaryElshaw two days ago you wrote:

> #3403, i think, is an easy fix. It also fixes another of the svg-related issues, and also provides a proper foundation for the GTK tray that users will use. I tend to think this pr means 'broken no more'. Again, any problems, i'm happy to spend time fixing them.

...and after I did testing on this PR and took the time to write up my findings, make screenshots of multiple branches, and  then explain the screenshots and asked for changes... **then** you closed the PR and deleted the branch WITHOUT EVEN COMMENTING. :angry: 

It feels like the message you're sending me is that you're OK with *talking* about why this PR is important, and you're OK with *me* doing testing on it, but you won't do it yourself. Maybe you feel like my time is less valuable than yours. Seriously dude, I genuinely feel insulted. For you do to this at this point... I just don't know.

**Comment by ckerr** [comment]
NGL, it feels like a personal insult when you offer to do the work to fix any issues with this PR, so I spend an hour testing branches, screenshotting them, uploading them here, explaining them, describing the problem, and explaining that I need to know how to test the change ... and then you close & delete the PR **without even a comment**. :angry: 

It feels like you're fine with *me* testing and figuring it out but you're not willing to do it yourself. Maybe my time isn't as valuable as yours, IDK.

**Comment by GaryElshaw** [comment]
Yesterday, i mistakenly installed ubuntu over my mac partition when trying to install ubuntu from usb to usb. I spent 12 hours working on getting all of the dependencies in place on a platform i am unfamiliar with. I have the binaries up and running, but the last hurdle of getting the gui client built hit this roadblock.

-- Checking for modules 'gtkmm-3.0>=3.24.0;glibmm-2.4>=2.50.1;giomm-2.4>=2.26.0'
--   No package 'gtkmm-3.0' found

The change i made yesterday, reverting the gresource file, may make the difference. It's certainly the one thing i can think of that is different from the original pr. If you take a look at the original pr, Nevack had this working, then you made some changes, i made some changes, and now i'm in a Catch-22. If i can't build it, i can't pr it. If i don't have a willing collaborator, i can't pr it because i can't build it.

And i will now need to spend another half a day because my macOS install is hosed, including the rescue partition. My time is as valuable as yours, but 24 hours for an icon that is less than 1k in size is not worth my time. It doesn't help when i feel like the consequence is a reminder that i'm somehow not sufficiently dedicated to Sparkle Motion.

**Comment by GaryElshaw** [comment]
I'm spending time in Manjaro Gnome for a few days, until i can get a proper efi sorted, and quite like it. 

I'm trying to figure out how different linux distros/contributors/pkg-makers etc might be building their own versions with what appears to be their own icon sources, but the version for this distro looks exactly as i wanted it to. Note how the Transmission icon more closely resembles the macOS version, and also how the tray icon plays nicely with its neighbours compared with #3312.

I managed to hunt down and install all of the dependencies, but sadly cmake isn't seeing them, so i still can't build the gui client :-(

transmission-info

tray

**Pull request closed without merging**
