### PR TITLE
Fix red link in Xcode project

### PR DESCRIPTION
**Pull request by Coeur**
watchdir-common.h was deleted in #3606

### CODE REVIEW

**Comment by livings124** [comment]
Thanks

**Comment by ckerr** [comment]
Notes: Fixed various XCode and CMake build issues.

**Comment by GaryElshaw** [comment]
Notes: Fixed various Xcode and CMake build issues.

**Comment by Coeur** [comment]
Notes: Fixed various Xcode and CMake build issues.

**Pull request merged**
