### PR TITLE
fix: Port-Forwarding never comes back after failure

### PR DESCRIPTION
**Pull request by Coeur**
Fix: #5464

Credit: @stefantalpalaru in https://github.com/stefantalpalaru/transmission-og/pull/15

Related: #6718

### CODE REVIEW

**Comment by tearfur** [comment]
I already have #6718 for this.

**Comment by Coeur** [comment]
I know, I wrote it in the description.

**Comment by tearfur** [comment]
Hmm, then what is this PR for then? It is a subset of #6718.

**Comment by Coeur** [comment]
> Hmm, then what is this PR for then? It is a subset of #6718.

In its previous state, your PR was a draft and was a bit harder to review with all the extra changes. Now presently both PR are identical. So closing mine.

**Pull request closed without merging**
