### PR TITLE
Use CommonCrypto on MacOS

### PR DESCRIPTION
**Pull request by romanbsd**
MacOS already has all the required functionality in the Security and CommonCrypto frameworks.

### CODE REVIEW

**Comment by mikedld** [comment]
The functionality was there for a long time now, see e.g. https://github.com/mikedld/transmission-old/commit/b64a242fbd0c1eb96eb8bdc991e4b1cfe068df8f#diff-d450e19ed0ac066bef3e12ee9e1abbd4 for my old implementation meant to be merged in at some point. What I don't like is that the functions used by me back then and by you now aren't part of public API and thus aren't guaranteed to be present in the future or have the same parameters / return types.

**Comment by romanbsd** [comment]
The DH is not in the public headers, true. It didn't change in the last decade, but I see your point.

**Comment by romanbsd** [comment]
https://github.com/soyersoyer/SwCrypt uses CCDHCreate, CCDHGenerateKey, etc. which are part of CommonCrypto (and not Security) framework.

https://github.com/Apple-FOSS-Mirror/CommonCrypto/blob/master/Source/CommonCryptoSPI/CommonDH.h

I wonder if this API is considered stable (albeit also private)...

**Comment by ckerr** [comment]
Just a heads-up, Transmission has moved away from the [GitFlow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) workflow: `master` is now the default branch and `develop` has been removed.

To move your branch forward, please re-PR it to `master` rather than `develop`. Thank you!

**Pull request closed without merging**
