### PR TITLE
perf: saxlike benc pt 6 use benc handler in torrent metainfo

### PR DESCRIPTION
**Pull request by ckerr**
Part 6 in the "faster benc decoding" series. The previous PR was #2531. The goals of the series are discussed in #2490.

This PR uses the new benc parser for parsing .torrent files. This is the main place the benc parser is used, so this is an important step in the series.

### CODE REVIEW

**Comment by GScottElshaw** [comment]
> literally lust

Fair enough :-)

**Comment by ckerr** [comment]
> > literally lust
> 
> Fair enough :-)

It's a very sexy PR

**Comment by GaryElshaw** [comment]
That's a substantial PR. Are you sure you're not wholly remaking Transmission?

SCR-20220521-661

**Comment by ckerr** [comment]
> That's a substantial PR. Are you sure you're not wholly remaking Transmission?

Eh, it's because I merged instead of squash-merging. This PR is getting old because it still feels off, so I keep merging `main` into it to keep it up-to-date. That large # of commits are all pre-existing commits from `main` :smile_cat:

**Comment by GaryElshaw** [comment]
Congrats on landing all this work Charles.

**Pull request merged**
