### PR TITLE
macOS revert fullscreen changes

### PR DESCRIPTION
**Pull request by sweetppro**
as described in #3297

### CODE REVIEW

**Comment by ckerr** [comment]
@sweetppro does this need code review / ui review, or is it just a straight revert? If the latter, I'll got ahead and merge it w/o calling for review

**Comment by sweetppro** [comment]
> @sweetppro does this need code review / ui review, or is it just a straight revert? If the latter, I'll got ahead and merge it w/o calling for review

ive reverted the changes manually, but it does put the codebase back into the pre fullscreen state

**Comment by ckerr** [comment]
@sweetppro I think this PR has conflicts now that #3303 has landed in main

**Comment by sweetppro** [comment]
I’m away from my computer now, I’ll fix it when I get home. I tried on my phone…. But it’s super painful

**Pull request merged**
