### PR TITLE
Add readme with light setup instructions; minor UI tweaks

### LINKED ISSUE #4209: WebUI Peer list too narrow
### What is the issue?

IPV6 Addresses can overflow.

2022-11-17-193220_914x583_scrot

### Which application of Transmission?

Web client

### Which version of Transmission?

Latest main branch

### LINKED ISSUE #5639: Limit input width in Add dialog of Web
### What is the issue?

1. Open Transmission Web
2. Click `Add` icon to show new torrent dialog
3. Set `.torrent` file with long name

Actual result:

`<input>` field became longer than dialog width. UI looks broken.

Expected result:

`<input>` field is limited. You can’t see all file name but UI doesn’t look broken.

Captura desde 2023-06-19 14-06-08

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.3

### PR DESCRIPTION
**Pull request by dareiff**
These are very minor changes that cover a few issues:

- Fixes #4209

On very small screens (for-phone-only), we modify width on some fields for less overlap. But we also truncate using `text-overflow: ellipsis` and `overflow-x: hidden`.

- properly style up/down speed icons

Moved SVG contents into index.html so we can make these style changes based on the `prefers-color-scheme` media query.

I also set a min-width, text-align: right on the download/upload label so they aren't shifting when going from 1 kB/s to 800 Mb/s.

- Add README for `web` directory

It made sense to add some super simple getting-started instructions for the directory. So, super light instructions on getting started with development, plus a very simple bookmarklet to anonymize the interface with lorem ipsum before screenshotting.

- Fixes #5639

Add a width to the open-torrent file input, but also increase the modal dialog container size.

<details>
<summary>Images of the changes:</summary>

Screenshot 2023-07-21 at 11 15 48 AM

Screenshot 2023-07-21 at 11 48 22 AM

Screenshot 2023-07-21 at 11 51 40 AM

</details>

### CODE REVIEW

**Comment by GaryElshaw** [comment]
From my perspective, reviewed and approved.

**Comment by ckerr** [comment]
@dareiff I like everything in this PR, but have a request for future PRs -- please keep them single-topic. There are a couple of unrelated things pushed into a single PR here which makes it difficult, e.g when cherry-picking bugfixes or when writing a one-sentence summary for the Release Notes generator.

Looks like everything here is either bugfixes or docs so I'll take this one as-is and cherry-pick the entire commit back to 4.0.x, but in future please keep separate changes in separate PRs. Thanks!

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: Fixed overflow when rendering peer lists and made speed indicators honor `prefers-color-scheme` media queries.

**Comment by GaryElshaw** [comment]
Charles, can you please take a look at the contributor controls available to me for review and approval?

**Comment by ckerr** [comment]
> Charles, can you please take a look at the contributor controls available to me for review and approval?

@GaryElshaw you don't appear to currently be a member. TBH I don't remember why this is the case; my *guess* is that I had to remove you from the org as a prerequisite of giving you a ban last year.

**Comment by ckerr** [comment]
I've sent you a new invitation.

**Comment by GaryElshaw** [comment]
Thanks Charles, unfortunately none of the features of assigning or closure have appeared. Is there something i need to do on my end?

**Comment by valynor** [comment]
Unfortunately I'm still seeing overflows in the peer list, the status "characters" are sometimes across 2 lines. 

Similarly on the top right corner of the main web interface I saw the download speed formatted across 2 lines like this: 
12,5
MB/s

**Comment by GaryElshaw** [comment]
> Similarly on the top right corner of the main web interface I saw the download speed formatted across 2 lines like this:
> 12,5
> MB/s

Noted in #5951

**Pull request merged**
