### PR TITLE
Update Greek translation

### PR DESCRIPTION
**Pull request by gmou3**
Add missing translations and refine a few previous translations.

### CODE REVIEW

**Comment by ckerr** [comment]
Hi @gmou3, thanks for the PR!

Thank you for the improvements, but please submit them [here](https://explore.transifex.com/transmissionbt/transmissionbt). The translations in this repo get overwritten before release by syncing them from that site, so I can't merge this PR -- your changes would get overwritten the next time we sync from Transifex.

https://github.com/transmission/transmission/blob/main/docs/Translating.md has a short primer on how to get started on Transifex.

Thank you again!

**Comment by gmou3** [comment]
Ok, I sent a join request on transifex.

**Comment by gmou3** [comment]
I still don't seem to have access on transifex. :(

**Comment by gmou3** [comment]
Greek is now fully translated on `transifex`!

I'll keep an eye for improvements mostly in the `GTK` app that I use.

**Pull request closed without merging**
