### PR TITLE
Mac: Added an option to select torrent double-click action in preferences

### PR DESCRIPTION
**Pull request by ekreutz**
uTorrent-like feature for choosing what will happen when a torrent list item is double-clicked.

**Possible values are:**

- Show info (this is the previous value and the default)
- Pause/Resume (pause or resume seeding)
- Show in Finder (shows the selected file(s) in Finder)

double_click_preferences

### CODE REVIEW

**Comment by ekreutz** [comment]
@mikedld what do you think?
Obviously, this is far from an urgent feature but it'd sure be a nifty addition :)

**Comment by mikedld** [comment]
I have no strong feelings about it but it looks like a nice and concise change overall. I'm hesitant to accept any Mac client PRs though until PR for #140 lands, so if you want this one to be merged I suggest you help there.

**Comment by ekreutz** [comment]
Brilliant. I'll check it out 👍

**Comment by livings124** [comment]
While I really do appreciate them pr, I don't think this is a level of customizability that the app needs. I don't think the demand is there.

**Pull request closed without merging**
