### PR TITLE
fix: Add tooltip explaining why auto adding for magnets is unavailable.

### LINKED ISSUE #5034: "Display a window when opening a magnet link" settings checkbox greyed out
### What is the issue?

Screenshot 2023-02-24 at 20 18 46

After updating to version 4 I can no longer disable this setting.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.1

### PR DESCRIPTION
**Pull request by nevack**
Fixes #5034

### CODE REVIEW

**Comment by ckerr** [comment]
Notes: Fixed minor UI bugs, e.g. layout and control alignment.

**Comment by Coeur** [comment]
@ckerr I see that we started merging new strings in #5035. So it means we can merge the strings-related changes now:
- #4452
- #4419 
- #4169 
And the build fixes:
- #4931 
- #4919

**Comment by ckerr** [comment]
@Coeur, 

- 1 breaks existing translations
- 2 and 3 are new features
- 4 is unmerged since afaict this is the first time it's been described as a fix. I'm unsure what is broken? 
- 5 is maybe ok? But it has nothing to so with strings so I'm not sure why it's being discussed here.

Please help get us past the bugfix cycle faster by contributing on mac client bug reports e.g. https://github.com/transmission/transmission/issues/4683

**Comment by ckerr** [comment]
I figured this was semver:patch since it fixes a UI issue that can confuse users, but yes it does introduce a new untranslated string so I agree it is in a grey area. If you feel strongly about this I'll revert the commit and earmark it for 4.1.0.

**Comment by Coeur** [comment]
No need to revert. 4 (aligning builds between ninja and xcode) and 5 (warnings) are good to merge for 4.0.2 too.

**Comment by ckerr** [comment]
Then let's discuss 4 and 5 in their own PRs. I'm still unclear on what 4 fixes but am open to discussion on both 4 and 5.

**Pull request merged**
