### PR TITLE
refactor: add more C++ glue for the session network layer

### PR DESCRIPTION
**Pull request by dmantipov**
Fold session's DHT, UTP, and a few core network functions into `tr_session` members and methods, adjust related code. Fix `-DENABLE_UTP=OFF` configuration as well.

### CODE REVIEW

**Comment by dmantipov** [comment]
This follows https://github.com/transmission/transmission/pull/3794. BTW, an overall design concern is that `tr_session` becomes monstrously huge. Any thoughts on this?

**Comment by ckerr** [comment]
Yeah I'd absolutely keep these all in separate pieces and then have something act as a mediator between them as necessary.

:+1: on C++ifying this code but `tr_session` is already insanely big

**Comment by Coeur** [comment]
@dmantipov kindly rebase your PR, thanks

**Comment by ckerr** [comment]
Oog. I've made some changes in the "tr_session Lifecycle PR Arc" that cause a lot of shear in this PR :crying_cat_face:

**Comment by ckerr** [comment]
I think I'm going to close this one as just being too far out-of-date from `main` but I'm still on-board with the idea of moving some of this code out of `tr_session` into a more standalone block. If you wanted to resubmit this for a `4.x.0` release I'd be happy to look at it again

**Pull request closed without merging**
