### PR TITLE
refactor: autogenerate the macOS client's Message Log dots

### PR DESCRIPTION
**Pull request by Coeur**
This supersedes (the now closed) #3098 by adopting generated icons directly.

For simplicity, I used the same shape as group icons, but we can also adopt a different design if we want.

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
That's pretty cool. Just from the code side, I love the diff, i.e. the idea of generating these instead of bundling them.

I'll defer to the mac people whether or not these icons are macish though, e.g. .do they work as icons on a  mac desktop app :smile_cat:

**Review by sweetppro — COMMENTED** [review]
this code looks good, but is it possible to make the icons smaller:
Screen Shot 2022-06-06 at 10 52 37 pm

it'd be great if there were also icons in the popup menu

**Comment by Coeur** [comment]
Which popup menu? Do you have a screenshot?

**Comment by GaryElshaw** [comment]
A wider philosophical issue. The more the ui is hard-coded, the less opportunity for users to customise Transmission's appearance.

**Comment by GaryElshaw** [comment]
> That's pretty cool. Just from the code side, I love the diff, i.e. the idea of generating these instead of bundling them.
> 
> I'll defer to the mac people whether or not these icons are macish though, e.g. .do they work as icons on a mac desktop app 😸

Yes

**Comment by sweetppro** [comment]
> Which popup menu? Do you have a screenshot?

Perhaps it’s a dropdown menu, I get them mixed up all the time… the menu selector at the bottom left of the window. In the current nightly, there are icons included with the text.

**Comment by GaryElshaw** [comment]
@Coeur MessageWindowController.mm + MessageWindow.xib

**Comment by sweetppro** [comment]
@Coeur here's the current menu:

menu

**Comment by Coeur** [comment]
> A wider philosophical issue. The more the ui is hard-coded, the less opportunity for users to customise Transmission's appearance.

Well, it's simply coded differently? Dynamic customisation of this part was not a feature. Build-time customisation is simply a matter of adding new assets and changing what is returned by `+ (NSImage*)iconForLevel:(NSInteger)level`.

It's also nice for overall user experience to have a UI that is consistent with the system UI (macOS, Windows, Ubuntu, ...), so in theory we could be using the system icons NSStatusUnavailable, NSStatusPartiallyAvailable, NSStatusAvailable, but that's only 3 colours and we need 5.

**Comment by GaryElshaw** [comment]
These are still far too big Antoine, they should be around 16px.

SCR-20220608-k9x

**Comment by sweetppro** [comment]
@Coeur this is looking great, I prefer the icons size a little smaller though
this size looks nice to me:
`#define ICON_WIDTH 10.0`
Screen Shot 2022-06-08 at 6 18 02 am

**Comment by sweetppro** [comment]
> I'm surprised by how it renders for Gary. Let's try by increasing the inset first, then if it still doesn't work, I'll try reducing the icon size.

looking good 👍

Screen Shot 2022-06-08 at 7 29 22 pm

**Comment by Coeur** [comment]
@GaryElshaw can you verify if the size is good for you?

**Comment by GaryElshaw** [comment]
Much better, thanks Antoine. One thing i noticed is how the dots respond to changing the size of the 'Message' column, see how the placement of the dots changes depending on the line-wrap?

**Comment by Coeur** [comment]
I assume that this behaviour was already present before?
I guess that we could top-align the icon to make it stable?

**Comment by GaryElshaw** [comment]
> I assume that this behaviour was already present before? I guess that we could top-align the icon to make it stable?

Yep, i just checked, it's always been there :-(

**Pull request merged**
