### PR TITLE
make mac icons a consistent size

### LINKED ISSUE #3100: macOS, v.3.00+, Icons should preferably be the same size
Screen Shot 2022-05-15 at 22 17 35

### PR DESCRIPTION
**Pull request by GaryElshaw**
Hopefully fixes #3100

### CODE REVIEW

**Comment by Coeur** [comment]
Thanks. But can you keep it 18x18px and 36x36px?
Both buttons and both images are sized to be 18x18px (the other image is TurtleTemplate).
Capture d’écran 2022-05-17 à 04 03 28

**Comment by GaryElshaw** [comment]
> Thanks. But can you keep it 18x18px and 36x36px? Both buttons and both images are sized to be 18x18px (the other image is TurtleTemplate). Capture d’écran 2022-05-17 à 04 03 28

It sucks, but Unfortunately the problem _is_ the height.

**Comment by Oleg-Chashko** [comment]
Please, make the turtle a little bigger. Take the size of the pinion as the base size. Thanks.

**Comment by GaryElshaw** [comment]
> Please, make the turtle a little bigger. Take the size of the pinion as the base size. Thanks.

They all have very unique profiles - essentially a circle, a rectangle, and a pyramid. The danger in adapting them further is that they look even less uniform than they currently do. As it stands, each of these are at different sizes and I don't think they'll tolerate more resizing without adjusting the lower bar.

**Comment by Oleg-Chashko** [comment]
Bottom alignment Example:

Use the icons from the archive. There should be a positive result.

[Archive.zip](https://github.com/transmission/transmission/files/8709387/Archive.zip)

Screen Shot 2022-05-17 at 16 53 11

**Comment by GaryElshaw** [comment]
> Bottom alignment Example:
> 
> Use the icons from the archive. There should be a positive result.
> 
> [Archive.zip](https://github.com/transmission/transmission/files/8709387/Archive.zip)
> 
> Screen Shot 2022-05-17 at 16 53 11

Now i'm even more confused. Those images are the original ones i edited and reduced from 36x36 to 32x32. https://github.com/transmission/transmission/pull/3103/files

**Comment by Oleg-Chashko** [comment]
I apologize for not writing this to you right away.

Icon (canvas) size remains 36x36 but drawing size is now 32x32
Icon (canvas) size remains 18x18 but drawing size is now 16x16

**Comment by GaryElshaw** [comment]
@coeur @sweetppro I just noticed this in the MainMenu.xib. I wonder why that default drop-down icon on the far left was never implemented?

SCR-20220518-r8k

Currently playing around with the recycling icon because we don't recycle, we literally trash :-(

CleanupTemplate copy

**Comment by sweetppro** [comment]
The trash icon indicates deleting the Torrent. But we are actually removing it from the interface.

i personally think the recycle icon, while maybe not perfect - is better than a trash can

**Comment by GaryElshaw** [comment]
@Coeur *ping*

**Comment by mangosplat** [comment]
@GaryElshaw you haven't changed it to the upsized icons @Oleg-Chashko has created

**Comment by GaryElshaw** [comment]
> @GaryElshaw you haven't changed it to the downsized* icons @Oleg-Chashko has created

Because #3113 will rebase the changes and make Oleg's request and this PR moot. @sweetppro

**Comment by GaryElshaw** [comment]
Superseded by #3113

**Pull request closed without merging**
