### PR TITLE
Fixup: Replace 'gear' icon with 'ellipsis'

### PR DESCRIPTION
**Pull request by GaryElshaw**
The current icon is inappropriate for two reasons. 

Historically, the gear icon used to represent preferences in MacOS X (and even earlier OS 7 - 9), but is no longer appropriate for this particular function because of two reasons.

1. The icon is not a shortcut to global preferences, but a specific subset.
2. More importantly, unlike the other functions in the Transmission footer, this functionality is actually a menu and not a single function button.

In modern MacOS, the ellipsis icon is frequently used to designate a menu that includes more than one functional change.

Ironically, in Xcode, this is the default icon for this functionality and was there prior to this PR.

SCR-20220518-r8k

ellipsis-circle

### CODE REVIEW

**Comment by GaryElshaw** [comment]
@Coeur Review please.

**Comment by sweetppro** [comment]
this looks like it changes the gear icon in Preferences, and in the torrent inspector...
Both of which are standard in macOS for the ***General*** tab

**Comment by GaryElshaw** [comment]
> this looks like it changes the gear icon in Preferences, and in the torrent inspector... Both of which are standard in macOS for the _**General**_ tab

@sweetppro Oh, i see!

**Comment by GaryElshaw** [comment]
#3113 necessitated a lot more work that i thought. This is ready for review/merge @Coeur @ckerr

**Comment by GaryElshaw** [comment]
Here's how it looks in practice with the new lock icon.

SCR-20220529-nve

**Comment by ckerr** [comment]
> #3113 necessitated a lot more work that i thought. This is ready for review/merge @Coeur @ckerr

I'm very hesitant to do review for macOS GUI changes. I'd be much happier if @Coeur or @sweetppro or @DevilDimon said yea or nay

**Comment by GaryElshaw** [comment]
:-(

**Comment by sweetppro** [comment]
personally I prefer the look of the gear icon...
but personal preferences aside,  the icon is the wrong size and needs padding added to the icon file to match the other icon sizes. for example https://github.com/transmission/transmission/pull/3113
169312972-d04d8e65-9155-422a-b6b9-70dd5172bfa0
size

**Comment by sweetppro** [comment]
here these are the correct size:
[Elilipsis_icons.zip](https://github.com/transmission/transmission/files/8802331/Elilipsis_icons.zip)

Im not sure which I prefer...
ellipsis
ellipsisFilled
GearShape

**Comment by GaryElshaw** [comment]
> personally I prefer the look of the gear icon... but personal preferences aside, the icon is the wrong size and needs padding added to the icon file to match the other icon sizes. 

I noticed the sizing issue too and was a bit confused. The new template options include images that are 18x18 and 36x36. In the past these have all been 16x16 and 32x32. I tried 18x18 and it looked too large so reverted back to 16x16.

Let's try that again w/ some more padding.

**Comment by GaryElshaw** [comment]
> here these are the correct size: [Elilipsis_icons.zip](https://github.com/transmission/transmission/files/8802331/Elilipsis_icons.zip)

> Im not sure which I prefer...

I personally prefer the fill version. I'm not coming from a perspective of preference per se, more about the function. It's a menu item with a subset of functions and not a button. Does that make sense?

**Comment by sweetppro** [comment]
It also needs to look aesthetically pleasing

**Comment by GaryElshaw** [comment]
> It also needs to look aesthetically pleasing

Sure thing, it looks fine when the recycling symbol is there, i think, it's the flatness of the tortoise that makes it look weird.

**Pull request closed without merging**
