### PR TITLE
Bundle the macOS 11/12 icons for use in macOS 10 builds

### PR DESCRIPTION
**Pull request by GaryElshaw**
With macOS 10.x still in the mix, we can unify the gui across 10 - 11.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Does anyone know what test is running in the background that isn't visible for review on the dashboard? I'm guessing it's TC?

**Comment by ckerr** [comment]
@GaryElshaw when you're iterating on the code, please try to make local commits and then push the batch up to GitHub when you're reasonably happy with the changes.

According to https://github.com/transmission/transmission/pull/3347/commits you pushed up to GitHub five times between 5:54 and 5:58, which triggers off fresh CI for every push, which makes CI slow for both you and everyone else. If you made those five commits locally and _then_ pushed, it would all be in a single CI run.

Thank you!

**Comment by GaryElshaw** [comment]
That was human error, i apologise.

**Comment by GaryElshaw** [comment]
I'm a little shocked no one has commented. Is there any will for the Mac client to look consistent between macOS 10.x and 11/12? @sweetppro @Coeur @nevack @DevilDimon.

**Comment by sweetppro** [comment]
I don't really support macOS 10 in any of my own apps, and rarely do I get support requests for older operating systems. Personally I don't feel its worth the effort.

**Comment by GaryElshaw** [comment]
The idea is that the macOS gui client _looks_ the same, irregardless of whether the user is on macOS 10, 11, or 12. If under-the-hood is equivalent, why shouldn't the gui interface be the same across OS versions?

**Review by fxcoudert — APPROVED** [review]

**Comment by fxcoudert** [comment]
I don't see any issue with the PR

**Comment by nevack** [comment]
AFAIK, images must be named as corresponding exported SF Symbols.
Then it will be easy to reference them from XIB.

**Comment by ckerr** [comment]
> The idea is that the macOS gui client looks the same, irregardless of whether the user is on macOS 10, 11, or 12. If under-the-hood is equivalent, why shouldn't the gui interface be the same across OS versions?

When it's running on macOS 10, shouldn't it look like a macOS 10 app?

**Comment by GaryElshaw** [comment]
It currently has a number of macOS 11 SF Symbols elements already, this just implements the remaining ones.

**Comment by fxcoudert** [comment]
I think it's better to have a coherent icon set. Also, there is nothing inherently “macOS 10 native” about the previous images, really.

**Review by Coeur — APPROVED** [review]

**Comment by GaryElshaw** [comment]
@ckerr I don't know if i have redeemed myself, but could i please have my collaborator privileges back? Worth mentioning, i am perfectly capable of apologies.

**Comment by GaryElshaw** [comment]
Also, please drop me a line. What happened with access to the change-log notes?

**Comment by GaryElshaw** [comment]
@fxcoudert @Coeur Please let me know if there are any errors or anomalies here, i'm happy to fix. The PR is a like for like image duplication, but we all know the reality can be different when built. Cheers gentlemen.

**Comment by GaryElshaw** [comment]
OpenBSD/amd64 failure is unrelated.

`[02:03:23]                            ^
[02:03:23]1 warning generated.
[02:04:00]/home/user/buildAgent/work/1f3bff43dd55cfe9/libtransmission/session.cc:71:34: warning: declaration requires an exit-time destructor [-Wexit-time-destructors]
[02:04:00]std::recursive_mutex tr_session::session_mutex_;
[02:04:00]                                 ^
[02:04:00]1 warning generated.
[02:04:01]/home/user/buildAgent/work/1f3bff43dd55cfe9/libtransmission/verify.cc:204:19: warning: declaration requires an exit-time destructor [-Wexit-time-destructors]
[02:04:01]static std::mutex verify_mutex_;
[02:04:01]                  ^
[02:04:01]1 warning generated.
[02:04:03]ld: error: undefined symbol: std::__1::optional<unsigned long> tr_parseNum<unsigned long, true>(std::__1::basic_string_view<char, std::__1::char_traits<char> >&, int)
[02:04:03]>>> referenced by variant-benc.cc:109 (/home/user/buildAgent/work/1f3bff43dd55cfe9/libtransmission/variant-benc.cc:109)
[02:04:03]>>>               variant-benc.cc.o:(transmission::benc::impl::ParseString(std::__1::basic_string_view<char, std::__1::char_traits<char> >*)) in archive ../../libtransmission/libtransmission.a
[02:04:03]>>> did you mean: std::__1::optional<signed char> tr_parseNum<signed char, true>(std::__1::basic_string_view<char, std::__1::char_traits<char> >&, int)
[02:04:03]>>> defined in: ../../libtransmission/libtransmission.a(utils.cc.o)
[02:04:03]c++: error: linker command failed with exit code 1 (use -v to see invocation)
[02:04:03]*** Error 1 in . (tests/libtransmission/CMakeFiles/subprocess-test.dir/build.make:114 'tests/libtransmission/subprocess-test')
[02:04:03]*** Error 2 in . (CMakeFiles/Makefile2:1209 'tests/libtransmission/CMakeFiles/subprocess-test.dir/all')
[02:04:03]*** Error 2 in /home/user/buildAgent/work/1f3bff43dd55cfe9/_build (Makefile:166 'all')
[02:04:03]Process exited with code 2`

**Comment by ckerr** [comment]
> @ckerr I don't know if i have redeemed myself, but could i please have my collaborator privileges back? Worth mentioning, i am perfectly capable of apologies.

You've already been sent an invitation

> Also, please drop me a line. What happened with access to the change-log notes?

I took away your access to the hackmd for that week that you were banned, and the hackmd is out-of-date now. The draft is in `main` now, so updates should be done through PR :+1:

**Comment by ckerr** [comment]
> Merge branch 'main' into macos10-11

> Merge branch 'main' into macos10-11

[Pushing new commits like this is like saying "bump" again & again in a discussion thread, with the added bonus of each "bump" adds another hour of work to Sanity CI.](https://github.com/transmission/transmission/pull/3348#issuecomment-1168086207). @GaryElshaw please use more restraint on this.

**Comment by GaryElshaw** [comment]
I understand, but a 'clean bill of health' means something to me. I need to know it's not me F-ing up.

**Comment by ckerr** [comment]
Has anyone actually tested this PR on 10?

**Review by ckerr — DISMISSED** [review]
Marking as "Request changes" pending the answer to the above question

> Has anyone actually tested this PR on 10?

**Comment by GaryElshaw** [comment]
> > Has anyone actually tested this PR on 10?
> 
> I did. Let me send screenshots.

Sort of off-topic, but i watched this video from Apple's developer conference today and there is some very good virtualisation coming to Ventura. I'll look forward to being able to test Gnome, macOS, and anything else by the look of it. https://developer.apple.com/videos/play/wwdc2022/10002/

**Comment by nevack** [comment]
> > > Has anyone actually tested this PR on 10?
> > 
> > 
> > I did. Let me send screenshots.
> 
> Sort of off-topic, but i watched this video from Apple's developer conference today and there is some very good virtualisation coming to Ventura. I'll look forward to being able to test Gnome, macOS, and anything else by the look of it. https://developer.apple.com/videos/play/wwdc2022/10002/

There's no VM solution provided by Apple itself.
It's more like building blocks for VM developers.

There's already decent and free VM solution like VMware Fusion and Virtual Box.

**Comment by Coeur** [comment]
Capture d’écran 2022-07-05 à 18 16 58
@ckerr

**Comment by nevack** [comment]
> Capture d’écran 2022-07-05 à 18 16 58
> 
> @ckerr 

Looks pretty bad, IMO.
Let's use previous icons for 10.x, I can fix this in a separate PR.

**Comment by GaryElshaw** [comment]
They need the heavier weight in SF Symbols to match the top menu, and maybe more black than grey.

I still think it's better.

**Comment by GaryElshaw** [comment]
You've been clear and i've been clear what we think.

**Comment by sweetppro** [comment]
I think resources would be better utilised in moving forward. Rather than wasting programming hours on fixing the UI for a handful of users on deprecated hardware

**Comment by ckerr** [comment]
So, applying those new rules to this PR:

- If anyone has *actionable* change requests they should provide a review. E.g. @nevack "looks pretty bad" is not gonna cut it since it's not actionable, but refining that into specific change requests would IMO be productive. You can do that by clicking "add your review". :slightly_smiling_face: 

- I have no opinion on the UI since I don't know what a macOS 10 app *should* look like -- but this PR has two approvals, so if nobody's going to request changes I'm fine with merging this PR. :green_circle: 

- If @nevack or anyone else requests changes and @GaryElshaw makes changes to the PR to address the requests, Gary *must* test them out before pushing *and* include screenshots here on this PR page. If you're not willing or able to do that then you shouldn't be championing this PR.

**Comment by sweetppro** [comment]
> ## The PR champion(s) should put in 90+% percent of the work.
> IMO this is the core problem. The PR has a champion who believes in it, but the group collectively has to do testing and other work.

💯 agree with this statement. Everyone can decide where they want to spend there own resources, but expecting others to reallocate to address shortcomings is detrimental to the project.

**Comment by fxcoudert** [comment]
Thanks @ckerr for providing clear guidelines and explaining their rationale. This is good project (and team) leadership. ❤️ 

I'm recanting my previous ✅ and adding an actionnable review, based on the UI screenshot provided by @Coeur in https://github.com/transmission/transmission/pull/3347#issuecomment-1174892583

**Comment by GaryElshaw** [comment]
> Point of comparison _before_ the change:

Yes, i think the .fill option will work better.

**Comment by ckerr** [comment]
Putting them in the same comment to make a side-by-side easier:

Capture d’écran 2022-07-06 à 09 58 06

Capture d’écran 2022-07-05 à 18 16 58

**Comment by beren12** [comment]
> I don't really support macOS 10 in any of my own apps, and rarely do I get support requests for older operating systems. Personally I don't feel its worth the effort.

Just because you don't use an older OS doesn't mean that nobody else does. All the restrictions and feature removals in the newer os x has turned many people off of upgrading when it can be avoided.

And *please* keep an option for color icons. They are a giant bonus to usability. Humans see in color, if everything is greyscale the icons blur together. I use SIMBL to bring back colored Finder sidebar icons, and I can tell what every one is at the briefest glace without reading the label. Also, it would be great to bring back the option to use the old icon as well. Many apps have the ability to pick the icon, the new one looks more like a bloated barrel than any transmission shifter. (sorry)

**Comment by fxcoudert** [comment]
> The PR champions must provide firsthand screenshots of UI changes.

@GaryElshaw in order to review that change, can you provide screenshots of the new UI? I want to check that there is no “blue-on-blue” issue on the selected tabs.

**Comment by GaryElshaw** [comment]
> > The PR champions must provide firsthand screenshots of UI changes.
I want to check that there is no “blue-on-blue” issue on the selected tabs.

Working on it ;-)

**Comment by GaryElshaw** [comment]
Interestingly, although the scale of the images these are proposed to replace is like for like, their rendering is different. I'll take a look so things look _a lot_ more even.

SCR-20220718-s0u

**Comment by Oleg-Chashko** [comment]
I apologize off-topic, in advance for not being able to get past it. Don't touch the old icons.

“blue-on-blue”

https://user-images.githubusercontent.com/62497891/179519086-3a6e72e6-c0c2-440e-b6b0-3cc8d4cfc806.mp4

**Comment by GaryElshaw** [comment]
> “blue-on-blue”

The current icons feature "blue on blue", it's why i remade them this way, as a compromise for those who prefer the colour of the old, but move the icons to parity with 11 - 12.

**Pull request closed without merging**
