### PR TITLE
build: install rebuilt web if available

### PR DESCRIPTION
**Pull request by t-8ch**

### CODE REVIEW

**Comment by ckerr** [comment]
Hey @t-8ch I think I'm misunderstanding this PR. What problem does this solve?

Not asking in a negative way -- I'm not for or against this PR; I just don't understand it yet.

**Comment by t-8ch** [comment]
Currently the web bundle is always installed from the source directory.
In out-of-source builds however a rebuild web bundle will not be generated in the source directory but the build directory.

With this patch the newly generated bundle will be installed instead of the old one from the git checkout.

**Comment by ckerr** [comment]
Yeah, that makes sense. :+1: 

Also reported in the last two hours and very closely related to this PR: #4864.

So much so that IMO if you're interested it makes a lot of sense to fix 4864 in this patch.

**Comment by ckerr** [comment]
No worries! Thanks for the PR :+1:

**Review by ckerr — APPROVED** [review]

**Pull request merged**
