### PR TITLE
Updating group icon style for newer macOS

### PR DESCRIPTION
**Pull request by Coeur**
Addresses the essential of #3058 for macOS 12:
- adopts the round shape used by Finder;
- adopts the flatness used by Finder;
- adopts system colors used by Finder;

Note:
- doesn't change anything else, like the group visual style.

Capture d’écran 2022-05-08 à 16 46 00

### CODE REVIEW

**Comment by GaryElshaw** [comment]
That looks great! Is there a round icon for 'None' there, Antoine? I was thinking of the 'Home' one.
empty

**Comment by Coeur** [comment]
For 'None', it's a pair of .png files:
https://github.com/transmission/transmission/tree/main/macosx/Images/Images.xcassets/GroupsNoneTemplate.imageset

I'll leave the asset update to someone else.

**Comment by GaryElshaw** [comment]
> For 'None', it's a pair of .png files

Thanks @Coeur, on to it.

**Review by DevilDimon — APPROVED** [review]

**Comment by GaryElshaw** [comment]
@ckerr Welcome back Charles. This commit also relies on mine for the 'Empty' icon #3067

**Pull request merged**
