### PR TITLE
Add function of skip verify local data

### PR DESCRIPTION
**Pull request by yangzhaofeng**
For cli and rpc.
It can be used by `transmission-remote --skip-verify`

### CODE REVIEW

**Comment by yangzhaofeng** [comment]
Why I created this pull request:

I have many private tracker accounts. When I or others transfer a torrent from one of them to another and reseed the torrents with only some info and trackers changed, I have to verify the files again and again. It consumes a lot of time in which I can not download other torrents when verifying large ones. There are a lot of users using transmission in these private trackers. We would be glad if you pass this pull request.

What I changed:

I add a bool to decide whether to skip the verification. If it is set to true, the functions that really verify the files will not run and it is considered that you own the files.

**Comment by cfpp2p** [comment]
I don't see where it is checked if any of the file(s) exist to begin with.
In my fork I have a well tested and 5 years proven method based on
setting only existing files verified. This prevents a lot of common user errors.
Your implementation will easily result in bad data being sent to peers.
Additionally there needs to be strong warnings when a torrent's files
are being verify skipped. I see danger all over the place in how you
are implementing.

**Comment by yangzhaofeng** [comment]
> I don't see where it is checked if any of the file(s) exist to begin with.
> In my fork I have a well tested and 5 years proven method based on
> setting only existing files verified. This prevents a lot of common user errors.
> Your implementation will easily result in bad data being sent to peers.
> Additionally there needs to be strong warnings when a torrent's files
> are being verify skipped. I see danger all over the place in how you
> are implementing.

It will automatically exit with cli, or pause with daemon if some files do not exist (or be corrupt) when sending data to peers. The error in daemon is "Please verify local data! piece #NUMBER is corrupt!"

Anyway, this function is for users who are **SURE** that they have all the files. Skipping local verify of non-existing files or corrupt files will lead to errors, as is expected.

**Comment by cfpp2p** [comment]
I do not agree with allowing the user to set completely non-existent file(s)
to 100% verified and 100% completed. Then starting the torrent and waiting
for seeding torrent at peer-msgs.c `fillOutputBuffer()`to call
`tr_torrentCheckPiece()` and failing. Only then to notify the user
of an error and subsequently pausing this erroneously seeding torrent.

This would be very confusing to any user as the error in  no way to tells whether it is actually is a particular piece is corrupt or that a non-existent file was by mistake skip-verified.

**Comment by cfpp2p** [comment]
I do not agree with allowing the user to set completely non-existent file(s)
to 100% verified and 100% completed. Then starting the torrent and waiting
for seeding torrent at peer-msgs.c `fillOutputBuffer()`to call
`tr_torrentCheckPiece()` and failing. Only then to notify the user
of an error and subsequently pausing this erroneously seeding torrent.

Besides the unusual way to halt as described above this would be very confusing to any user. No way to tell if in actuality a corrupt piece or the error of skip-verify  non-existent.
This would be very confusing to any user as there is no way to tell

**Comment by cfpp2p** [comment]
I do not agree with allowing the user to set completely non-existent file(s)
to 100% verified and 100% completed. Then starting the torrent and waiting
for seeding torrent at peer-msgs.c `fillOutputBuffer()`to call
`tr_torrentCheckPiece()` and failing. Only then to notify the user
of an error and subsequently pausing this erroneously seeding torrent.

Besides the unusual way to halt as described above this would be
very confusing to any user. From the error message no way to tell
if in actuality a corrupt piece or the error of skip-verify non-existent.

**Comment by yangzhaofeng** [comment]
@cfpp2p You are right. I added `fd != TR_BAD_SYS_FILE` to `hasPiece` in order to make sure the file(name) exists. But sometimes the "traversal" of files can be as slow as it used to be, especially working with sshfs.

**Comment by cfpp2p** [comment]
@yangzhaofeng 
My fork at https://github.com/cfpp2p/transmission functions perfectly,
none of the problems you are describing. Use it and you will see.
I am not about to reinvent the wheel. I have no single patch for
skip-verify and there have been many improvements since I first
patched for skip-verify years ago. Here is the original and now
vastly outdated patch I began with back in 2012,
and I believe from @ijuxda .

```patch
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/completion.c.org	Mon Jan 30 15:44:55 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/completion.c	Wed Jan 25 23:04:30 2012
@@ -21,7 +21,7 @@
 ****
 ***/
 
-static void
+void
 tr_cpReset( tr_completion * cp )
 {
     cp->sizeNow = 0;
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/completion.h.org	Mon Jan 30 15:44:55 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/completion.h	Wed Jan 25 23:27:47 2012
@@ -135,6 +135,8 @@
     return tr_bitfieldHas( &cp->blockBitfield, i );
 }
 
+void      tr_cpReset( tr_completion * completion );
+
 /***
 ****  Misc
 ***/
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/daemon/remote.c.org	Mon Jan 30 15:46:06 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/daemon/remote.c	Thu Jan 26 10:27:04 2012
@@ -7,7 +7,7 @@
  *
  * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
  *
- * $Id: remote.c 13182 2012-01-26 12:56:28Z jordan $
+ * $Id: remote.c 13104 2011-12-10 18:34:36Z jordan $
  */
 
 #include <assert.h>
@@ -302,6 +302,7 @@
     { 830, "utp",                    "Enable uTP for peer connections", NULL, 0, NULL },
     { 831, "no-utp",                 "Disable uTP for peer connections", NULL, 0, NULL },
     { 'v', "verify",                 "Verify the current torrent(s)", "v",  0, NULL },
+    { 964, "set-verified",           "Assume files in current torrent(s) are verified", "sv", 0, NULL },
     { 'V', "version",                "Show version number and exit", "V", 0, NULL },
     { 'w', "download-dir",           "When adding a new torrent, set its download folder. Otherwise, set the default download folder", "w",  1, "<path>" },
     { 'x', "pex",                    "Enable peer exchange (PEX)", "x",  0, NULL },
@@ -467,6 +468,9 @@
         case 'v': /* verify */
             return MODE_TORRENT_VERIFY;
 
+        case 964: /* set-verified */
+            return MODE_TORRENT_VERIFY;
+
         case 600: /* reannounce */
             return MODE_TORRENT_REANNOUNCE;
 
@@ -2293,6 +2297,21 @@
                 status |= flush( rpcurl, &top );
                 break;
             }
+            case 964:
+            {
+                tr_benc * top;
+                if( tset != 0 )
+                {
+                    addIdArg( tr_bencDictFind( tset, ARGUMENTS ), id );
+                    status |= flush( rpcurl, &tset );
+                }
+                top = tr_new0( tr_benc, 1 );
+                tr_bencInitDict( top, 2 );
+                tr_bencDictAddStr( top, "method", "torrent-set-verified" );
+                addIdArg( tr_bencDictAddDict( top, ARGUMENTS, 1 ), id );
+                status |= flush( rpcurl, &top );
+                break;
+            }
             case 'r':
             case 'R':
             {
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/rpcimpl.c.org	Tue Jan 10 22:17:40 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/rpcimpl.c	Thu Jan 26 00:31:39 2012
@@ -401,6 +401,28 @@
     return NULL;
 }
 
+static const char*
+torrentSetVerified( tr_session               * session,
+                    tr_benc                  * args_in,
+                    tr_benc                  * args_out UNUSED,
+                    struct tr_rpc_idle_data  * idle_data UNUSED )
+{
+    int i, torrentCount;
+    tr_torrent ** torrents = getTorrents( session, args_in, &torrentCount );
+
+    assert( idle_data == NULL );
+
+    for( i = 0; i < torrentCount; ++i )
+    {
+        tr_torrent * tor = torrents[i];
+        tr_torrentSetFilesVerified( tor );
+        notify( session, TR_RPC_TORRENT_CHANGED, tor );
+    }
+
+    tr_free( torrents );
+    return NULL;
+}
+
 /***
 ****
 ***/
@@ -1797,6 +1819,7 @@
     { "torrent-start-now",     true,  torrentStartNow     },
     { "torrent-stop",          true,  torrentStop         },
     { "torrent-verify",        true,  torrentVerify       },
+    { "torrent-set-verified",  true,  torrentSetVerified  },
     { "torrent-reannounce",    true,  torrentReannounce   },
     { "queue-move-top",        true,  queueMoveTop        },
     { "queue-move-up",         true,  queueMoveUp         },
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/extras/rpc-spec.txt.org	Mon Jan 30 15:46:12 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/extras/rpc-spec.txt	Wed Jan 25 22:26:15 2012
@@ -62,13 +62,14 @@
 
 3.1.  Torrent Action Requests
 
-   Method name          | libtransmission function
-   ---------------------+-------------------------------------------------
-   "torrent-start"      | tr_torrentStart
-   "torrent-start-now"  | tr_torrentStartNow
-   "torrent-stop"       | tr_torrentStop
-   "torrent-verify"     | tr_torrentVerify
-   "torrent-reannounce" | tr_torrentManualUpdate ("ask tracker for more peers")
+   Method name            | libtransmission function
+   -----------------------+-------------------------------------------------
+   "torrent-start"        | tr_torrentStart
+   "torrent-start-now"    | tr_torrentStartNow
+   "torrent-stop"         | tr_torrentStop
+   "torrent-verify"       | tr_torrentVerify
+   "torrent-set-verified" | tr_torrentSetFilesVerified
+   "torrent-reannounce"   | tr_torrentManualUpdate ("ask tracker for more peers")
 
    Request arguments: "ids", which specifies which torrents to use.
                   All torrents are used if the "ids" argument is omitted.
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/torrent.c.org	Tue Jan 10 22:32:14 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/torrent.c	Thu Jan 26 03:17:10 2012
@@ -802,6 +802,22 @@
     return disappeared;
 }
 
+static bool fileExists( const char * filename, time_t * optional_mtime );
+
+static bool
+torrentDataExists( const tr_torrent * tor )
+{
+    char * path;
+    bool exists;
+    if( !tr_torrentHasMetadata( tor ) )
+        return false;
+    path = tr_buildPath( tr_torrentGetCurrentDir( tor ),
+                         tr_torrentName( tor ), NULL );
+    exists = fileExists( path, NULL );
+    tr_free( path );
+    return exists;
+}
+
 static void
 torrentInit( tr_torrent * tor, const tr_ctor * ctor )
 {
@@ -1739,6 +1755,17 @@
     tr_runInEventThread( tor->session, torrentRecheckDoneImpl, tor );
 }
 
+static bool
+quickVerify( tr_torrent * tor )
+{
+    if( torrentDataExists( tor ) )
+        return false;
+    tr_cpReset( &tor->completion );
+    tor->anyDate = tr_time( );
+    tr_torrentSetDirty( tor );
+    return true;
+}
+
 static void
 verifyTorrent( void * vtor )
 {
@@ -1760,7 +1787,12 @@
     if( setLocalErrorIfFilesDisappeared( tor ) )
         tor->startAfterVerify = false;
     else
-        tr_verifyAdd( tor, torrentRecheckDoneCB );
+    {
+        if( quickVerify( tor ) )
+            torrentRecheckDoneCB( tor );
+        else
+            tr_verifyAdd( tor, torrentRecheckDoneCB );
+    }
 
     tr_sessionUnlock( tor->session );
 }
@@ -1772,7 +1804,66 @@
         tr_runInEventThread( tor->session, verifyTorrent, tor );
 }
 
+static void
+setExistingFilesVerified( tr_torrent * tor )
+{
+    tr_file_index_t fi;
+    tr_piece_index_t pi;
+    const tr_info * info = tr_torrentInfo( tor );
+    bool * missing = tr_new0( bool, info->pieceCount );
+
+    for( fi = 0; fi < info->fileCount; ++fi  )
+    {
+        const tr_file * file = &info->files[fi];
+        const bool have = !file->dnd
+            && tr_torrentFindFile2( tor, fi, NULL, NULL, NULL );
+
+        for( pi = file->firstPiece; pi <= file->lastPiece; ++pi )
+            if( !missing[pi] && !have )
+                missing[pi] = true;
+    }
+
+    for( pi = 0; pi < info->pieceCount; ++pi )
+    {
+        tr_torrentSetHasPiece( tor, pi, !missing[pi] );
+        tr_torrentSetPieceChecked( tor, pi );
+    }
+    tr_free( missing );
+}
+
+static void
+setTorrentFilesVerified( void * vtor )
+{
+    tr_torrent * tor = vtor;
+    bool startAfter = false;
+
+    assert( tr_isTorrent( tor ) );
+    tr_sessionLock( tor->session );
+
+    tr_verifyRemove( tor );
+    if( tor->startAfterVerify || tor->isRunning ) {
+        startAfter = !tor->isStopping;
+        tr_torrentStop( tor );
+    }
+
+    setExistingFilesVerified( tor );
+    tor->anyDate = tr_time( );
+    tr_torrentRecheckCompleteness( tor );
+
+    if( startAfter )
+        torrentStart( tor, true );
+
+    tr_sessionUnlock( tor->session );
+}
+
 void
+tr_torrentSetFilesVerified( tr_torrent * tor )
+{
+    if( tr_isTorrent( tor ) )
+        tr_runInEventThread( tor->session, setTorrentFilesVerified, tor );
+}
+
+void
 tr_torrentSave( tr_torrent * tor )
 {
     assert( tr_isTorrent( tor ) );
--- J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/transmission.h.org	Tue Jan 10 22:59:14 2012
+++ J:/!!/skp-v-diff/skp-v-svn/Transmission/libtransmission/transmission.h	Wed Jan 25 22:55:54 2012
@@ -1759,6 +1759,26 @@
 
 void tr_torrentVerify( tr_torrent * torrent );
 
+/**
+ * This function will mark all data in files in the torrent as "verified",
+ * if the files themselves already exist and are wanted (i.e. file->dnd
+ * is FALSE).
+ *
+ * If the torrent is currently being verified, the verification is
+ * cancelled. If the torrent is running, it is stopped and restarted
+ * afterwards as part of this function.
+ *
+ * @note Since the piece data itself is not checked against the checksums
+ *       in the torrent, using this function with partially complete files
+ *       will result in bad data being sent to peers. This is not what
+ *       you want. Take extra care when using this function, or just use
+ *       tr_torrentVerify().
+ *
+ * @see tr_torrentVerify()
+ * @see tr_torrentSetFileDLs()
+ */
+void tr_torrentSetFilesVerified( tr_torrent * tor );
+
 /***********************************************************************
  * tr_info
  **********************************************************************/
```

**Comment by yangzhaofeng** [comment]
@cfpp2p I tested your code from your repo at latest commit. Your transmission daemon would also set non-existent files as 100% verified when sending `-sv` by `transmission-remote`. What's more, your transmission daemon would set an empty file(with only a filename) as fully verified in "normal" mode when no skip signal was sent to that torrent.

I do not know whether it is because of my testing environment or your code. I was testing on Debian buster with kernel `4.18.20-2 (2018-11-23) x86_64`. To successfully compile, I substituted `m4/glib-gettext.m4` with the latest version and added exec permission to `autogen.sh`, `update-version-h.sh` and `third-party/*/*.sh`. If the program was compiled correctly, it seems that your code of checking whether the file exists when skip verifying local data do not work.

**Comment by cfpp2p** [comment]
> I tested your code from your repo at latest commit. Your transmission daemon would also set non-existent files as 100% verified when sending -sv by transmission-remote. What's more, your transmission daemon would set an empty file(with only a filename) as fully verified in "normal" mode when no skip signal was sent to that torrent.

>I do not know whether it is because of my testing environment or your code. I was testing on Debian buster with kernel 4.18.20-2 (2018-11-23) x86_64. To successfully compile, I substituted m4/glib-gettext.m4 with the latest version and added exec permission to autogen.sh, update-version-h.sh and third-party/*/*.sh. If the program was compiled correctly, it seems that your code of checking whether the file exists when skip verifying local data do not work.

**NOPE---** there is no bug as you describe. You just do not understand
the intricacies of a proper implementation of skip-verify.

If there is a bug in my fork it is not appropriate to discuss that here,
so please report it there.

**EMPTY** zero byte files are **NOT** non-existent files.
If you previously started download and some files were deselected then
as you describe set them from **D**o**N**ot**D**ownload to **"normal"** priority mode
the partial files in the temporary piece directory are used.
If the now selected files are are smaller than piece size
they are correctly 100% verified as the DND file(s) are now transfered from the
piece temp directory as they should.


# transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  #  Done Priority Get      Size  Name
  0:   0% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1:   0% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2:   0% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3:   0% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4:   0% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5:   0% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4
# transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -sv
xxx.168.1.77:9091/transmission/rpc/ responded: "success"
# transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  #  Done Priority Get      Size  Name
  0:   0% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1:   0% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2:   0% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3:   0% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4:   0% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5:   0% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4

//As below:
//I now create empty **ZERO** byte files in the directory
//Or the same results if select ONLY `why are we[A].mp4`, download some, then
//toggle **D**o**N**ot**D**ownload to **"normal"** priority mode all the files.

# transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -sv
xxx.168.1.77:9091/transmission/rpc/ responded: "success"
# transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  #  Done Priority Get      Size  Name
  0: 100% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1: 100% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2: 100% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3: 100% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4: 100% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5: 100% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4
#

**Comment by cfpp2p** [comment]
> I tested your code from your repo at latest commit. Your transmission daemon would also set non-existent files as 100% verified when sending -sv by transmission-remote. What's more, your transmission daemon would set an empty file(with only a filename) as fully verified in "normal" mode when no skip signal was sent to that torrent.

>I do not know whether it is because of my testing environment or your code. I was testing on Debian buster with kernel 4.18.20-2 (2018-11-23) x86_64. To successfully compile, I substituted m4/glib-gettext.m4 with the latest version and added exec permission to autogen.sh, update-version-h.sh and third-party/*/*.sh. If the program was compiled correctly, it seems that your code of checking whether the file exists when skip verifying local data do not work.

**NOPE---** there is no bug as you describe. You just do not understand
the intricacies of a proper implementation of skip-verify.

First of all if there is a bug in my fork it is not appropriate to discuss that here,
so please report it there.

**EMPTY** zero byte files are **NOT** non-existent files.
If you previously started download and some files were deselected then
as you describe set them from **D**o**N**ot**D**ownload to **"normal"** priority mode
the partial files in the temporary piece directory are used.
If the now selected files are are smaller than piece size
they are correctly 100% verified as the DND file(s) are now transfered from the
piece temp directory as they should.


cfp~ transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  cfp~  Done Priority Get      Size  Name
  0:   0% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1:   0% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2:   0% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3:   0% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4:   0% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5:   0% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4
cfp~ transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -sv
xxx.168.1.77:9091/transmission/rpc/ responded: "success"
cfp~ transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  cfp~  Done Priority Get      Size  Name
  0:   0% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1:   0% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2:   0% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3:   0% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4:   0% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5:   0% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4

//As below:
//I now create empty **ZERO** byte files in the directory
//Or the same results if select ONLY `why are we[A].mp4`, download some, then
//toggle **D**o**N**ot**D**ownload to **"normal"** priority mode all the files.

cfp~ transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -sv
xxx.168.1.77:9091/transmission/rpc/ responded: "success"
cfp~ transmission-remote xxx.168.1.77:9091 -n user:pass --torrent 26 -if
Why are we [A] (6 files):
  cfp~  Done Priority Get      Size  Name
  0: 100% Normal   Yes  0.17 KiB  Why are we [A]/info.txt
  1: 100% Normal   Yes  0.23 KiB  Why are we [A]/how-to.txt
  2: 100% Normal   Yes  0.10 KiB  Why are we [A]/why.txt
  3: 100% Normal   Yes  0.47 KiB  Why are we [A]/A Read Me!.txt
  4: 100% Normal   Yes 137.3 KiB  Why are we [A]/A.png
  5: 100% Normal   Yes 212.5 MiB  Why are we [A]/why are we[A].mp4
cfp~

**Comment by cfpp2p** [comment]
@yangzhaofeng 
For reference pertaining to (Collect unwanted, but received, blocks in a separate file)[https://trac.transmissionbt.com/ticket/532] and skip-verify.

https://github.com/transmission/transmission/issues/290
https://github.com/transmission/transmission/issues/382
https://github.com/transmission/transmission/issues/400
https://github.com/transmission/transmission/commits/trac532-collect-unwanted-blocks
https://forum.transmissionbt.com/viewtopic.php?f=2&t=13363#p74519

Note that also that web client --> https://github.com/transmission/transmission/tree/master/web does not
allow initially unchecked for download now 100% to be toggled to download.

**Comment by cfpp2p** [comment]
@yangzhaofeng 
For reference pertaining to [Collect unwanted, but received, blocks in a separate file](https://trac.transmissionbt.com/ticket/532) and skip-verify.

https://github.com/transmission/transmission/issues/290
https://github.com/transmission/transmission/issues/382
https://github.com/transmission/transmission/issues/400
https://github.com/transmission/transmission/commits/trac532-collect-unwanted-blocks
https://forum.transmissionbt.com/viewtopic.php?f=2&t=13363#p74519

Note that also that web client --> https://github.com/transmission/transmission/tree/master/web does not
allow initially unchecked for download now 100% to be toggled to download.

**Comment by yangzhaofeng** [comment]
@cfpp2p Thank you very much! I tested my code hours ago and found that even my original commit can not be called "skip verify" and can only be called "quick verify". For large torrents (100+GB and almost 30000 pieces), the counting of `pieceIndex` also consumes considerable resources and time, even consumes much less than really verifying, though. I will rewrite the function of skipping verification.

**Comment by yangzhaofeng** [comment]
@ckerr Most bittorrent clients will deny the data received from peers sending corrupt ones. What's more, users will receive errors from transmission when sending data of a mismatching piece if they have skipped verifying local data.

**Comment by ckerr** [comment]
> @ckerr users will receive errors from transmission when sending data of a mismatching piece if they have skipped verifying local data.

This sounds like you're making my argument for me, so I think I might be misunderstanding your point.

I agree that if users skip the verification step, that increases their chances of seeding incorrect data

**Comment by ckerr** [comment]
> In fact, compared with duplicate data transferring in Bittorrent network, incorrect data transferring that this function may introduce would only cause much less performance loss.

How does verifying local data contribute to performance loss or to redundant data being transferred?

**Comment by yangzhaofeng** [comment]
@ckerr This is not caused by verifying local data. This is a characteristic of p2p networks. I mean that the performance loss caused by skipping verifying local data (thus sending one corrupt piece at most) is much inferior to the performance loss caused by the Bittorrent network itself, which is extremely difficult to be avoided.

**Comment by LaserEyess** [comment]
@ckerr I'd like to make an argument for this. There are two use cases where this would be extremely useful, and not at all a legitimate risk of sending bad data. 

1. For loading a torrent into transmission after creating it with some utility like transmission-create
2. For cross-seeding **known** equivalent torrents between trackers

The first case is rather obvious, you just created that torrent, and now you're putting it into transmission. The odds of a bitflip in that next 30 seconds you take to add it to transmission should be nil. There should be no need to hash the data again, it's just wasting CPU/Disk I/O. 

The second case is a bit niche, but I believe it is legitimate. On private trackers, where you cannot add new trackers to a torrent, there are sometimes overlaps in the data that can be shared; so adding the same torrent twice to your client, one for each tracker, is a way to share the data with multiple trackers. 
Sometimes piece sizes are different, and it would probably be best to ensure you rehash in that case, but other times trackers use the source field of the infodict to create a unique hash so that two identical torrents can be added to clients. If you **know** the piece hashes are the same, what is the point of rehashing the data? 

I think it should come with some kind of warning that the option risks data corruption, and should absolutely  never be the default, but personally I have legitimate use-cases for doing this and I think a lot of other people do, too.

**Comment by swannie-eire** [comment]
+1 for this.

I have the same use cases as @LaserEyess 

This feature is in many other bit torrent clients.

Qbittorrent and uTorrent to name a few.

**Comment by escape0707** [comment]
Missing the important feature is a blocking point for me to use Transmission for my daily usage.

I mean, see, I can't even quickly and painlessly start to use Transmission to seed those 2 TB torrents which I've been seeding in other BT clients! Then how to easily try TR out and decide whether to migrate??

**Comment by perazzi** [comment]
> @ckerr I'd like to make an argument for this. There are two use cases where this would be extremely useful, and not at all a legitimate risk of sending bad data.
> 
>     1. For loading a torrent into transmission after creating it with some utility like transmission-create
> 
>     2. For cross-seeding **known** equivalent torrents between trackers


> Missing this important feature is a blocking point for me to use Transmission for my daily usage.

Totally agree.
It takes forever to verify large files that I created using transmission-create, it should be possible to skip verifying.

**Comment by tc60045** [comment]
> Totally agree.
> It takes forever to verify large files that I created using transmission-create, it should be possible to skip verifying.

We incur this 100 times a day in the process of distributing 120+ GB files to paid clients.  Costs us money and makes us think about switching to other clients that have had this for years.

**Comment by batkom** [comment]
Cheers @yangzhaofeng and @cfpp2p.
I just adapted your solution for transmission 3.0 and optimized performance for large files
look https://github.com/batkom/transmission_skip_verify/commit/510167604de8ef4fcb1ac6bbc41949b5f04ff57b
hope it can help you

**Comment by waynon** [comment]
> The potential for abusing this feature, either intentionally or unintentionally, seems to outweigh the benefits.
> 
> Why would you ever want Transmission to be serving unverified data out to peers?

On the one hand, if someone deliberately wants to transmit wrong data, they can use a modified version of Transmission. On the other hand, in order to prevent someone from unintentionally transferring wrong data, a warning dialog can be used. 

Also, this feature already exists in qBittorrent, µTorrent and BitTorrent, and I can't figure out why transmission can't support it. 

If this is still the case in the future, I might consider other BitTorrent clients.

**Comment by ckerr** [comment]
Closing in favor of https://github.com/transmission/transmission/issues/2261.

In particular please read https://github.com/transmission/transmission/issues/2261#issuecomment-1014993084 about what parts of this I would and wouldn't approve.

**Pull request closed without merging**
