### PR TITLE
Removed ToolbarSegmentedCell

### PR DESCRIPTION
**Pull request by Coeur**
Class is unused.

### CODE REVIEW

**Review by sweetppro — APPROVED** [review]
nice catch

**Comment by ckerr** [comment]
Huh, those `Sanity / windows (x64)` and `Sanity / windows (x86)` failures are finding fault in a CMakeLists.txt file that hasn't changed since July and surely don't have anything to do with this PR...? :thinking:

**Comment by Coeur** [comment]
I'm positive that the Windows failures are unrelated to this PR... most of my PR are seeing unrelated CI failures, which is a bummer.
I don't have a Windows or a FreeBSD, nor the time, to look at the CI flakiness unfortunately.
As one said: https://github.com/transmission/transmission/discussions/3709

**Comment by ckerr** [comment]
OK I think I see it.

The build is with `-DENABLE_TESTS=ON  -DENABLE_UTILS=OFF `  except that there are utils-specific tests in `tests/utils/` and so CI is trying to run tests on code that didn't get built. :smile_cat: 

I'll look at this now & if it's an easy fix I'll fast-track it so that I can get CI green again & rebase this PR; otherwise, I'll merge one as-is.

**Pull request merged**
