### PR TITLE
Fix wrong IPv6 address used in announces

### PR DESCRIPTION
**Pull request by malte-v**
Original author: @vuori

This is just https://github.com/transmission/transmission/pull/265 with the merge conflicts fixed. I've tested this locally and it works as expected.

### CODE REVIEW

**Comment by ckerr** [comment]
@malte-v could you update this to fix the merge conflicts?

**Comment by malte-v** [comment]
Nah. I don't need this anymore and tbh, this PR was totally fine nine months ago, when you had the opportunity to merge this without conflicts (ironically, this is a "fix merge conflicts" PR). I didn't break anything, so I respectfully invite you to fix the merge conflicts yourself.

**Comment by ckerr** [comment]
Fair enough.

**Comment by tomtastic** [comment]
whaaaa?! 🤨

**Comment by RobFog** [comment]
> whaaaa?! 🤨

#265 was merged…

**Pull request closed without merging**
