### PR TITLE
FIX for issue #1082: Done script is now only executed on a finished download.

### LINKED ISSUE #1082: Done script called even for initial seed hash checking
I have the opinion that the done script should not be called when starting to seed a torrent with

`transmission-remote -a file.torrent -S --find /dir` # to make sure it does not download accidentally
`transmission-remote -t $X -v `# verify 
`transmission-remote -t $X -s `# start ( if above verify was successfull ..)

this can easily be fixed in the code by doing something like
`            if ( wasRunning && wasLeeching ) `

around the `torrentCallScript(tor, tr_sessionGetTorrentDoneScript(tor->session));`

in file torrent.c lines 2336 and following.

regards

### PR DESCRIPTION
**Pull request by devilopa**
Fixes #1082.

This modification is just wrapping the doneScript call in a if condition.

### CODE REVIEW

**Comment by tueksta** [comment]
If you remove the spaces inside the parentheses the code style check will pass.

**Comment by devilopa** [comment]
No idea why the Code Style check fails. I did `uncrustify --replace --no-backup uncrustify.cfg libtransmission/torrent.c` on the file and it didn't change anything.

**Comment by tueksta** [comment]
I think by now all your stuff is fine, it's just some other code that was already there that is broken. I guess this project isn't in the best state, someone needs to clean up a bit.

**Comment by ckerr** [comment]
Superseded by https://github.com/transmission/transmission/pull/2619

**Pull request closed without merging**
