### PR TITLE
refactor: replace tr_info with tr_torrent_metainfo

### PR DESCRIPTION
**Pull request by ckerr**
This has been in the works for a month (or more?) now and is a prerequisite for two performance improvements that I want to get merged before the next stable release.

This is the final step of decoupling the rest of Transmission from the `tr_info` struct, which had been at the core of every torrent object and was referenced by virtually every part of Transmission's code. It's been a lot of work to get to this point!

### CODE REVIEW

**Comment by GScottElshaw** [comment]
@mikedld Similar deal? It has been stuck for hours.

**Comment by GScottElshaw** [comment]
@ckerr Okay Charles, i'm game. Talk me through it.

**Comment by ckerr** [comment]
> @ckerr Okay Charles, i'm game. Talk me through it.

Should be safe to test now.

If you want to make backups, it's the two directories that have the `.resume` files and `.torrent` files. On Linux, by default that's in `~/.config/transmission`. 

On macOS, IIRC it's in `~/Library/Application Support/Transmission`

**Comment by GScottElshaw** [comment]
> Should be safe to test now. I'm running it on my live torrents FWIW.

I'm not seeing any problems here, Charles. 3.00+ (3a96a5c316) MacOS 11.6.2.

**Comment by PriitUring** [comment]
**Main pull request title has a typo:**
"tr_torrent_metaifo" instead of "tr_torrent_metainfo".

**First commit title also has a typo:**
"tr_torrent_metafo" instead of "tr_torrent_metainfo"

**Comment by GScottElshaw** [comment]
> > @ckerr Okay Charles, i'm game. Talk me through it.
> 
> Should be safe to test now. I'm running it on my live torrents FWIW.
> 
> If you want to make backups, it's the two directories that have the `.resume` files and `.torrent` files. On Linux, by default that's in `~/.config/transmission`.
> 
> On macOS, IIRC it's in `~/Library/Application Support/Transmission`

Charles, any idea why the build process is as long as it is right now? This current build has been running for 13 hours now.

**Comment by ckerr** [comment]
No idea. Thoughs @mikedld?

**Comment by mikedld** [comment]
Jenkins and TeamCity needed to be reconfigured to use "main" instead of "master" as primary branch name.

**Comment by GScottElshaw** [comment]
> No idea. Thoughs @mikedld?

Well, obviously, it's time for a musical interlude. The transmission of Transmission will rejoin you shortly. In the leanwhile... https://www.youtube.com/watch?v=u-161h9KLh4

**Comment by GScottElshaw** [comment]
A restart of 3.00+ (db23ca4c6b) wiped out all of the torrents on MacOS Big Sur.

**Comment by ckerr** [comment]
> A restart of 3.00+ ([db23ca4](https://github.com/transmission/transmission/commit/db23ca4c6b65ff419a2327c1148c3efd142e314f)) wiped out all of the torrents on MacOS Big Sur. Also, selecting a torrent and trying to save torrent file as... results in the following pop-up.

I often don't look at PR pages after they're merged / closed, so I didn't see this earlier. Might be better to file new issues for each new issue that you find, to make it harder for anything to fall through the cracks or get overlooked.

Thank you for reporting these issues! I'm pretty sure I've mentioned this before, but but users like you testing out the nightly builds are _extremely_ helpful, especially until we reach that distant-future dream goal of full test coverage. Most of the codebase wasn't designed with testing in mind, so that's going to take a lot of work... :slightly_smiling_face:

**Pull request merged**
