### PR TITLE
[macOS] Fix global popover clipping.

### LINKED ISSUE #3263: macOS - Improve: A drop-down list box
Delete as unnecessary. And in certain situations it is misleading by pointing to the wrong place.
Screen Shot 2022-06-12 at 08 48 16

- Example:
Screen Shot 2022-06-12 at 08 48 16 copy

- Example: macOS
172881226-6b53bdca-00c8-433d-b72e-6980d6e836b4
172881236-8a764dcc-4f2d-4c31-b352-1abd359d25ec

### PR DESCRIPTION
**Pull request by nevack**
Fixes #3263

### CODE REVIEW

**Comment by nevack** [comment]
@Coeur @sweetppro Can you take a look, please?

**Comment by sweetppro** [comment]
Looks good to me, but I’m away from my computer right now

**Comment by Oleg-Chashko** [comment]
Looks not good.
Screen Shot 2022-06-12 at 12 29 24

**Comment by sweetppro** [comment]
> It doesn't look good.
> Screen Shot 2022-06-12 at 12 29 24

this only occurs when Transmission is in the bottom left hand corner of the screen...

**Comment by Oleg-Chashko** [comment]
> this only occurs when Transmission is in the bottom left hand corner of the screen...

Imagine this: 
You go to a doctor and say: When I chew on my left side, my lower jaw tooth hurts. 
The doctor answers: Do your teeth hurt on your right side? 
You say no. 
The doctor says, Then chew on the right side only.

---
I wrote in the beginning that it should be removed, so as not to have problems in the future.
I have already checked this before. 
The problem is present, there are two options simply to solve:
1. Delete (easier and more logical).
2. Move the icons to the right (but this is a bad option).

**Comment by nevack** [comment]
@Oleg-Chashko I don't understand how removing existing feature will help.
It's better to fix it.

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko I don't understand how removing existing feature will help.
> It's better to fix it.

Example: macOS
173223205-4ec1e866-9770-446a-b6a2-77ab39092569
173223209-624e31ed-2b9e-421a-9699-81da7d1245c8

**Comment by nevack** [comment]
@Oleg-Chashko This is not that simple.
Context menus allow only list of textual one off actions.
Global limits menu of Transmission contains much more complex UI

**Comment by Oleg-Chashko** [comment]
Alternatively, swap the icons.

Screen Shot 2022-06-12 at 14 43 53

**Comment by nevack** [comment]
@Oleg-Chashko Can you test again?

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko Can you test again?

Yes, of course. I'll write as soon as I check it out.

**Comment by Oleg-Chashko** [comment]
@nevack 
The left side is excellent.

- The right side is not done.

Screen Shot 2022-06-12 at 15 27 26

**Comment by nevack** [comment]
@Oleg-Chashko Please, check again :)

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko Please, check again :)

Yes, of course. :)

**Comment by Oleg-Chashko** [comment]
@nevack 
Is excellent, Test passed ❤️

**Comment by ckerr** [comment]
@nevack I’m happy to merge this once the conflicts are resolved

**Comment by nevack** [comment]
> @nevack I’m happy to merge this once the conflicts are resolved

Done

**Comment by sweetppro** [comment]
> @Coeur @sweetppro @nevack can y'all take a look at these macOS client regressions? #3283 #3282 #3281

These will all most likely be fixed once I finish updating the main window to use autolayout

**Comment by nevack** [comment]
> @Coeur @sweetppro @nevack can y'all take a look at these macOS client regressions? #3283 #3282 #3281

IMHO we need to revert recent work on FullScreen fixes (and maybe Toolbar) and figure it out properly with more thorough testing.
As far as I see, this changes created more issues than fixed. No offense to other contributors.

**Comment by sweetppro** [comment]
> …and figure it out properly with more thorough testing.

This is exactly what nightlies are for

**Comment by GaryElshaw** [comment]
Agreed

**Pull request merged**
