### PR TITLE
fix: improve resolution of Qt app icon

### LINKED ISSUE #5567: Transmission's new program and document icons are fuzzy in Windows 10
### What is the issue?

Transmission's new program and document icons are fuzzy in Windows 10, version 21H2 at 200% UI scale:
Preview - 01

This is what the icons should look like (icon by [yw4z](https://github.com/transmission/transmission/issues/1360#issuecomment-783600708) with quick highlights +30 & shadows +15 edit using paint.net):
Preview - 02
Preview - 03
[ICO files](https://github.com/transmission/transmission/files/11617508/Transmission.zip) (created with [paint.net 5.0.5](https://github.com/paintdotnet/release/releases) and [this plugin](https://forums.getpaint.net/topic/927-icon-cursor-and-animated-cursor-format-v37-may-2010/)) from these screenshots for reference on the icon sizes in Windows 10.

P.S. The default Start menu icon is different altogether for some reason: 
Preview - Start Menu

### Which application of Transmission?

Qt app on Windows

### Which version of Transmission?

4.0.3

### PR DESCRIPTION
**Pull request by GaryElshaw**
Replaces the poor resolution macOS icon for the correct qt icon.

Fixes #5567

### CODE REVIEW

**Comment by ckerr** [comment]
Looks reasonable but has some excessive size. If we run this `qtr.ico` through [this lossless compression script](https://gist.github.com/ckerr/6acb982f1c44ad24fab344ba98e3c1e0) I get it down from 43915 bytes to 35274 bytes :balance_scale:

**Comment by ckerr** [comment]
[qtr.ico.zip](https://github.com/transmission/transmission/files/11655567/qtr.ico.zip)

**Review by ckerr — CHANGES_REQUESTED** [review]
Looks reasonable but has some excessive size. If we run this qtr.ico through [this lossless compression script](https://gist.github.com/ckerr/6acb982f1c44ad24fab344ba98e3c1e0) I get it down from 43915 bytes to 35274 bytes balance_scale

**Comment by GaryElshaw** [comment]
Hmmm: "D:\a\transmission\transmission\obj\qt\transmission-qt-app-info.rc(50) : error RC2175 : resource file qtr.ico is not in 3.00 format"

**Comment by bananakid** [comment]
@ckerr, @GaryElshaw would you kindly make it clear if I'm supposed to be able to unzip and view qtr.ico.zip in Windows?

**Comment by GaryElshaw** [comment]
@ckerr Quick win. So, something to do with the compression process was making CI fail, but this should work now.

**Comment by GaryElshaw** [comment]
@ckerr ping.

**Review by ckerr — APPROVED** [review]

**Pull request merged**
