### PR TITLE
Updated Polish translation for transmission-gtk

### PR DESCRIPTION
**Pull request by piotrdrag**
Transmission's Launchpad seems all but dead since 2012, so here is the long needed update to Polish translation.

### CODE REVIEW

**Comment by jordanl** [comment]
I'm not sure what you mean by "all but dead since 2012". 

According to <https://translations.launchpad.net/transmission/trunk/+translations> it looks like the Polish translations were last updated earlier this month on 2016-09-05 and are now at 100%

However we absolutely should be pulling the translations into our repo more often

**Comment by piotrdrag** [comment]
I mean that the POT file has not been updated and PO files has not been pulled since 2012. I've been updating Polish translation on Launchpad for years and so far it was for nothing.

**Comment by mikedld** [comment]
@piotrdrag, is this solved with recent translations sync?

**Comment by piotrdrag** [comment]
Half of it is - Launchpad still has a 4-year-old POT file.

**Comment by d9h02f** [comment]
It is probably a good idea to move translation efforts to something else entirely, like [Weblate](https://hosted.weblate.org/) or [Transifex](https://www.transifex.com/).

**Pull request closed without merging**
