### PR TITLE
feat: minor changes to compact view

### PR DESCRIPTION
**Pull request by GaryElshaw**
Partially addresses user feedback in #4994. An increase in the progress bar size and a minor increase in the font size of the ratio and speed data.

The current UI:

web-gui-1

This pr:

web-gui-2

### CODE REVIEW

**Comment by Pentaphon** [comment]
I guess we're not able to add the rest of the torrent info from the non-compact mode between the title and existing speed/status info, so that compact and non-compact are equally informative? 

I think some people might find the progressbar still too long but I'm fine with making it smaller to compromise with them.

**Comment by GaryElshaw** [comment]
I'm trying to be careful in not undermining the whole idea of a separate 'compact' ui from the main. The progress bar is exactly half the size of the proposed mockup. We'll see what the feedback is like.

**Comment by GaryElshaw** [comment]
Closing in favour of #5319

**Comment by Pentaphon** [comment]
Hey @GaryElshaw do you think I should close my issue in favor of https://github.com/transmission/transmission/pull/5319 as well?

I think this new compact UI in the Qt client would be even more suitable for browsers.

**Comment by GaryElshaw** [comment]
@dareiff had some changes he wanted to make in this space, but i've lost track on all of the semver changes and requests. I'll reopen in the interim.

**Comment by GaryElshaw** [comment]
File conflicts :-( I'll try again with the recent updates.

**Pull request closed without merging**
