### PR TITLE
macOS remove support for macOS 10

### PR DESCRIPTION
**Pull request by sweetppro**
as discussed in #3302

* removes conditional calls
* removes macOS 10 image assets

### CODE REVIEW

**Comment by Coeur** [comment]
At this stage, I'm against raising the minimum target until we get a new stable release compatible with macOS 10.x.
There is no extra work needed to keep things as they are, and the Transmission version 3.0 is too buggy to stay the only one available for old macs.

Once Transmission 4.0 is out, then sure, we can bump the minimum version for 4.1.
So please @ckerr , just make a 4.0 release as is, and _then_ drop older versions support on main branch.

**Comment by sweetppro** [comment]
And what of the new bugs which will invariably be introduced with v4?

**Comment by sweetppro** [comment]
Do any of the maintainers even have a system running macOS 10? I’m running an M1, and the apple silicon transition is nearing completion. I’m not sure it’s even possible to run 10.10 on the current Apple lineup

**Comment by GaryElshaw** [comment]
> And what of the new bugs which will invariably be introduced with v4?

That is such a BS response and is ridiculously obtuse. Of course there are going to be bugs.

**Comment by sweetppro** [comment]
> > And what of the new bugs which will invariably be introduced with v4?
> 
> That is such a BS response and is ridiculously obtuse. Of course there are going to be bugs. There are multiple reasons why users might still be on 10.x, and multiple reasons why they don't have an M1 chip in their Mac.

And how can you debug on a system you don’t have….

**Comment by GaryElshaw** [comment]
Also a ridiculous assertion. What is TC or the new GitHub Actions but a means of checking a build.

**Comment by sweetppro** [comment]
> Also a ridiculous assertion. What is TC or the new GitHub Actions but a means of checking a build.

That doesn’t fix bugs

**Comment by Coeur** [comment]
I'm on macOS 10.14 Mojave, the last 32 bits macOS, hence why I did #2844 in the first place.
I'm OK to maintain a 10.x branch for some time.

**Comment by nevack** [comment]
> I'm on macOS 10.14 Mojave, the last 32 bits macOS

I want to clarify, Mojave is not 32bit, it's the last version that supports running 32bit code.
This is good point, though.
I think there're some users, that prefer to not upgrade from Mojave to have their old software functional, like many macOS games on Steam.

I agree with @Coeur,  such a huge leap from 10.10 to 11.0 is not necessary for a major release.
Let's bump target after 4.0 and only when we have a real reason to do so, not just dropping assets.

**Comment by ckerr** [comment]
OK. Since there is not consensus on the 11 bump -- Coeur, nevack, and Gary are all opposed -- and since the removal isn't a blocker for anything, let's table this for post-4.0.0.

**Comment by ckerr** [comment]
Based on feedback here and in #3302 I'm going to close this PR as superseded by #3310

**Pull request closed without merging**
