### PR TITLE
fix: do not lose magnet links when upgrading from tr3 to 4

### LINKED ISSUE #4295: can't resume magnet tasks added in 3.00
### What is the issue?

I have some almost dead tasks added from magent url in 3.00 and haven't downloaded torrent info successfully. 

And when I upgrade to 4.0.0 beta 2 these tasks are not resumed, they just disappear, and when I downgrade to 3.00, these tasks come back.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0 beta 2

### PR DESCRIPTION
**Pull request by Coeur**
Fix #4295

Notes: Fixed `4.0.0` issue that failed to migrate magnet links that were added in Transmission 3.

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
@Coeur thanks!

Would it be possible to add a `tests/libtransmission/torrent-metainfo-test.cc` test for this?

**Comment by ckerr** [comment]
CI failure is unrelated to this PR:

> Agent failed to create agent temp directory at /home/user/buildAgent/temp/agentTmp. Please check agent has necessary permissions and there is enough free space on disk.

**Comment by Coeur** [comment]
Some magnets still don't work with this change, I need to tweak it a little.

**Comment by Coeur** [comment]
> Would it be possible to add a `tests/libtransmission/torrent-metainfo-test.cc` test for this?

Test added, although I don't know how to run tests locally, so test is untested...

**Comment by Coeur** [comment]
Hum, my test is failing possibly because there are binary characters in the hash that I didn't copy-paste properly.

**Comment by ckerr** [comment]
@Coeur lmk when this is ready for review

**Comment by Coeur** [comment]
It is ready for review.

**Review by ckerr — APPROVED** [review]
Nice! LGTM.

**Pull request merged**
