### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by GaryElshaw**
I would like to be removed from the authors list, and also have my current GitHub status be reduced to contributor. @ckerr

### CODE REVIEW

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
> and also have my current GitHub status be reduced to contributor. @ckerr

@GaryElshaw there is nothing to change wrt your account status for in github.com/transmission/ settings; IIRC it was removed the last time you quit the project

**Comment by GaryElshaw** [comment]
> @GaryElshaw there is nothing to change wrt your account status for in github.com/transmission/ settings; IIRC it was removed the last time you quit the project

I disagree that i quit the project, I have had times where my frustrations with the project have been clear, needing time to cool down. This is not one of those times. 'Member' status has been meaningless when i can't access GitHub tools to ask for review, and can't even tag issues that arise in the project. 

Status doesn't mean anything to me. Recognition does. But it's also encumbent to reconcile that within the project, these things are seemingly not commensurate. I'm okay with it, which is why i've made this request.

**Comment by ckerr** [comment]
> This is not one of those times. 'Member' status has been meaningless when i can't access GitHub tools to ask for review, and can't even tag issues that arise in the project.

I don't understand this comment. Team members & outside collaborators do have this ability; e.g. I know that Coeur and tearfur both set labels in GitHub all the time. My memory isn't perfect and I can't look up the discussion because IIRC it took place in the GitHub "Team Discussions" feature that GitHub removed, but I think your permissions were removed the when you left the project, and you never asked for them to be restored.

**Comment by ckerr** [comment]
You know what, I don't have enough [spoons today](https://en.wikipedia.org/wiki/Spoon_theory) to debate you on whether or not you're getting enough attention on the project. 

If you want to leave the project because your "change the width from 275 pixels to 320 pixels" PR hasn't been merged when it's been approved for five days, that's fucking fine. Instead of wondering how to respond to your PR request and having Yet Another Drama Discussion With You, I could have been trying to triage the CI failure or doing PR review on the backlog that Coeur has. Or maybe working on my Day Job backlog which is even longer.

**Comment by ckerr** [comment]
If you want to leave the project (for the third? fourth? time) because your "change the width from 275 pixels to 320 pixels" PR hasn't been merged in five days since its approval **while all builds that touch code are broken in CI**... I don't have enough [spoons today](https://en.wikipedia.org/wiki/Spoon_theory) to debate you on this.  The last couple of times you've left the project, I've tried being conciliatory, I've tried being polite, I've tried arguing what I thought were the facts, but we keep coming back to this point.

Instead of wondering how to respond to your messages and having Yet Another Drama Discussion With You, I could have been trying to triage the sanitizer CI failures or doing PR review on the backlog that Coeur has helpfully provided. Or maybe working on my Day Job backlog which is even longer.

If you want to contribute, you're always welcome. But the drama is not.

**Comment by ckerr** [comment]
[TWO YEARS!! TWO YEARS](https://github.com/transmission/transmission/pull/3308#issuecomment-1157739706) we've been doing this stupid dance.

If you want to quit / take a break from / get kicked from the project for the third? fourth? time because your "change the width from 275 pixels to 320 pixels" PR hasn't been merged in five days since its approval **while all builds that touch code are broken in CI**... I don't have enough [spoons today](https://en.wikipedia.org/wiki/Spoon_theory) to debate you on this.  The last couple of times we've done this dance, I've tried being conciliatory, I've tried being polite, I've tried arguing what I thought were the facts, but we keep coming back to this point.

I've tried blocking you for 1 week, I've tried blocking you for a month... and that's the upper limit that GitHub allows for time-bounded blocks. This time I'm blocking you until I'm stupid enough to unblock you and open myself up to another two years of this drama.

**Comment by ckerr** [comment]
Also I notice that even though I'm the maintainer you have the issues with, you still damn well @'ed me to approve and merge this. Manipulative, games-playing bullshit. If you really had a problem with me, why not use Mike or Mitchell instead? No, cause you want to make me feel responsible for it all.

**Comment by ckerr** [comment]
Also I notice that even though I'm the maintainer you have the issues with, you still damn well @'ed me to approve and merge this. Manipulative, games-playing bullshit. If you really had a problem with me, why not use Mike or Mitchell instead? No, it's gotta be me because you want me to feel responsible for you leaving.

**Pull request merged**
