### PR TITLE
change alt to control for shortcuts

### LINKED ISSUE #4829: alt-i keyboard shortcut for torrent inspector doesn't work
### What is the issue?

Browser is MacOS Safari

Keyboard shortcut hint says to use "Alt-I" to open the inspection window.
This would, using a Mac keyboard, usually translate to either Option-I (correct) or Command-I (problematic).
Neither work. Command-I is problematic because the command keys are often in use by the browser (e.g. Command-O opens a dialog box).

Fixes:
- Allow option- versions of the keys through the web interface.
- Better yet, allow straight keys again (just like transmission 3.0), which will work much better on mobile screens!

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.0-stable

### PR DESCRIPTION
**Pull request by tessus**
I changed the modifier key from `Alt` to `Control`, which makes it possible to use it on macOS.

The `Deselect all` shortcut has also been changed from `Control+A` to `Control+D`.

fixes #4829

### CODE REVIEW

**Comment by ckerr** [comment]
@tessus Thanks you for doing this! :heart: 

Since it's easier for you to test (since you have a Mac) could you please confirm that all these shortcuts work on both Safari and Chrome?

IIRC there was some potential conflict e.g. with Ctrl+O being the browser's "open" as well but TBH I'm fuzzy on the details and might be misremembering -- so the shortest path is to just test and make sure.

I believe FF behaves similarly to Chrome so testing on Safari & Chrome should be sufficient

**Comment by tessus** [comment]
Yep, it works on Firefox, Chrome, and Safari.

**Comment by tessus** [comment]
Hmm, I just saw that I cannot commit the generated file. I did that only, because it wsa in the source tree. Shall I remove it from my PR?

**Comment by ckerr** [comment]
> Hmm, I just saw that I cannot commit the generated file. I did that only, because it wsa in the source tree. Shall I remove it from my PR?

Yes, please.

I don't think we've ever had anyone submit a malicious patch, but webpacked files are difficult to review and so letting the CI bots build the webpack files ensures that nothing gets in there that shouldn't be there.

**Comment by tessus** [comment]
Done.

**Review by ckerr — APPROVED** [review]

**Comment by tessus** [comment]
I'm slightly confused why you committed my changes again. Now they are no longer gpg signed. Anyway, not that important, just curious.

**Comment by ckerr** [comment]
@tessus I was just rebasing them on top of the lastest commit in `main`, that's all

**Comment by tessus** [comment]
I see, thanks for the info. I usually only rebase in a branch when there are conflicts, which is why I didn't understand why a rebase was done.

**Comment by ckerr** [comment]
Notes: Fixed broken keyboard shortcuts on desktop Safari.

**Pull request merged**
