### PR TITLE
macOS add full screen support

### PR DESCRIPTION
**Pull request by sweetppro**
as described in #3297

adds FullScreen support back into the macOS version
no refactoring into a seperate Category as in the previous commit #3297

* adds auto layout to MainMenu.xib
* now using constraints to calculate view heights

### CODE REVIEW

**Comment by ckerr** [comment]
@sweetppro I think this PR has conflicts with main now that #3304 has landed :dizzy:

**Comment by sweetppro** [comment]
Ah Git…
I’ll fix it up in a little

**Comment by Oleg-Chashko** [comment]
What about the errors that appeared after this PR in full screen mode?

**Comment by sweetppro** [comment]
this PR uses a different approach, and shouldn't have any of the issues of the other PR.
I have however discovered an issue with showing the toolbar, when autosize is enabled.

If theres any NSLayoutConstaraint wizards who can see a solution, that would be great

**Comment by Oleg-Chashko** [comment]
When autosize is enabled, I found at least 3 bugs.

**Comment by sweetppro** [comment]
with this PR?
which version of macOS?

**Comment by Oleg-Chashko** [comment]
1. Yes
2. v.12.4 (21F79)

_If theres any NSLayoutConstaraint wizards who can see a solution, that would be great_

That would be wonderful.

**Pull request merged**
