### PR TITLE
feat: support redirects to magnet

### LINKED ISSUE #5847: Feature Request: handling shortlinks to magnet links when copy-pasting
### What is the issue?

When copy-pasting a shortlink (aka, from an URL shortener) of a magnet link, the macOS app says it can't support that format.
Other clients like qBittorrent are supporting it.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0

### PR DESCRIPTION
**Pull request by Coeur**
Fix #5847 (on macOS app)

### CODE REVIEW

**Review by sweetppro — APPROVED** [review]
works well
👍

**Comment by ckerr** [comment]
@Coeur needs a 'Notes:' comment plz :bowing_man:

**Review by nevack — APPROVED** [review]
I find this solution very clever!

**Comment by Coeur** [comment]
Notes: feat: support redirects to magnet

**Pull request merged**
