### PR TITLE
Feature/show public ip

### PR DESCRIPTION
**Pull request by mervij**
The third-party service (https://www.ipify.org/) is being utilized to fetch the IP address, because the RPC interface doesn't provide easy access to it.

IP is fetched only once. IP is updated after the page is refreshed. 

This pull request is part of a student project of Tampere University.

### CODE REVIEW

**Comment by malte-v** [comment]
-1 for relying on an external 3rd party service. There are several torrent leak checkers on the web you can use to validate your configuration.

**Comment by ckerr** [comment]
Hi @mervij, thanks for the PR!

I'm not sure that I understand the purpose of this feature. What is the use case for being able to see the IP address of the web client?

**Comment by peterberbec** [comment]
> Hi @mervij, thanks for the PR!
> 
> I'm not sure that I understand the purpose of this feature. What is the use case for being able to see the IP address of the web client?

I'm not the submitter, but was looking for this feature myself.

My use case is to determine if my VPN is functioning properly. If the public IP in the transmission webUI is different than my WAN IP, I know my VPN is functioning properly. I can get the same result by SSHing to my seedbox and checking that way, but the webUI is very convenient.

**Comment by ckerr** [comment]
That makes sense. Thanks for the reply!

**Comment by Vaadasch** [comment]
#5785

**Pull request closed without merging**
