### PR TITLE
fix: limit number of bad pieces to accept from a webseed

### LINKED ISSUE #267: webseed torrents can download too much excess data
Errornous torrents like http://mirror.aarnet.edu.au/pub/sage/spkg/upstream/singular/meta/singular-3.1.5.tar.bz2.torrent can cause a large amount of download data to be transferred (eventually infinite) which doesn't make sense because they never seem to be finished. There should be configurable limit of this checksum error data volume to be downloaded.

experienced with 2.92-2ubuntu1 on Ubuntu 17.04

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #267.

Notes: Limit the number of bad pieces to accept from a webseed before banning it.

### CODE REVIEW

**Comment by tearfur** [comment]
Anybody know of a webseed I can test this PR with?

**Comment by Pentaphon** [comment]
> Anybody know of a webseed I can test this PR with? The webseeds provided by the issue either isn't working anymore, or is not corrupt.

Arch uses webseeds.
https://archlinux.org/releng/releases/

**Comment by ckerr** [comment]
@tearfur probably the best way to do this reliably is to do it locally, e.g. with a local webserver and a torrent with a localhost webseed. Then after creating the .torrent file, overwrite all the file contents with bad data and serve it up on the local webserver.

**Comment by tearfur** [comment]
Finished testing, looks to be working as intended.

```
[2024-06-12 07:24:04.768] trc test.dat increasing peer localhost:80 strike count to 1 (peer-mgr.cc:646)
[2024-06-12 07:24:04.768] trc test.dat increasing peer localhost:80 strike count to 2 (peer-mgr.cc:646)
[2024-06-12 07:24:04.768] trc test.dat increasing peer localhost:80 strike count to 3 (peer-mgr.cc:646)
[2024-06-12 07:24:04.768] trc test.dat increasing peer localhost:80 strike count to 4 (peer-mgr.cc:646)
[2024-06-12 07:24:04.768] trc test.dat increasing peer localhost:80 strike count to 5 (peer-mgr.cc:646)
[2024-06-12 07:24:04.768] trc test.dat banning peer localhost:80 (peer-mgr.cc:651)
```

**Review by ckerr — APPROVED** [review]

**Pull request merged**
