### PR TITLE
chore: improved filterbar for narrowed viewports in web client

### LINKED ISSUE #6375: upload/download speed uses 2 rows
### What is the issue?

image

Once again there's something off with the UI elements. The up and download speed indicators wrap and are displayed in 2 rows. 

The previous fix doesn't work anymore:

```
sed -i 's/speed-up-label{text-align:right;width:70px}/speed-up-label{text-align:right;width:100px;white-space:nowrap}/g'
```

Update: Sorry, the fix still works. It is now in a different file, which I missed.

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.5

### PR DESCRIPTION
**Pull request by Rukario**
Features and fixes ported from #5828 for 4.0.x release

Resolves #6375

Notes: General UI improvement related to filterbar and fixes download/upload speed info wrap.

Left: This PR, Right: Original
Transmission 4 0 x

### CODE REVIEW

**Comment by Pentaphon** [comment]
Perhaps this should be made consistent with https://github.com/transmission/transmission/pull/6739 by putting the arrows to the right as @tearfur has done?

**Comment by Rukario** [comment]
@Pentaphon Ideally this PR jointed with a 4.0.x port of #6739 that would change the layout to however we want for the 4.0.x release

**Review by ckerr — CHANGES_REQUESTED** [review]
Minor branch shear w / web/assets/css/transmission-app.scss

**Comment by Rukario** [comment]
Oh, it looks like another PR (#6570) was merged that isn't complied with narrowed viewport this PR tried to resolve. What should I do from this point?

**Comment by ckerr** [comment]
@tearfur wdyt?

**Comment by tearfur** [comment]
I think this PR should overwrite the changes made in #6570. Maybe we can just revert it, then the git conflict will be gone.

We reached a consensus in #6739 over the solution for stopping the transfer speed info from moving around as the text changes, and that requires merging this PR, then porting #6739 to `4.0.x`.

**Comment by ckerr** [comment]
@Rukario ^

**Comment by Rukario** [comment]
Ok, overwrote changes made in another PR

Have we really reached consensus for fixed width though?

**Comment by tearfur** [comment]
Well, IMO the bottom line is regardless of how the "fixed width" discussion develops, this PR should be merged.

**Review by tearfur — APPROVED** [review]

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
@Rukario this has a little bit of shear with your original PR -- you removed the width property for speed-dn-label and speed-up-label, and there's also #6570 which widened it to 100px and set `white-space: nowrap`

I've preserved 6570 here but TBH I'm not sure if it's still needed with your other changes, so please feel free to LMK or fix my meddling in a followup PR :heart:

**Comment by tearfur** [comment]
Yes, this PR is supposed to overwrite #6570 as I understand.

I'll be porting #6739 over to `4.0.x` in the coming few days. I can fix the shear there.

**Pull request merged**
