### PR TITLE
Added Support for Mac OS 10.14 Light and Dark Mode

### PR DESCRIPTION
**Pull request by williamluke**

### CODE REVIEW

**Comment by Enuqt** [comment]
I hope the next release will be published soon thanks for the branch worked Perfectly looked very native !!!

**Comment by fishcharlie** [comment]
@mikedld Any ideas when this will be merged in and a new released will be published that integrates this?

**Comment by mikedld** [comment]
@fishcharlie As soon as both are ready.

**Comment by fishcharlie** [comment]
@mikedld Is there anything I can do to help with this process and getting it out quicker?

**Comment by mikedld** [comment]
@fishcharlie Thorough testing of this PR will be highly appreciated.

As for the release, the list of pending issues is at [3.00 milestone](https://github.com/transmission/transmission/milestone/2) page but that's out of scope here.

**Comment by juliand665** [comment]
Switching between dark and light mode and clicking the tab buttons in the info window can lead to weird looks because of the way their colors are calculated.

screenshot of tab buttons

The easiest solution would probably be to not give them a complex gradient to begin with, instead making them a flat color. The fact that they are buttons should be obvious enough anyway.

**Comment by mikedld** [comment]
@williamluke What's wrong with this PR that you decided to close it? I though it was going great and nearing completion...

**Comment by williamluke** [comment]
Sorry, I had to make a lot of changes to this request in oreder to support Yosemite (10.10) in addition to different issues with dark/light mode.  So I needed to create another branch to isolate those changes into a seperate branch. I didn't actually intend to close this quite yet. I made an attempt to revert changes and that somehow closed it.

**Pull request closed without merging**
