### PR TITLE
New macOS Big Sur icons

### PR DESCRIPTION
**Pull request by hazarek**
icons I designed. Icons are unlicensed.
Screenshots;

Ekran Resmi 2020-12-14 00 47 58

Ekran Resmi 2020-12-14 00 49 25
Ekran Resmi 2020-12-14 00 49 45

### CODE REVIEW

**Comment by RobFog** [comment]
I find them quite ugly, to be honest.

**Comment by hazarek** [comment]
> I find them quite ugly, to be honest.

better than 3D illustration. this is an app icon not an artwork.

**Comment by RobFog** [comment]
This one's neat: https://forum.transmissionbt.com/viewtopic.php?p=79413&sid=341c8b15577025218d947e2132c05a86#p79413

**Comment by hazarek** [comment]
> This one's neat: https://forum.transmissionbt.com/viewtopic.php?p=79413&sid=341c8b15577025218d947e2132c05a86#p79413

https://macosicons.com/
I've tried all of them, none of them look good on Big Sur.

**Comment by MaddTheSane** [comment]
If the Transmission handle is non-compliant, then Xcode's icon is non-compliant with the hammer.

**Comment by hazarek** [comment]
> If the Transmission handle is non-compliant, then Xcode's icon is non-compliant with the hammer.

@MaddTheSane
Does not fit the official template. there is an overflow. Xcode icon follows the rules, and no overflow.
app-icon-layout-guides_2x-1

https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon

> Avoid defining contours that suggest a shape other than a rounded rectangle. In rare cases, you might want to fine-tune the basic app icon shape, but doing so risks creating an icon that looks like it doesn’t belong in macOS 11. If you must alter the shape, prefer **subtle adjustments that continue to express a rounded rectangle** silhouette.

# soft-edged exception (very rare)
Suitable for soft edges, no overflow.

app-icon-consistent-shape_2x

**Pull request closed without merging**
