### PR TITLE
Recommended Project Settings

### PR DESCRIPTION
**Pull request by Coeur**
Xcode 15.3 Recommended Project Settings.
I've verified that it's compatible with Xcode 11.3.1.

### CODE REVIEW

**Comment by nevack** [comment]
I tried `ENABLE_USER_SCRIPT_SANDBOXING` before, and this won't work as is, I think.
1. You need to declare shell script we call from build steps.
2. You need to declare everything they reference as inputs (previously, this was `.git/` for example).

**Comment by Coeur** [comment]
Indeed, not working as is:
>[21:28:06 ]      /usr/bin/sandbox-exec -D SCRIPT_OUTPUT_FILE_0\=/Users/teamcity/buildAgent2/work/1f3bff43dd55cfe9/third-party/miniupnpc/miniupnpcstrings.h 
>[21:28:06 ]  sh: updateminiupnpcstrings.sh: Operation not permitted

Want to try to do it, nevack?

**Comment by Coeur** [comment]
>ln: ../evconfig-private.h: Operation not permitted

OK, still some tweaking needed.

**Comment by nevack** [comment]
> Should be good now with [f3c6099](https://github.com/transmission/transmission/commit/f3c6099ee126b07a7a625e62a30dfd601ca2592d) ?

No, I don't think so.
Please, take a look at https://github.com/transmission/transmission/blob/main/update-version-h.sh#L61-L81
This script reads `.git/` (indirectly, via invoking `git`) and reads+writes `REVISION`

<details>
<summary>I think this reads and writes are just masked by shell fallbacks and stderr redirections, see:</summary>

```
creating libtransmission/version.h

fatal: not a git repository (or any of the parent directories): .git

rm: REVISION: Operation not permitted

update-version-h.sh: line 83: libtransmission/version.h.new: Operation not permitted

update-version-h.sh: line 104: libtransmission/version.h.new: Operation not permitted

mv: rename libtransmission/version.h.new to libtransmission/version.h: No such file or directory

Sandbox: git(39054) deny(1) file-read-data /Users/nevack/Developer/Projects/transmission/.git/HEAD

Sandbox: rm(39055) deny(1) file-write-unlink /Users/nevack/Developer/Projects/transmission/REVISION

Sandbox: bash(39059) deny(1) file-write-create /Users/nevack/Developer/Projects/transmission/libtransmission/version.h.new

Sandbox: bash(39039) deny(1) file-write-create /Users/nevack/Developer/Projects/transmission/libtransmission/version.h.new

```

```
creating libtransmission/version.h
fatal: not a git repository (or any of the parent directories): .git
```

```
creating libtransmission/version.h
warning: unable to access '.git/config': Operation not permitted
fatal: unable to access '.git/config': Operation not permitted
```

</details>

Contents of `libtransmission/version.h`:

<details>
<summary>With your PR:</summary>

```
#pragma once

#define PEERID_PREFIX             "-TR410Z-"
#define USERAGENT_PREFIX          "4.1.0-dev"
#define VCS_REVISION              "0"
#define VCS_REVISION_NUM          0
#define SHORT_VERSION_STRING      "4.1.0-dev"
#define LONG_VERSION_STRING       "4.1.0-dev (0)"
#define VERSION_STRING_INFOPLIST  4.1.0-dev
#define BUILD_STRING_INFOPLIST    14714.4.1.0
#define MAJOR_VERSION             4
#define MINOR_VERSION             1
#define PATCH_VERSION             0
#define TR_NIGHTLY_RELEASE        1
```

</details>


<details>
<summary>Before:</summary>

```
#pragma once

#define PEERID_PREFIX             "-TR410Z-"
#define USERAGENT_PREFIX          "4.1.0-dev"
#define VCS_REVISION              "340d0d4966"
#define VCS_REVISION_NUM          340d0d4966
#define SHORT_VERSION_STRING      "4.1.0-dev"
#define LONG_VERSION_STRING       "4.1.0-dev (340d0d4966)"
#define VERSION_STRING_INFOPLIST  4.1.0-dev
#define BUILD_STRING_INFOPLIST    14714.4.1.0
#define MAJOR_VERSION             4
#define MINOR_VERSION             1
#define PATCH_VERSION             0
#define TR_NIGHTLY_RELEASE        1
```

</details>

**Comment by nevack** [comment]
@Coeur Do you still want `ENABLE_USER_SCRIPT_SANDBOXING=YES` right now? :D
I think this can be enabled later, when our Xcode build is fully out-of-tree and incremental.

**Comment by Coeur** [comment]
Ah indeed, good catch on the REVISION not being updated. Well, I couldn't find a workaround to that, so for now, yes, I'll keep sanboxing disabled.

**Comment by Coeur** [comment]
> You enabled sandboxing in project, but disabled it in specific (`libtransmission`) target, right?

right

> Also, `BuildIndependentTargetsInParallel` has been lost in the second commit, is it intentional?

intentional: any single xcodeproj edit will currently auto-remove it. So I prefer to wait for Apple to fix Xcode for BuildIndependentTargetsInParallel support first.

**Comment by Coeur** [comment]
ping @nevack

**Comment by nevack** [comment]
> So I prefer to wait for Apple to fix Xcode for BuildIndependentTargetsInParallel support first.

Is this fixed with Xcode 15.3?

**Comment by Coeur** [comment]
> > So I prefer to wait for Apple to fix Xcode for BuildIndependentTargetsInParallel support first.
> 
> Is this fixed with Xcode 15.3?

It seems not. I'll create a feedback assistant report.

**Comment by Coeur** [comment]
@nevack code_style change done in 26182d071efc2f47065fe445c7015e04df232ea3

**Comment by Coeur** [comment]
@nevack ?

**Review by nevack — APPROVED** [review]
LGTM

**Pull request merged**
