### PR TITLE
refactor: unified shadow properties for web client

### PR DESCRIPTION
**Pull request by Rukario**
Side note: The context menu and inspector page will use bigger shadow like others. We can tweak it if you think there's a better shadow to use...

Notes: Unified CSS shadow properties

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
@Rukario if possible, please attach before/after screenshots -- that makes it much easier for other contributors to review the UI changes :smile_cat:

**Comment by Rukario** [comment]
Above: This PR, Below: Original

Transmission shadow

**Comment by GaryElshaw** [comment]
cc @dareiff

**Comment by dareiff** [comment]
I like the code minimization, but I don’t have an opinion on the shadows themselves — if someone else likes them, I like them!

**Comment by GaryElshaw** [comment]
> if someone else likes them, I like them!

¯\_(ツ)_/¯

**Comment by Rukario** [comment]
File conflict resolved

**Pull request merged**
