### PR TITLE
updated no group image to match new circular stlye

### PR DESCRIPTION
**Pull request by sweetppro**
https://github.com/transmission/transmission/pull/3067

### CODE REVIEW

**Comment by GaryElshaw** [comment]
?

**Comment by sweetppro** [comment]
groupimage

**Comment by sweetppro** [comment]
> ?

using the same dashed line as in v3, see image above
:)

**Comment by GaryElshaw** [comment]
But i, in that PR. Choice is good.

SCR-20220515-nbz

**Comment by sweetppro** [comment]
just another option, I agree - choice is good

**Comment by GaryElshaw** [comment]
Confession. I always hated that dashed icon :-(

**Comment by sweetppro** [comment]
closed in favour of https://github.com/transmission/transmission/pull/3094

**Pull request closed without merging**
