### PR TITLE
chore: convert `transmission-web` to ES module

### PR DESCRIPTION
**Pull request by tearfur**
Fix the CI failure at https://github.com/transmission/transmission/actions/runs/11562354743/job/32183335007.
Regression from #7198.

```
> node generate-buildonly.js

(node:3759) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/runner/work/transmission/transmission/web/generate-buildonly.js:1
import fs from 'node:fs';
^^^^^^
```

### CODE REVIEW

**Comment by tearfur** [comment]
### Discussion

I could also fix the CI failure by simply renaming `generate-buildonly.js` to `generate-buildonly.mjs`, but I figured we might as well move to ES modules.

I already have #7003 in the works for making the full conversion from CommonJS to ESM.

**Review by ckerr — APPROVED** [review]

**Comment by nevack** [comment]
@ckerr Is there anything else to do for this to be merged?
Do no want to press you into anything, just want to have "green" master branch once again :)

**Comment by nevack** [comment]
Can reproduce with Node.js v18.20.4 as on CI
Cannot with Node.js v20.18.0

**Comment by tearfur** [comment]
Fixed in #7214.

**Pull request merged**
