### PR TITLE
Minor localisation fixes

### PR DESCRIPTION
**Pull request by bitigchi**
Some improvements in Turkish strings, that are not available through Transifex.

### CODE REVIEW

**Comment by bitigchi** [comment]
May I request a review for this one?

**Comment by Coeur** [comment]
@bitigchi 
"This branch has conflicts that must be resolved"

**Comment by ckerr** [comment]
@bitigchi DYK if there's a way to expose these strings for translation in Transifex?

I don't think any of the maintainers are qualified to review the translations in this PR; and moreover, I'm concerned that these changes could get overwritten the next time a maintainer downloads translations from Transifex and stores them in this repository.

That's why this PR hasn't gotten more attention sooner; I'm really not sure how to proceed with it

**Comment by bitigchi** [comment]
@ckerr, thanks for the reply. Please see [#3039](https://github.com/transmission/transmission/pull/3039)

**Comment by bitigchi** [comment]
@ckerr, it looks like the proposed fix will take longer, unless someone else volunteers to take it on. In the meantime, this change would be completely safe I believe, since these strings are not in Transifex, and only affects the main branch (and only strings are modified).

**Comment by bitigchi** [comment]
Already updated through Transifex.

**Pull request closed without merging**
