### PR TITLE
Keep the GTK icon and ico files consistent

### PR DESCRIPTION
**Pull request by GaryElshaw**
Restoring the more contemporary GTK icon makes some sense after being in GTK for the last while. Current 3.0 builds in flatpak, snap etc are using it, and having the client and tray match seems right. More on this here #3432 and #3403.

### CODE REVIEW

**Review by ckerr — CHANGES_REQUESTED** [review]
1. PR title lacks a verb or clear description. Third time ([1](https://github.com/transmission/transmission/pull/3351#issuecomment-1168123675), [2](https://github.com/transmission/transmission/pull/3238#pullrequestreview-1000726332)) I've  requested this in your PRs Gary. Please?  :smile_cat: 

2. This appears to not be a multisize ico -- the one it's replacing has six icon sizes and is sourced from an svg so that the six images are smooth. This one in the PR also looks good, but should be prescaled. You can see the contrast by opening both icons in the GIMP. See `gtk/icons/SOURCES.md` for notes that I took when making the older ico file.

**Comment by ckerr** [comment]
Oh another question, do you have an svg source for that icon? If so, let's get it into the repository for safekeeping

**Comment by GaryElshaw** [comment]
> Oh another question, do you have an svg source for that icon? If so, let's get it into the repository for safekeeping

It's already there as hicolor_apps_scalable_transmission.svg

**Review by ckerr — APPROVED** [review]
LGTM. Thanks for the update!

**Comment by ckerr** [comment]
CI failure in TC Sanity is unrelated to PR

**Pull request merged**
