### PR TITLE
Update workflow to Qt 6 on macOS

### PR DESCRIPTION
**Pull request by fxcoudert**
- Update workflow to Qt 6 on macOS
- Remove weird (probably copy-pasted) brew-related lines for Linux

### CODE REVIEW

**Review by ckerr — APPROVED** [review]

**Comment by fetzu** [comment]
It looks like compiling is failing with Qt 6 because it is using some features first introduced in macOS 10.15 ([officially, macOS 11 onwards is supported](https://doc.qt.io/qt-6/macos.html#supported-versions)).

Here is one excerpt from [the logs](https://github.com/transmission/transmission/actions/runs/6759976930/job/18373195275) (note: this happens on multiple files):

```
FAILED: qt/CMakeFiles/transmission-qt.dir/AddData.cc.o 
/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DENABLE_DBUS_INTEROP -DFMT_EXCEPTIONS=0 -DFMT_HEADER_ONLY=1 -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DSMALL_DISABLE_EXCEPTIONS=1 -DTRANSLATIONS_DIR=\"/Users/runner/work/transmission/transmission/pfx/share/transmission/translations\" -I/Users/runner/work/transmission/transmission/obj/qt/transmission-qt_autogen/include -I/Users/runner/work/transmission/transmission/src/qt -I/Users/runner/work/transmission/transmission/src/libtransmission/.. -I/Users/runner/work/transmission/transmission/obj/libtransmission/.. -isystem /Users/runner/work/transmission/transmission/src/third-party/fmt/include -isystem /Users/runner/work/transmission/transmission/src/third-party/small/include -isystem /usr/local/Cellar/libevent/2.1.12_1/include -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/share/qt/mkspecs/macx-clang -isystem /usr/local/opt/qt/include -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /usr/local/opt/qt/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -isystem /usr/local/opt/qt/lib/QtSvg.framework/Headers -isystem /usr/local/opt/qt/lib/QtDBus.framework/Headers -O2 -g -DNDEBUG -std=gnu++17 -arch x86_64 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.14.6 -W -Wall -Wextra -Wcast-align -Wexit-time-destructors -Wextra-semi -Wextra-semi-stmt -Wextra-tokens -Wfloat-equal -Wgnu -Winit-self -Wint-in-bool-context -Wmissing-format-attribute -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wredundant-move -Wreorder-ctor -Wreturn-std-move -Wself-assign -Wself-move -Wsemicolon-before-method-body -Wsentinel -Wshadow -Wsign-compare -Wsometimes-uninitialized -Wstring-conversion -Wsuggest-destructor-override -Wsuggest-override -Wuninitialized -Wunreachable-code -Wunused -Wunused-const-variable -Wunused-parameter -Wunused-result -Wwrite-strings -Wformat-security -fPIC -MD -MT qt/CMakeFiles/transmission-qt.dir/AddData.cc.o -MF qt/CMakeFiles/transmission-qt.dir/AddData.cc.o.d -o qt/CMakeFiles/transmission-qt.dir/AddData.cc.o -c /Users/runner/work/transmission/transmission/src/qt/AddData.cc
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:31:58: error: 'path' is unavailable: introduced in macOS 10.15
inline QString fromFilesystemPath(const std::filesystem::path &path)
                                                         ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:36:40: error: 'native' is unavailable: introduced in macOS 10.15
    return QString::fromStdString(path.native());
                                       ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:1193:22: note: 'native' has been explicitly marked unavailable here
  const string_type& native() const noexcept { return __pn_; }
                     ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:40:25: error: 'path' is unavailable: introduced in macOS 10.15
inline std::filesystem::path toFilesystemPath(const QString &path)
                        ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:42:29: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
                            ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:42:12: error: 'path<const char16_t *>' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:953:3: note: 'path<const char16_t *>' has been explicitly marked unavailable here
  path(_InputIt __first, _InputIt __last, format = format::auto_format) {
  ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:42:12: error: 'path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:953:3: note: 'path' has been explicitly marked unavailable here
  path(_InputIt __first, _InputIt __last, format = format::auto_format) {
  ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:42:12: error: '~path' is unavailable: introduced in macOS 10.15
    return std::filesystem::path(reinterpret_cast<const char16_t *>(path.cbegin()),
           ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:968:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:100:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemFileName() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:162:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemSymLinkTarget() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:167:29: error: 'path' is unavailable: introduced in macOS 10.15
    static std::filesystem::path filesystemSymLinkTarget(const T &fileName)
                            ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:101:14: error: '~path' is unavailable: introduced in macOS 10.15
    { return QtPrivate::toFilesystemPath(fileName()); }
             ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:968:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:8:
/usr/local/opt/qt/include/QtCore/qfile.h:164:16: error: '~path' is unavailable: introduced in macOS 10.15
        return QtPrivate::toFilesystemPath(symLinkTarget());
               ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:968:3: note: '~path' has been explicitly marked unavailable here
  ~path() = default;
  ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:81:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemFilePath() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:83:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemAbsoluteFilePath() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:85:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemCanonicalFilePath() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:99:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemPath() const { return QtPrivate::toFilesystemPath(path()); }
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:100:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemAbsolutePath() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:102:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemCanonicalPath() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
In file included from /Users/runner/work/transmission/transmission/src/qt/AddData.cc:6:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/QDir:1:
In file included from /usr/local/opt/qt/lib/QtCore.framework/Headers/qdir.h:9:
/usr/local/opt/qt/include/QtCore/qfileinfo.h:132:22: error: 'path' is unavailable: introduced in macOS 10.15
    std::filesystem::path filesystemSymLinkTarget() const
                     ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/filesystem:909:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
                       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

I think one way to go would be to try targeting 10.15 (instead of 10.14.6) and see if that works; the other would mean backpedalling and going back to Qt 5 and seeing if the [runner/compiling issue](https://github.com/transmission/transmission/pull/6203#issuecomment-1793276082) can be fixed.

**Comment by Coeur** [comment]
@fxcoudert @ckerr This change broke the macOS pipelines. Maybe revert it for now, and re-introduce it when you have a better solution?

**Comment by ckerr** [comment]
@Coeur just to make sure, your patch in 6214 fixed this, is that correct? e.g. is there any remaining action needed?

**Comment by Coeur** [comment]
my patch did fix it normally (but I'm no cmake expert, maybe Mike should double check)

**Pull request merged**
