### PR TITLE
macOS fix clipping and crashing on the Info Inspector Options tab

### LINKED ISSUE #3464: [macOS] Crash, v.3.00+ffe307ac1b, Torrent Inspector
[Crash Logs.zip](https://github.com/transmission/transmission/files/9130212/Crash.Logs.zip)

FR

Bildschirmfoto 2022-07-18 um 09 43 01

https://user-images.githubusercontent.com/62497891/179463932-60389d2a-88d4-4331-9c9d-ad7ee974cd0d.mp4

### LINKED ISSUE #3465: [macOS] UI-Torrent Inspector, v.3.00+ffe307ac1b
- Clipping

Bildschirmfoto 2022-07-18 um 09 15 16
Bildschirmfoto 2022-07-18 um 09 18 27
Bildschirmfoto 2022-07-18 um 09 19 04
Bildschirmfoto 2022-07-18 um 09 21 03
Bildschirmfoto 2022-07-18 um 09 13 59

### PR DESCRIPTION
**Pull request by sweetppro**
Fixes #3465.

Fixes #3464.

### CODE REVIEW

**Comment by sweetppro** [comment]
Fixes #3464

**Comment by Oleg-Chashko** [comment]
1. Not fixed:  #3465

Deutsch und Russisch.

Bildschirmfoto 2022-07-20 um 15 16 29

Bildschirmfoto 2022-07-20 um 15 25 15

**Comment by Oleg-Chashko** [comment]
> @oleg one issue would be easier for me to keep track of
> :)

I'm doing what's convenient for you: One Shot (issue), One Kill (fix).
 ;)

**Comment by ckerr** [comment]
I am confused on whether the second issue is going to be fixed in this PR or in a followup PR :dizzy: so LMK when this is OK to merge

**Comment by sweetppro** [comment]
@ckerr you can merge, I won’t get around to the other fixes till maybe tomorrow. And it would probably be good to merge now to fix the crashing

**Comment by Oleg-Chashko** [comment]
@sweetppro 
Did you fix it? 
Should I check it?
https://github.com/transmission/transmission/pull/3473#issuecomment-1190287997

**Comment by sweetppro** [comment]
> @sweetppro
> Did you fix it?
> Should I check it?
> [#3473 (comment)](https://github.com/transmission/transmission/pull/3473#issuecomment-1190287997)

I’ll fix that tonight or tomorrow. It’s 36degrees here in Berlin, I’m heading out for a swim 🙃

**Comment by Oleg-Chashko** [comment]
I came home from Düsseldorf to Essen today, but only bathed in the shower, we have a thunderstorm. 🙁

**Pull request merged**
