### PR TITLE
build: downgrade libdeflate to 1.7

### PR DESCRIPTION
**Pull request by abubaca4**
Transmission work with libdeflate 1.7 that delivered with debian 11

### CODE REVIEW

**Comment by ckerr** [comment]
This is a pretty straightforward PR but CC'ing @mikedld as an interested party

**Comment by GaryElshaw** [comment]
> This is a pretty straightforward PR but CC'ing @mikedld as an interested party

#4968 resolved the issue, no?

**Comment by ckerr** [comment]
> > This is a pretty straightforward PR but CC'ing @mikedld as an interested party
> 
> #4968 resolved the issue, no?

Sorry if I'm being slow but I don't understand what you're asking.

**Comment by GaryElshaw** [comment]
I thought Mike's pr had sorted out the issue the user was experiencing trying to get 1.7 built. The effect was that 1.7 was now set as a minimum requirement rather than later versions?

**Comment by ckerr** [comment]
Looks like 4968 fixed the problem of `DEFLATE_VERSION` not being used properly when set, and that 4970 lowers `DEFLATE_VERSION` to 1.7. They are related but `main` is currently requiring a version newer than 1.7

**Comment by ckerr** [comment]
@GaryElshaw an easy mistake to make tho 👍

**Pull request merged**
