### PR TITLE
Beautify README markdown formatting

### PR DESCRIPTION
**Pull request by VVVFO**

### CODE REVIEW

**Comment by mikedld** [comment]
Thanks, but I'm not sure how's this helping? Do you see it formatted differently somewhere? Because as long as file extension is not .md or something, GitHub will still treat it as plain text...

**Comment by VVVFO** [comment]
Sorry for not noticing that, but why not changing it to .md? It will make this repository page much more elegant.

**Comment by reelsense** [comment]
The improved legibility in proper markdown is nice.

**Comment by reelsense** [comment]
@VVVFO add the undiscovered typo referenced in issue #18 to your PR.  _**dependencies**_ not dependancies.

**Comment by mikedld** [comment]
Original repository doesn't even exist anymore, closing this in favour of #21.

**Pull request closed without merging**
