### PR TITLE
Update qt cmakelists to include support for building svg

### PR DESCRIPTION
**Pull request by GaryElshaw**
Also remove redundancy of line 59 from /dist/msi/cmakelists.txt

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Cheers @mikedld, over to you.

**Comment by GaryElshaw** [comment]
Apologies, i misunderstood. I'll do some digging.

**Comment by GaryElshaw** [comment]
@mikedld &#x2713;

**Review by mikedld — APPROVED** [review]
As mentioned elsewhere this will potentially break Linux and Windows builds on Jenkins, but I'll deal with it separately.

**Comment by GaryElshaw** [comment]
@mikedld I was wondering if that file needs to include an 'if this, then that' provision, because the same issue will be there for users whether they build with qt5 or qt6.

**Comment by ckerr** [comment]
I was going to merge this but from this comment

> As mentioned elsewhere this will potentially break Linux and Windows builds on Jenkins, but I'll deal with it separately.

I am wondering if me doing a drive-by merge would mess with something that @mikedld is working on wrt Jenkins, so I'll leave this alone & let Mike merge it when he's ready

**Comment by GaryElshaw** [comment]
A note about sequencing:

1. #4421 
2. #4437 
3. #4376

**Comment by mikedld** [comment]
Linux and Windows Jenkins jobs have been reconfigured to include Qt Svg module.

**Pull request merged**
