### PR TITLE
Set `"cache-size-mb": 0` to bypass write cache 

### PR DESCRIPTION
**Pull request by tearfur**
Idea and rationale from https://github.com/transmission/transmission/issues/5667#issuecomment-1606809431.

### CODE REVIEW

**Comment by tearfur** [comment]
My theory is this is probably only helpful to those whose filesystem has its own cache layer to group up transactions. Will have to wait for @blind-oracle's results since he has a filesystem with a cache layer.

Disabling the cache was trivial enough that I am confident it works. But I am not able to test it right now.

**Comment by blind-oracle** [comment]
I did the test - it seems to help, the speed was closer to 1Gbit/s most of time, but still I can't really go over that much (some 1.1Gbit/s max). The daemon hits 100% and there it stays.

Here's the graph, though it was taken with release flags and might be not very usable. But anyway it seems that the cache is now mostly no-op which is good.

trans

**Comment by tearfur** [comment]
@blind-oracle Nice. 20-30% improvement is a big improvement. But we better compare Debug build with Debug build to be fair.

When you say your CPU is at 100%, do you mean all cores, or just 1?

Looking at your other flame graphs, the other big part is the arc4 cipher. Can you generate another flame graph with encryption disabled? I want to identify the remaining parts that are eating up resources.

**Comment by blind-oracle** [comment]
@tearfur 

Sure, I can do debug, but it's very slow there. I'll try.

When I say 100% I mean one core. I don't think that transmission can effectively use several cores... at least I never saw >100% cpu usage.

**Comment by tearfur** [comment]
> When I say 100% I mean one core. I don't think that transmission can effectively use several cores... at least I never saw >100% cpu usage.

Yeah Transmission is mostly single threaded.

> About encryption - I don't think you can disable it, at least the lowest level for it is `Tolarable`. Hard to say what this means, probably it won't initiate encrypted sessions, but would accept ones?

Sure, just set it to `Tolerable` to get rid of as much arc4 CPU time as possible.

**Comment by blind-oracle** [comment]
> Yeah Transmission is mostly single threaded.

Which is sad, a thread-per-torrent would be quite efficient I guess, they don't really need to share any state.

Here's the graph for debug build & tolerated encryption.
For debug build disabling the cache is visible most significantly - speed went up from 4-5MB/s to 20-30MB/s.

ARC4 is still there, but only around 5% of samples.
trans_debug

**Comment by ckerr** [comment]
commented @ https://github.com/transmission/transmission/issues/5667#issuecomment-1607989536

**Comment by blind-oracle** [comment]
@ckerr these particular graphs were made by `flamegraph-rs` since hotspot is Linux-only GUI and I don't really have any Linux desktop around...

**Comment by ckerr** [comment]
@blind-oracle TIL about flamegraph-rs, thanks for the info! That is really handy

**Comment by tearfur** [comment]
> Just as a side thought, it's _very_ cool that hotspot exports flame graphs svgs that include mouseover text for each slice. That is super useful

I agree, they have been very useful. 😁

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: Setting `"cache-size-mb": 0` in `settings.json` now disables the disk write cache.

**Pull request merged**
