### PR TITLE
chore: bump libutp

### PR DESCRIPTION
**Pull request by tearfur**

### CODE REVIEW

**Comment by ckerr** [comment]
Oog.

I've put this moment off because I shipping forked libutp code is conceptually a little scary but I guess I should've thought of that before writing the patches :joy_cat:

**Review by ckerr — DISMISSED** [review]

**Comment by ckerr** [comment]
I'm confused why `--std=c++17` isn't being passed along to the libutp CMakeLists.txt when we're building. Our libutp CMake currently sets the std to c++17 **iff** it's a standalone build and if `CMAKE_CXX_STANDARD` isn't already set.

Though maybe the simplest fix is just to unconditionally set `CMAKE_C_STANDARD` and `CMAKE_CXX_STANDARD` in `libutp/CMakeLists.txt`. Anyone see any downside to that approach?

--- 

```
[41/588] Building CXX object third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o
FAILED: third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o 
/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPOSIX -I/Users/runner/work/transmission/transmission/src/third-party/libutp/include/libutp -I/Users/runner/work/transmission/transmission/src/third-party/libutp/include -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.14.6 -MD -MT third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o -MF third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o.d -o third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o -c /Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.cpp
In file included from /Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.cpp:36:
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:65:15: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
        RST_Info() = default;
                     ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:69:3: error: expected member name or ';' after declaration specifiers
                , connid{ _connid }
                ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:68:9: error: expected '('
                : addr{ _addr }
                      ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:68:16: error: expected ';' after expression
                : addr{ _addr }
                             ^
                             ;
```

**Comment by ckerr** [comment]
I'm confused why `--std=c++17` isn't being passed along to the libutp CMakeLists.txt when we're building. Our libutp CMake currently sets the std to c++17 **iff** it's a standalone build and if `CMAKE_CXX_STANDARD` isn't already set.

Though maybe the simplest fix is just to unconditionally set `CMAKE_C_STANDARD` and `CMAKE_CXX_STANDARD` in `libutp/CMakeLists.txt`. Anyone see any downside to that approach?

--- 

```
[41/588] Building CXX object third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o
FAILED: third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o 
/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DPOSIX -I/Users/runner/work/transmission/transmission/src/third-party/libutp/include/libutp -I/Users/runner/work/transmission/transmission/src/third-party/libutp/include -O2 -g -DNDEBUG -arch x86_64 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=10.14.6 -MD -MT third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o -MF third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o.d -o third-party/libutp.bld/CMakeFiles/libutp.dir/utp_internal.cpp.o -c /Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.cpp
In file included from /Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.cpp:36:
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:65:15: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
        RST_Info() = default;
                     ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:69:3: error: expected member name or ';' after declaration specifiers
                , connid{ _connid }
                ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:68:9: error: expected '('
                : addr{ _addr }
                      ^
/Users/runner/work/transmission/transmission/src/third-party/libutp/utp_internal.h:68:16: error: expected ';' after expression
                : addr{ _addr }
                             ^
                             ;
```

**Comment by nevack** [comment]
@ckerr at least for mac builds there were some preparations in advance https://github.com/transmission/transmission/pull/6242
I can look into this breakage

**Comment by ckerr** [comment]
> Is it known behavior of CMake not to inherit/share values between included and including project?

I thought CMake did inherit but @mikedld understands the ins & outs of our CMake much better than I do

**Comment by mikedld** [comment]
`CMAKE_CXX_STANDARD` is set (line 604) *after* libutp subdirectory is added (line 518), that's why it doesn't have any effect.

**Comment by mikedld** [comment]
> Though maybe the simplest fix is just to unconditionally set `CMAKE_C_STANDARD` and `CMAKE_CXX_STANDARD` in `libutp/CMakeLists.txt`. Anyone see any downside to that approach?

I'm slightly concerned with compiling different parts of code using different standards. OTOH, maybe we shouldn't be setting `CMAKE_*_STANDARD` variables at all and setting [compile features](https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html) (e.g. `cxx_std_17`) on targets instead which should allow CMake to reconcile potential issues or at least control the requirements more precisely.

**Comment by ckerr** [comment]
Anyone opposed to this?

**Comment by mikedld** [comment]
Not unless it breaks things :-P I didn't review transmission/libutp#13 and can't be confident, so will leave it to others :))

**Comment by tearfur** [comment]
LGTM.

**Review by Coeur — APPROVED** [review]
I haven't reviewed it, but I tested it with no apparent regressions on my end.

**Comment by ckerr** [comment]
> Not unless it breaks things :-P I didn't review [transmission/libutp#13](https://github.com/transmission/libutp/pull/13) and can't be confident, so will leave it to others :))

I did @ you in the PR when it went up a couple weeks ago :smile_cat: 

But yes, even though I wrote the PRs I agree this is kind of a "not unless it breaks things" since there's not a good way to test libutp changes before going into production, so the nightly builds after this lands will be important.

Also -- since upstream libutp seems to be abandoned, @mikedld @tearfur do y'all have opinions on how we should handle our diffs? e.g. should the use-std-tools PRs be moved into `main` as well? And even though upstream seems to be abandoned, should I make PRs there as a good-faith effort to keep the repos in sync?

**Pull request merged**
