### PR TITLE
Fix TR_ASSERT equality

### PR DESCRIPTION
**Pull request by Coeur**
Fix regression from #3849.

### CODE REVIEW

**Comment by Coeur** [comment]
But it's not enough. I still get a crash on launch. :(

**Review by ckerr — APPROVED** [review]

**Comment by GaryElshaw** [comment]
I'm still seeing a crash on quit :-(

[crash-on-quit.txt](https://github.com/transmission/transmission/files/9689328/crash-on-quit.txt)

**Comment by Coeur** [comment]
@GaryElshaw I clearly listed on my latest GitHub issue that there were multiple different causes. The one you faced is #3776

**Comment by GaryElshaw** [comment]
Sure thing. It's a little tough keeping track of which targets at the moment.

**Pull request merged**
