### PR TITLE
feat: add "Open URL" toolbar button to transmission-gtk.

### PR DESCRIPTION
**Pull request by J08nY**
This PR adds a toolbar button to transmission-gtk for opening a torrent from a URL. 

**Rationale:**
For what anecdotes are worth, from my personal usage of transmission, I have added a torrent from a magnet URL much more times than I have added one from a file, thus having a toolbar button to do that seems nice.

### CODE REVIEW

**Comment by Coeur** [comment]
@J08nY 
"This branch has conflicts that must be resolved"

**Comment by mikedld** [comment]
@J08nY, GTK client code has changed a bit since 2019, sorry for not getting to this PR earlier. Would you be willing to rebase your changes on top of current `main`?

**Comment by J08nY** [comment]
So I really don't care for this anymore and do not have time to implement it. Either someone else ports the changes or this can be closed.

**Comment by mikedld** [comment]
@J08nY, thank you for getting back.

**Comment by ckerr** [comment]
Closing due to lack of update.

Anyone who would like to add this feature, please feel free to open a new PR.

**Pull request closed without merging**
