### PR TITLE
configure anti brute force

### PR DESCRIPTION
**Pull request by Chrool**
related to issue #1415

### CODE REVIEW

**Comment by heliostatic** [comment]
This would be a great PR to merge since there's no recourse right now except restarting the daemon or disabling rpc completely.

**Comment by ckerr** [comment]
Code style CI failure is unrelated:

```
ENOSPC: no space left on device
```

**Comment by antivirtel** [comment]
Hi, great news it has been added, thanks. However I can't seem to find the new options in the docs: https://github.com/transmission/transmission/blob/main/docs/Configuration-Files.md - can that be added too? Should end up in `man` pages if possible too. Thank you!

**Comment by ludwigvdb** [comment]
Hi,

"anti-brute-force-enabled": false,
"anti-brute-force-threshold": 100,

I've stop transmission daemon, put these two lines in my configuration file and restart transmission but still get the message randomly : 

403: Forbidden
Too many unsuccessful attempts. Please restart transmission-daemon

I'm running transmission on docker container if that's important

What could possibly other than anti brute force create that message ?

**Comment by spacecowboy** [comment]
When is this fix going to be included in a release? My daemon is locking me out constantly. Going to put in a force-restart timer in systemd meanwhile

**Comment by ckerr** [comment]
in 4.0.0-beta.1. There are still a few items left on the milestone but we're getting close.

**Pull request merged**
