### PR TITLE
feat: update web client's icons

### PR DESCRIPTION
**Pull request by GaryElshaw**
A starter on making the icons in the web interface consistent in style. Quite possibly just something i will use for myself, but thought others in the community might like too. Zero code changes as yet, a work in progress, but feedback is always welcome.

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
I don't understand why there are some new files that don't replace old files, but no corresponding code or css changes. Are the new icons used anywhere? If not, why are they here?

**Comment by GaryElshaw** [comment]
> I don't understand why there are some new files that don't replace old files, but no corresponding code or css changes. Are the new icons used anywhere? If not, why are they here?

This is a draft, but it does make the icons a consistent theme. There are multiple different styles in the current icon set. Happy to close if no one wants it or is interested.

I made a QT/GTK theme over the weekend for Transmission after getting frustrated with Faenza if you feel like a change?

**Comment by ckerr** [comment]
I'm not sure how far I want to take this idea of having consistent icons for things like locks and gears between platforms. The entire reason that we keep three different codebases between GTK, Qt, and macOS -- and this is a _lot_ of work -- is for the app to seem as native as possible. Having icons that don't match the target desktop works against that.

**Comment by GaryElshaw** [comment]
I was meaning the icons within the web client are currently not consistent. I'll close those GTK and QT PR's

**Review by ckerr — CHANGES_REQUESTED** [review]
Please update `web/assets/img/README.md` with info about the sourcing and licensing of these new icons. This PR leaves the old icons' information in place, which is inaccurate since the icons have changed.

For example, `files.svg` is changed to a different icon but it's still isted as coming from bootstrap and having an MIT license.

**Review by ckerr — COMMENTED** [review]
There appear to be competing icons, e.g. chevron-down.svg vs chevron-down.png.

When a foo.svg is availble, please use it exclusively and remove the foo.png sibling

**Comment by GaryElshaw** [comment]
I'm not going to contribute anything anymore Charles. I've had enough of being made to feel like i'm second-rate when other contributors are not treated remotely this way. In fact, they're often thanked. Being asked to offer legal analysis when the project, if it is in breach, has been for years, is just demeaning.

**Comment by ckerr** [comment]
@GaryElshaw it is completely reasonable to ask for information that confirms that the assets being submitted can be used legally.  That is the same standard that I used for myself with the web client refresh and that can be seen in `web/assets/img/README.md` which documents the source and license of each new icon.

As for "other contributors are not treated remotely this way"... I feel that you are incorrectly reading things as personal attacks, e.g. when mikedld marked one of your bug reports as 'invalid', you were hostile to him and said it was an ad hominem attack. When I put you in timeout for hostility, I made sure to couch it in terms of I-value-your-presence-on-the-project-but... so that you wouldn't see it as an attack. Even so  you closed all your PRs for the duration of the timeout. And now you are doing the same thing again, less than a week later, because I've asked you for licensing information of the assets in your PR, which is the same standard that I set for myself.

I'll try this one last time: I value your presence on the project. I do not believe that I'm treating you differently than other contributors. I *have* thanked you for your help. Even now, your contributions would still be welcomed. But for fuck's sake,  put the drama away.

**Comment by GaryElshaw** [comment]
I was actually referring to the discussion in 'lock' when i talked about the legality of the icons, not this PR. Why is there one standard for one contributor to check the legality of a single icon, but zero concern for an entire UI, or another contributor's version of the very same icon concurrently being coded?

Yes, i do take it personally when one or more contributions are seemingly merged with next to no oversight, but there always seems to be a multitude of reasons why mine seemingly can't be. Or i work on something and another contributor makes their own version and i have to cancel mine for theirs. That's happened twice in the last two to three weeks.

The thing with Mike was about me being annoyed that he seemed to be annoyed that i wasn't psychic that he obviously knew about the new version. How foolish of me to just give him a heads up. But then to say this? Well.. "And again, as with other issues you report, please provide reasoning for why you think it's an issue in the first place." That's patronising AF and i thought that was ad hominem, a character sleight. And then he said TC had nothing to do with Transmission, so i responded with sarcasm, not hostility.

I closed the PR's *because* i was in Github jail. If you had merged them without me being able to amend anything, because i was locked out, that would be very bad, no?

I'm closing them now because it feels like i'm emphatically being told not to contribute. So i won't. I'm 52 this year. Apple has distributed software i wrote as part of their OS in years past. I've been a mac user since 1984/5. I've developed a tablet application that is in 100's of primary schools in Cambodia. I've managed multi-million dollar website projects and others that cost $200. I've spoken at international symposiums on UX. Here in this forum? I feel like a no-nothing noob.

**Review by ckerr — COMMENTED** [review]
If any of these icons are derived from the Apple SF Icon set, they need to be removed. Apple licensing only makes these available for use on their intended systems, e.g. macOS / iOS

**Comment by GaryElshaw** [comment]
> If any of these icons are derived from the Apple SF Icon set, they need to be removed. Apple licensing only makes these available for use on their intended systems, e.g. macOS / iOS

They are only used on the MacOS client.

**Pull request closed without merging**
