### PR TITLE
macOS: disable App Nap. Fixes #577

### LINKED ISSUE #577: [macOS] Task doesn't start until Transmission window is on foreground
I always add magnet links to Transmission via the remote interface on my local network. I don't have any auth set up or IP restrictions. To add the torrents I use the [Remote Torrent Adder](https://chrome.google.com/webstore/detail/remote-torrent-adder/oabphaconndgibllomdcjbfdghcmenci) extension.

When I add a magnet link, the task appears in Transmission without any issues. However, even though I have it configured to start tasks right away, I see in the web interface it stays fetching metadata (magnet/red state).

It's only when I VNC into my download server (a mac mini running macOs 10.13.2 and Transmission 2.92/14714) and bring the Transmission window to the foreground, it starts downloading.

In the attached logs you can see how the task was added at 18:15, but did not start until 19:12.

Please let me know if there's anything I can do to help debug this.
Thanks!

[transmission.txt](https://github.com/transmission/transmission/files/1891456/transmission.txt)

### PR DESCRIPTION
**Pull request by wiz78**
Prevent App Nap when the main window is closed or the desktop is blocked, in order to avoid the web interface getting stuck in the “Verifying local data” phase

Fixes #577

### CODE REVIEW

**Comment by wiz78** [comment]
any reason why this can't be merged?

**Comment by jqdg** [comment]
It would be great it this could be merged. I had to disable App Nap systemwide because otherwise using the web interface remotely is hardly usable --- torrents don't start downloading properly when the app is put in App Nap.

I merged the latest master into this branch and built locally and it seemed to work fine.

**Comment by wiz78** [comment]
@livings124 are you able to merge this one? (I'm asking you just because I've seen you merging other macOS related patches recently :-)

**Comment by RobFog** [comment]
@livings124 Is this not necessary for Transmission to function properly on macOS?

**Comment by wiz78** [comment]
I resolved a conflict for the last time. Since I no longer need this, I won't be spending more time on it, sorry

**Comment by Coeur** [comment]
I just searched for what is App Nap, clicked on the first article about it:
https://www.macplanete.com/astuces/22289/app-nap-mac-desactiver
And their screenshot uses two apps for their example: Mail and Transmission. 😁

**Review by Coeur — APPROVED** [review]
I've read the doc: https://developer.apple.com/library/archive/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/AppNap.html
I've tested it.
Seems a valid change.
Approved for merging. There is a clang-format warning, but easily fixable by the merger.
@ckerr

**Comment by andycarver101** [comment]
> Prevent App Nap when the main window is closed or the desktop is blocked, in order to avoid the web interface getting stuck in the “Verifying local data” phase
> 
> Fixes #577

2012 Mac Pro. App nap is not supported. I don’t think this is an issue any more as I cannot reproduce.

**Comment by Coeur** [comment]
@andycarver101 
Before this fix, if you reach zero peers, and wait 30 sec with the window minimised, you'll enter App Nap on macOS Monterey:
Capture d’écran 2022-05-14 à 16 14 06

The issue being that you can't wake up from App Nap even if the tracker gives you new peers, until you manually re-open the Transmission window.

**Pull request merged**
