### PR TITLE
fix: magnet link regression

### LINKED ISSUE #2357: commit #2345 broke Magnet links
All builds since commit #2345 cannot add torrents via Magnet links. 

Edit: 
To be a bit more clear: from the Jenkins builds, 7477 works fine, 7478 onwards cannot add via Magnet links.

### PR DESCRIPTION
**Pull request by ckerr**
fixes #2357.

### CODE REVIEW

**Comment by GScottElshaw** [comment]
Thanks for all your work and effort Charles.

**Comment by GScottElshaw** [comment]
Usually instantaneous, the build isn't appearing :-( https://build.transmissionbt.com/job/trunk-mac/

**Comment by mikedld** [comment]
https://github.blog/2021-09-01-improving-git-protocol-security-github/

> Date | What happens
> -- | --
> January 11, 2022 | Final brownout. This is the full brownout period where we’ll temporarily stop  accepting the deprecated key and signature types, ciphers, and MACs, and  the unencrypted Git protocol. This will help clients discover any  lingering use of older keys or old URLs.

Fixing now...

**Comment by GScottElshaw** [comment]
@mikedld Working again now, thanks Mike.

**Comment by GScottElshaw** [comment]
Okay, a couple of things with this commit. 

1. The linking works again - thanks @ckerr 
2.  The tracker field in the inspector is blank after adding a magnet link after download begins
3. Neither pausing, resuming, or restarting, changes the ability to examine, add or remove trackers.

**Comment by sweetppro** [comment]
> Okay, a couple of things with this commit.
> 
> 1. The linking works again - thanks @ckerr
> 2. The tracker field in the inspector is blank after adding a magnet link after download begins
> 3. Neither pausing, resuming, or restarting, changes the ability to examine, add or remove trackers.
> 4. It seems to effect all files. All seeds have zero trackers visible in the inspector panel.

Im not seeing this on macOS Monterey, but magnet links always pause after meta data has downloaded

**Comment by GScottElshaw** [comment]
> > Okay, a couple of things with this commit.
> > 
> > 1. The linking works again - thanks @ckerr
> > 2. The tracker field in the inspector is blank after adding a magnet link after download begins
> > 3. Neither pausing, resuming, or restarting, changes the ability to examine, add or remove trackers.
> > 4. It seems to effect all files. All seeds have zero trackers visible in the inspector panel.
> 
> Im not seeing this on macOS Monterey, but magnet links always pause after meta data has downloaded

Interesting. There is no pause on Big Sur.

**Comment by GScottElshaw** [comment]
Something i just noticed. This peer has exactly the same ratio as I do, but the display suggests they have 100% of the torrent.

Screenshot 2022-01-13 at 6 03 18 PM
.

**Pull request merged**
