### PR TITLE
feat: accept "interval" and "min interval" in scrape responses (#6934)

### LINKED ISSUE #6934: "interval" and "min interval" are valid scrape keys
### What is the issue?

Currently only `min_request_interval` is accepted during a scrape response.  There is no mention of any interval key in any BEP, though many trackers return some value.  Most clients accept and many trackers use variants such as `interval` and `min interval`, which should be accepted in `tr_announcerParseHttpScrapeResponse`

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

Tr4 mainline, possibly 4.0.x

### PR DESCRIPTION
**Pull request by bheesham**
Fixes #6934

### CODE REVIEW

**Review by Coeur — APPROVED** [review]

**Review by tearfur — APPROVED** [review]
Please add `Fixes #6934` to the PR description.

**Comment by bheesham** [comment]
Would I be able to ask y'all to also review https://github.com/transmission/transmission.github.io/pull/96 ?

**Comment by reardonia** [comment]
1) Note that `TR_KEY_min_request_interval` exists in the quark set, but is not used anywhere in the code.  There are no `TR_KEY_interval` or `TR_KEY_min_interval` quarks.  So perhaps you should also remove the quark as part of this.

2) Note that libtorrent-rb respects "interval" and "min interval" for scrape keys, so we might want to mark this as a client compatibility fix.  However, there is no BEP that covers this.  

3) Transmission has supported "min_request_interval" since 2006 but I can't find a BEP or any doc anywhere which describes it.

**Comment by bheesham** [comment]
@reardonia I like your PR more, so I'm closing this one off.

fwiw: please feel free to close my PRs if they're ever obsolete. Less burden on y'all. :)

**Comment by bheesham** [comment]
@Coeur , would you be able to swap this issue in https://github.com/transmission/transmission/issues/6952 ?

**Pull request closed without merging**
