### PR TITLE
refactor: use C++ objects in announcer

### PR DESCRIPTION
**Pull request by ckerr**
use std:: containers for the data structures in the announcer module.

### CODE REVIEW

**Comment by GScottElshaw** [comment]
Night and Day. I was seeding to a client at a max speed of around 50k/s, downloaded the new build, and? 750k/s.

**Comment by Pentaphon** [comment]
> Night and Day. I was seeding to a client at a max speed of around 50k/s, downloaded the new build, and? 750k/s.

Interesting! I can't wait for see the difference when they push out a new release! I'm glad this client is finally getting the optimizations and modernization it deserves.

**Comment by RobFog** [comment]
> Night and Day. I was seeding to a client at a max speed of around 50k/s, downloaded the new build, and? 750k/s.

Correlation or causation? 😛

**Comment by ckerr** [comment]
> Correlation or causation? stuck_out_tongue

That's my guess. I'm happy that it's going well, but I wouldn't've expected this PR to have a huge difference. Still, I'm not going to complain. :smile_cat:

**Pull request merged**
