### PR TITLE
Fixed crash on exit in tr_utpPacket

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by ckerr** [comment]
@Coeur which issue is this for -- is there a backtrace for this crash?

**Comment by Coeur** [comment]
It was happening on exit: utp_context was NULL, crash was on the first `assert(ctx)` of utp_process_udp. I tried to remove that assert, and then it crashed on the first `assert(ctx)` of utp_issue_deferred_acks. So instead of removing two asserts, I just avoid calling tr_utpPacket with a NULL context.

**Comment by Coeur** [comment]
```
Thread 6
#0	0x0000000184878374 in __abort ()
#1	0x00000001848782d4 in abort ()
#2	0x0000000184877620 in __assert_rtn ()
#3	0x0000000100e802a0 in ::utp_process_udp(utp_context *, const byte *, size_t, const sockaddr *, socklen_t) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2817
#4	0x0000000100be04dc in tr_utpPacket(unsigned char const*, unsigned long, sockaddr const*, unsigned int, tr_session*) at /Users/User/Developer/transmission/libtransmission/tr-utp.cc:234
#5	0x0000000100bd05c8 in event_callback(int, short, void*) at /Users/User/Developer/transmission/libtransmission/tr-udp.cc:219
#6	0x0000000100dd750c in event_persist_closure at /Users/User/Developer/transmission/third-party/libevent/event.c:1623
#7	0x0000000100dd4b98 in event_process_active_single_queue at /Users/User/Developer/transmission/third-party/libevent/event.c:1682
#8	0x0000000100dc2f8c in event_process_active at /Users/User/Developer/transmission/third-party/libevent/event.c:1783
#9	0x0000000100dbf2e0 in event_base_loop at /Users/User/Developer/transmission/third-party/libevent/event.c:2006
#10	0x000000010076e3bc in tr_session_thread_impl::sessionThreadFunc(event_base*) at /Users/User/Developer/transmission/libtransmission/session-thread.cc:244
#11	0x0000000100773fc8 in decltype(*(static_cast<tr_session_thread_impl*>(fp0)).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/type_traits:3859
#12	0x0000000100773e68 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/thread:287
#13	0x0000000100772ac4 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr/include/c++/v1/thread:298
#14	0x0000000101ff55d4 in _pthread_start ()
```
Capture d’écran 2022-12-13 à 22 51 00

**Comment by ckerr** [comment]
Notes: Fixed `4.0.0-beta.2` crash on shutdown

**Pull request merged**
