### PR TITLE
style: dock badge colours follow Apple a11y colour guide

### LINKED ISSUE #4800: Please restore the old Dock icon bandwith colours
### What is the issue?

Especially the new upload speed background colour is too light. It makes the speed difficult to read.

Please restore the old colours or choose colours with better contrast. 

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.0 (280ace12f8)

### PR DESCRIPTION
**Pull request by GaryElshaw**
Fixes #4800 (hopefully)

Zero code changes, just an image swap. Image credit to @sweetppro.

cc: @livings124 

Current

SCR-20221031-nt8

PR

SCR-20230211-m6t

Notes: Changed dock icon badge colours to Apple accessibility guideline recommendations, but retains code styling.

### CODE REVIEW

**Comment by sweetppro** [comment]
are there any before after screenshots?

**Comment by GaryElshaw** [comment]
> Im not a fan of the gradients...

Me either, it makes Transmission look dated and stuck in the aqua age. I'll see what i can do..

**Comment by robd003** [comment]
Any chance we could have the color change as a user preference? I prefer the bright colors since I'm using the dark macOS theme.

**Comment by Coeur** [comment]
Thank you for the PR, Gary, but as a sensitive UI element, we better have light colors for dark mode and dark colors for light mode. Either two sets of images, or generating those dynamically.

**Comment by GaryElshaw** [comment]
> Either two sets of images, or generating those dynamically.

Cheers Antoine. After some consideration, i don't think the dock icon needs to be themed or part of the scheme for Dark and Light modes, it's kinda irrelevant (and i'm scratching my head to even think of an application that changes its dock icon colour profile for dark and light modes. Anyone?). 

I think the body of the application is where the focus of whatever resource is available should go.

**Comment by Coeur** [comment]
You're right, I've double checked, all my apps have the same icons in Dark and Light mode, as well as the same badge colors in both modes.

So we need good average values that work just as well for both situations.

**Comment by GaryElshaw** [comment]
Something in-between and Apple-compliant?

https://github.com/transmission/transmission/issues/4800#issuecomment-1426586782

**Comment by mangosplat** [comment]
This would be a great chance to re-do these programatically

Also, not sure what's going on with the edges here

IMG_0793
IMG_0791

**Comment by ckerr** [comment]
> This would be a great chance to re-do these programatically

Agree in the abstract but not for a patch release, please. When in doubt on a patch release, choose the path that's least intrusive.

> Also, not sure what's going on with the edges here

Agreed; those are some jagged pixels

**Comment by ckerr** [comment]
> This would be a great chance to re-do these programatically

Agree in the abstract but not for a patch release, please. When choosing between two changes for a patch release, choose the one with less risk.

> Also, not sure what's going on with the edges here

Agreed; those are some jagged pixels

**Comment by Coeur** [comment]
> Something in-between and Apple-compliant?
> 
> [#4800 (comment)](https://github.com/transmission/transmission/issues/4800#issuecomment-1426586782)

Yes, looks good to me.

So if we go with those colors and fix the "edges" as mentioned by mangosplat, it would be good for Transmission 4.0.1.

**Comment by sweetppro** [comment]
> Also, not sure what's going on with the edges here

@mangosplat & @Coeur this is why I uploaded some png's in the other thread....
here they are again:
218235047-d245fd19-952e-4941-bf99-ab687aca3419
218235044-6723c792-9090-42f8-ba61-efd0ddb9e620
218234645-df991c91-1a0c-4b0d-98e6-c4b42937cb0f
218234650-fe0382a4-ac92-4f87-92ed-afe9f40de9a9
218234653-b93061d9-17fa-457b-8bce-aa4da7bec0b7
218234654-b990e074-51e1-4adb-8bce-79bae31e53f5

**Comment by ckerr** [comment]
> Merge branch 'main' into macos-badge

@GaryElshaw being up-to-date with the base branch is not the blocker right now and Sanity CI has been *hammered* today :smile: please hold off updates until the macOS reviewers have chimed in on this PR :heart:

**Review by Coeur — APPROVED** [review]
Capture d’écran 2023-02-12 à 11 52 21

**Comment by Coeur** [comment]
@ckerr I'm removing "needs UI review" since it was reviewed by me and the png are from sweetppro.

**Pull request merged**
