### PR TITLE
GTK icon for the system tray

### PR DESCRIPTION
**Pull request by GaryElshaw**
An svg icon for the GTK tray #3312

### CODE REVIEW

**Comment by nevack** [comment]
Seriously, I oppose using macOS icon for GTK client.
Current GTK Icon matches other Gnome Apps Icons perfectly.

**Comment by GaryElshaw** [comment]
> Seriously, I oppose using macOS icon for GTK client. Current GTK Icon matches other Gnome Apps Icons perfectly.

I'm not sure i understand. All of the branding was unified some time ago, GTK, QT, and Web included. The GTK icon was updated some time ago with the PR i referenced, this PR just changes the hicolor icon in line with QT and all of the other platforms.

I'm trying to accomplish two separate things with this PR.

1. An icon for the GTK tray that fits with the other icons the user illustrated and requested in #3312 (this icon is derived from and replaces hicolor_apps_symbolic_transmission-symbolic.svg by unifying the white with transparency so that it hopefully plays nicely with other themes.
2. Keeping the branding cohesive across platforms hicolor_apps_scalable_transmission.svg

**Comment by ckerr** [comment]
TBH I'm leaning more towards @nevack's point of view here about having GNOMEish icons for the GTK client. I kind of regret merging #3129 and its Qt counterpart because the new macOS icon, though great on macOS, is not designed for GNOME and so it naturally doesn't follow the  [GNOME App Icon Style](https://developer.gnome.org/hig/guidelines/app-icons.html).

When I look at all the icons at https://www.omgubuntu.co.uk/best-icon-themes-ubuntu ... even though Papirus, Numix, Qogir et al are different themes, they all do have a similar feel that follow the GNOME App Icon Style. The new icon doesn't. For that reason I'm leaning towards closing this and reverting 3129.

@GaryElshaw I know that icons are important to you though so for your consideration -- Ideally the project would have some "reference" look that could be adjusted slightly to match the style guides of different OSes. Consider how the Chrome icon is "shiny" on macOS and has a simpler look on GNOME, but it's always easily distinguished as the same icon. I'm not a graphic designer but If we could do that with Transmission, it would be great.

**Comment by GaryElshaw** [comment]
I still think it was the right decision, and i disagree with @nevack, because as we discussed, i think the macOS icon fits in very neatly with the current GTK iconography. https://github.com/transmission/transmission/issues/3119#issuecomment-1135349605

However, happy to redo this so that it is only the tray icon being PR'ed.

**Comment by ckerr** [comment]
> I still think it was the right decision, and i disagree with @nevack

I may be misreading things here -- it's very easy to misread intent from text in online forums, so sorry if I'm getting this wrong -- but this feels like it's leading towards a framing of one person being right and another being wrong. IMO that's not a productive way for this conversation to go and this is less about the people involved than about the icons.

So to the question of which icon is more GNOMEish. Here I'm looking at [A](https://raw.githubusercontent.com/transmission/transmission/79cd776f37cc33befaee7586219c9dbf87beb88c/gtk/transmission.png) and [B](https://raw.githubusercontent.com/transmission/transmission/a79a40ee8ae7b2435eaf0bfb1a493cfeb6ced178/gtk/transmission.png) from https://github.com/transmission/transmission/pull/3129/files . A has a flatter, matte look and is angular. B is shinier and curved. For these reasons A seems to follow the guidelines at https://developer.gnome.org/hig/guidelines/app-icons.html#gnome-app-icon-style more closely.

**Comment by nevack** [comment]
> i disagree with @nevack

It's up to Lead devs to decide, I just wanted to share my opinion.

> i think the macOS icon fits in very neatly with the current GTK iconography.

I don't think so.

I'm fan of GNOME and GTK itself, I use this DE and many GTK apps daily on my work machine.
I'm also fan of macOS, and my personal machine is MacBook.

Both GNOME and macOS have great UIs, and the major point of this is being consistent for user.
Making GTK app a macOS-lookalike is not the way for having great Linux app being consistent with the rest of the platform.

I would understand having the same icon across platforms if Transmission was built with Cross-platform UI framework, like qBittorrent being built with Qt.
But even qBittorrent has different icon on macOS and on other platforms.

The existing Transmission icon for GTK is really great and I don't see how replacing it with macOS icon will do any good impact on users

**Comment by nevack** [comment]
> Maybe we should have a greyscale version of https://raw.githubusercontent.com/transmission/transmission/79cd776f37cc33befaee7586219c9dbf87beb88c/gtk/transmission.png here?

I don't think so.

Tray icons are more like 1/0 alpha channel and distinct contours, example:
image

**Comment by nevack** [comment]
> @nevack Could you please try a build with the icon and post a shot?

image

**Comment by GaryElshaw** [comment]
> image

Interesting. That's with the proposed tray icon in place?

**Comment by nevack** [comment]
@GaryElshaw 
1) My patch here works https://github.com/transmission/transmission/issues/3312#issuecomment-1164816929
2) As I said here https://github.com/transmission/transmission/pull/3339#issuecomment-1165316501 prefix is important.
    So this patch also works also:
```diff
diff --git a/gtk/CMakeLists.txt b/gtk/CMakeLists.txt
index 7c7e72893..f08cc74ca 100644
--- a/gtk/CMakeLists.txt
+++ b/gtk/CMakeLists.txt
@@ -39,10 +39,10 @@ add_custom_command(
         --c-name transmission
         transmission.gresource.xml
     DEPENDS
+        icons/hicolor_apps_scalable_transmission-tray-icon.svg
         icons/hicolor_apps_scalable_transmission.svg
         icons/lock.png
         icons/ratio.png
-        icons/transmission-tray-icon.svg
         icons/turtle-blue.png
         icons/turtle-grey.png
         icons/utilities.png
@@ -194,6 +194,7 @@ endif()
 install(TARGETS ${TR_NAME}-gtk DESTINATION ${CMAKE_INSTALL_BINDIR})
 
 set(${PROJECT_NAME}_PUBLIC_ICONS
+    hicolor_apps_scalable_transmission-tray-icon.svg
     hicolor_apps_scalable_transmission.svg
     hicolor_apps_scalable_transmission-devel.svg
     hicolor_apps_symbolic_transmission-symbolic.svg
diff --git a/gtk/icons/transmission-tray-icon.svg b/gtk/icons/hicolor_apps_scalable_transmission-tray-icon.svg
similarity index 100%
rename from gtk/icons/transmission-tray-icon.svg
rename to gtk/icons/hicolor_apps_scalable_transmission-tray-icon.svg
```

**Comment by nevack** [comment]
> > image
> 
> Interesting. That's with the proposed tray icon in place?

I have build the package from this PR, so yes.

**Comment by GaryElshaw** [comment]
It's not building correctly, that's not the proposed tray icon, i'll try and find a fix :-(

**Comment by nevack** [comment]
> It's not building correctly, that's not the proposed tray icon, i'll try and find a fix :-(
> 
> Have you tried with the naming convention i proposed?

I have built directly from your PR. Your patch doesn't work.
Both my patches work.

See:
image

**Comment by GaryElshaw** [comment]
I don't understand, this is the proposed tray icon.

tray

**Comment by nevack** [comment]
> I don't understand, this is the proposed tray icon.
> 
> tray

It's the result of my patches. 

Here is the screenshot from your PR:
image

**Comment by GaryElshaw** [comment]
Now i understand. Thank you.

**Comment by GaryElshaw** [comment]
@nevack Could you please take a look at why these sanity checks are failing, i can't see what the problem might be. The complaints about the CMakeLists file don't make sense.

**Comment by GaryElshaw** [comment]
Something must have gone amiss with the previous version. It was working fine yesterday, so ¯\_(ツ)_/¯

**Pull request closed without merging**
