### PR TITLE
docs: add a draft of 4.0.0-beta.2 notes

### PR DESCRIPTION
**Pull request by ckerr**
**SEE IT HERE:** https://github.com/transmission/transmission/blob/docs/release-notes/news/news-4.0.0-beta-2.md

This draft is so we can see which changes still need annotation. 

These notes are autogenerated :robot: so what needs to happen is PRs with obscure / technical descriptions need a new comment from a maintainer to give a user-facing descrtiption. See https://github.com/ckerr/transmission-release-notes#making-better-notes for information no how to annotate the beta.1 --> beta.2 changes to make the script happy :robot:  

See also https://github.com/transmission/transmission/discussions/4251

CC @Coeur @mikedld

### CODE REVIEW

**Comment by Coeur** [comment]
How can I edit your Notes, Charles?
I want to change all the "XCode" to "Xcode"

**Comment by ckerr** [comment]
> How can I edit your Notes, Charles? I want to change all the "XCode" to "Xcode"

Adding a new `Notes: ` comment for the relevant PRs will work. The script will pick the newest comment from any of us.

**Comment by Coeur** [comment]
OK, I've done various revisions and added the LABEL `Notes:note` to some pulls: I hope it gets picked too.
Feel free to re-run the script for an updated draft.

**Comment by ckerr** [comment]
I've pushed up a newly-generated draft

**Comment by Coeur** [comment]
What's the logic for display order? It's neither alphabetical or by PR id.
And it's hard to review the list if the entries are pseudo-randomized with each commit.

**Comment by ckerr** [comment]
> What's the logic for display order? It's neither alphabetical or by PR id. And it's hard to review the list if the entries are pseudo-randomized with each commit.

Inside each section:

- Primary key is detection of these labels, in this order of priority: `notes:highlight`, `type:feat`, `type:fix`, `type:perf`, `type:ui`, `type:refactor`, `type:test`, `type:docs`.
- Secondary key is now PR number (but wasn't in an earlier version, which probably contributed to the pseudorandom appearance)

**Comment by Coeur** [comment]
You seem to have mixed sonarcloud fixes with those release notes, so it's inconvenient to review this PR now.

**Comment by ckerr** [comment]
> You seem to have mixed sonarcloud fixes with those release notes, so it's inconvenient to review this PR now.

Fixed.

**Comment by mikedld** [comment]
Added `notes:none` to a couple of GTK client PRs, the rest (for GTK client) seems fine.

**Comment by GaryElshaw** [comment]
@ckerr Charles, Antoine (@Coeur) most definitely needs to be included in `### Contributions to `macOS Client`:'

**Comment by ckerr** [comment]
> @ckerr Charles, Antoine (@Coeur) most definitely needs to be included in ### Contributions to macOS Client:
>
> I'll also take the blame for https://github.com/transmission/transmission/pull/4055.

@GaryElshaw your're listed now in ba5a779c; sorry for the omission.

Both you and @Coeur were omitted for the same reason -- a wart in the release-notes script that I'll try to fix for beta 3.

Basically, there's a single list in the code that says "these are the active devs" which means they can write `Notes:` comments and that they get omittted from the "Thanks" section, which is intended more for people who aren't doing PRs every week, to give them credit and give them a little positive feedback in the hopes they'll do more :smile_cat: 

But definitely there needs to be a way of giving people like @Coeur and @mikedld and me proper credit too. I'll work on that in the script before beta 3.

**Comment by Coeur** [comment]
I don't need to be credited.

**Pull request merged**
