### PR TITLE
Add ready-made RPC wrappers

### PR DESCRIPTION
**Pull request by Petrprogs**

### CODE REVIEW

**Review by ckerr — APPROVED** [review]
Thanks!

**Comment by Petrprogs** [comment]
You're welcome! But why my changes does not appear in this .md file?

**Comment by ckerr** [comment]
> You're welcome! But why my changes does not merged?

CI broke last night due to a server outage and I was waiting to see if it would be fixed, since it's a little nicer to merge PRs when CI is green.

The CI failure is CI's own fault and not this PR though, so I guess it's fine to merge it anyway :slightly_smiling_face:

**Comment by Petrprogs** [comment]
OK, I'll be waiting :)

**Pull request merged**
