### PR TITLE
macOS autolayout fixes on Inspector - Options tab

### LINKED ISSUE #3558: [macOS] UI-Torrent Inspector, German, etc.
- v.3.00+

After v 3 00+

Example: Before v.3.00

Before v 3 00

### PR DESCRIPTION
**Pull request by sweetppro**
Fixes #3558

### CODE REVIEW

**Comment by sweetppro** [comment]
Fixes some Deutsche autolayout issues on the Inspector - Options tab:
**Before:**
before

**After:**
after

**Comment by nevack** [comment]
Diff: 
image

**Review by nevack — APPROVED** [review]
LGTM

**Comment by sweetppro** [comment]
> Diff:

@nevack which app do you use to do this?

**Comment by Oleg-Chashko** [comment]
@sweetppro 
You couldn't fix it?

Bildschirmfoto 2022-07-31 um 18 03 49

**Comment by nevack** [comment]
> > Diff:
> 
> @nevack which app do you use to do this?

I just took you before/after image and used https://www.diffchecker.com/image-diff/

**Comment by nevack** [comment]
> @sweetppro It's not all fixed yet. You couldn't fix it?
> 
> Bildschirmfoto 2022-07-31 um 18 03 49

What do you mean here? Uneven height of Combo Buttons?

**Comment by Oleg-Chashko** [comment]
> > @sweetppro It's not all fixed yet. You couldn't fix it?
> > Bildschirmfoto 2022-07-31 um 18 03 49
> 
> What do you mean here? Uneven height of Combo Buttons?

https://github.com/transmission/transmission/issues/3558

**Comment by sweetppro** [comment]
The difference is so subtle, I can barely see it.
But Ive put an equal height constraint on Both the popup buttons,
so it should be equal now

**Comment by Oleg-Chashko** [comment]
> The difference is so subtle, I can barely see it.
> But Ive put an equal height constraint on Both the popup buttons,
> so it should be equal now:
> Bildschirmfoto 2022-07-31 um 6 32 12 PM

It's all fixed now in this issue.
The difference is exactly one pixel. 
And it is he who draws attention to himself.
That being said 13":
Bildschirmfoto 2022-07-31 um 18 35 42

**Pull request merged**
