### PR TITLE
Updated macOS segmented control alignment and popup button style

### PR DESCRIPTION
**Pull request by sweetppro**
addresses the following request: https://github.com/transmission/transmission/issues/3143:
Screen Shot 2022-05-29 at 4 29 36 pm
Screen Shot 2022-05-29 at 4 29 46 pm
Screen Shot 2022-05-29 at 4 30 33 pm
Screen Shot 2022-05-29 at 4 30 04 pm

### CODE REVIEW

**Comment by sweetppro** [comment]
@ckerr im not sure exactly what the issue is with the code style...

**Comment by sweetppro** [comment]
@ckerr ah thanks,
I didn't see the extra white-space

**Comment by ckerr** [comment]
The lack of progress on the recent macOS UI PRs is a little frustrating.

Nothing against the previous reviewers; I know all too well how difficult it is to find time for reviews. And since I hold the 10 Year Gold Medal in not reviewing Transmission PRs, I'm the last person to shame people for having afk lives :smile:  The answer isn't to shame busy reviewers; it's to have more reviewers.

@GaryElshaw and @sweetppro maybe you could review each others' changes?

**Comment by sweetppro** [comment]
no problem @ckerr, this is a volunteer operation after all and we all have busy lives

**Pull request merged**
