### PR TITLE
web client: edit some style and add space

### PR DESCRIPTION
**Pull request by S-Aarab**
addresses majority of suggetions in #5448

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Nicely done.

**Comment by ckerr** [comment]
This PR LGTM.

One concern, it looks like there are three people working in the same area with overlapping PRs: @dareiff (in #5272 and maybe in other PRs IIRC?) and @klevain (in #5470 and other work queued in #5460) and @S-Aarab here in #5466.

TBH all of the patches above look pretty good.

Transmission always needs more contributors, so I want to make sure that nobody feels slighted & gets driven away by someone else's conflicting PR getting merged :smile_cat: 

If you three could collaborate / figure out among yourselves, either in these PRs or in a  [discussion thread](https://github.com/transmission/transmission/discussions), I'll be happy to merge whatever y'all agrere on. What I'm looking for:

- for y'all to come to consensus
- for me to know what PRs should get merged and in which order
- single-topic PRs, e.g. so if there's a bugfix I can backport it to 4.0.x

**Comment by S-Aarab** [comment]
I'm not that familiar with git and github, I will try my best to follow, but I will accept whatevery you deside guys.

**Comment by klevain** [comment]
I think that, from mines, only #5470 is a more critical feature for the users.

The #5272 could be easily merge (not sure of the right git jargon here) as it cover theme and contrast.

So for me, in that order, should go smoothly : 
(0- #5466)
1- #5470 
2- #5472
(3- #5466)

But really I'm no expert in git/GitHub and would love to learn if this is bad idea.

**Comment by dareiff** [comment]
> This PR LGTM.
> 
> One concern, it looks like there are three people working in the same area with overlapping PRs: @dareiff (in #5272 and maybe in other PRs IIRC?) and @klevain (in #5470 and other work queued in #5460) and @S-Aarab here in #5466.
> 
> TBH all of the patches above look pretty good.
> 
> Transmission always needs more contributors, so I want to make sure that nobody feels slighted & gets driven away by someone else's conflicting PR getting merged 😸
> 
> If you three could collaborate / figure out among yourselves, either in these PRs or in a [discussion thread](https://github.com/transmission/transmission/discussions), I'll be happy to merge whatever y'all agrere on. What I'm looking for:
> 
> * for y'all to come to consensus
> * for me to know what PRs should get merged and in which order
> * single-topic PRs, e.g. so if there's a bugfix I can backport it to 4.0.x

I think I'll close my dark mode pull request (#5272) in favor of the others’ — not TOO much in there. When these new suggests from @S-Aarab and @klevain are in, I'll update my changes and submit for review!

**Comment by ckerr** [comment]
Notes: Improved some UI styling and spacing.

**Pull request merged**
