### PR TITLE
replace macOS Groups indicators with dots

### PR DESCRIPTION
**Pull request by sweetppro**
the current Group indicator PR #3183 uses bars. I feel using circles is a better fit with the overall theme of Transmission #3224 and macOS. Also added a similar style for the Compact view.
Uses the group icons images from @Coeur
minimal
regular
Screen Shot 2022-06-12 at 3 48 48 pm

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Ha!

**Comment by sweetppro** [comment]
> Ha!

I always preferred the look of the dots
:)

**Comment by GaryElshaw** [comment]
Are there royalties for the design attribution?

**Comment by sweetppro** [comment]
> Are there royalties for the design attribution?

100 internet points 💯 👍

**Comment by GaryElshaw** [comment]
> 100 internet points 💯 👍

That's worth about twice as much as the market rate for bitcoin, right?

**Comment by GaryElshaw** [comment]
@sweetppro For some reason the main window is now truncated, i can't scroll up to see another 7 or so torrents. If i enable the filter bar... :-(

SCR-20220613-ju5

**Comment by sweetppro** [comment]
thats odd, try restarting transmission, also try toggling in and out of fullldcreen

**Comment by GaryElshaw** [comment]
I got view of one more torrent by entering and exiting, alas no difference with a restart.

**Comment by sweetppro** [comment]
hmmm,
I see there is an issue when adding or removing torrents

**Comment by sweetppro** [comment]
how many torrents do you have, more than fits on screen?
and do you have the autosize setting enabled?

**Comment by GaryElshaw** [comment]
I have 20 torrents, and yes, the auto-size is on.

**Comment by sweetppro** [comment]
could you open a new issue, ill take a look later today

**Comment by GaryElshaw** [comment]
Will do. Filter bar is still, technical term, squiffy.

**Pull request merged**
