### PR TITLE
replace macOS encrypted image on macOS 11+

### PR DESCRIPTION
**Pull request by sweetppro**
various discussions on this... most recent is here:
closes https://github.com/transmission/transmission/pull/3217

### CODE REVIEW

**Comment by sweetppro** [comment]
here's a screen from macOS Monterey
Screen Shot 2022-06-06 at 5 03 36 pm

**Comment by ckerr** [comment]
Just out of curiosity, on what platforms will this be supported and which will it be not supported?

**Comment by sweetppro** [comment]
> Just out of curiosity, on what platforms will this be supported and which will it be not supported?
the new system icon will be shown on macOS11+, otherwise the older png file will be shown

**Comment by GaryElshaw** [comment]
> > Just out of curiosity, on what platforms will this be supported and which will it be not supported?
> 
> the new system icon will be shown on macOS11+, otherwise the older png file will be shown

@sweetppro @ckerr Merge mine then this immediately after?

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
Approving since this seems to match all the discussion in the other threads.

If anyone doesn't speak up to request changes, I'll merge this tonight

**Comment by GaryElshaw** [comment]
If i wanted to change the colour locally, how do i do that @sweetppro?

 [NSImage systemSymbol:@"lock.fill" withFallback:@"Lock"] : nil;

**Comment by GaryElshaw** [comment]
Can these be taken down by a couple of pixels and centred? Note how they don't float in the middle but sit on the line.

SCR-20220608-kye

**Pull request merged**
