### PR TITLE
docs: add 4.1.0-beta.1 notes

### PR DESCRIPTION
**Pull request by ckerr**
Add 4.1.0-beta.1 notes.

Bump version to 4.1.0-beta.1.

### CODE REVIEW

**Review by mikedld — APPROVED** [review]

**Comment by jggimi** [comment]
@ckerr it looks like there's a typo in the tag:  `4.0.1-beta.1` rather than `4.1.0-beta.1`.

**Comment by ckerr** [comment]
@jggimi thanks! I've pushed up a new tag `4.1.0-beta.1` for the same commit. I need to leave the previous one in place for a little bit but will delete it when the bots are done

**Comment by tearfur** [comment]
Does this mean that features are now frozen until `4.2.0-dev`?

**Comment by ckerr** [comment]
@tearfur I'm OK with landing new features for now.

We'll want to have a freeze period before 4.1.0 stable, but this branch has been in development for nearly two years so my _guess_ is we'll be in beta for awhile. My _guess_ is that'll be 2-3 months but who knows? Maybe nobody will report any bugs :smile: and it'll be much shorter

**Comment by Pentaphon** [comment]
>this branch has been in development for nearly two years so my _guess_ is we'll be in beta for awhile. My _guess_ is that'll be 2-3 months but who knows?

This is great, but I know this userbase pretty well from reading the comments for years and they will complain that they have to wait months to use this new version of Transmission on certain trackers. I think at least some of the urgent fixes from https://github.com/transmission/transmission/issues/7094 should be backported to a 4.0.7 release while people wait for 4.1.0 stable.

**Comment by tearfur** [comment]
> I'm OK with landing new features for now.

I want to know how things will go down from now until `4.1.0` stable, because this changes what I'll be working on. Will we be landing them *during* the beta? Or will there be a dev version after this beta and until the next beta/stable?

**Comment by Rukario** [comment]
@ckerr 2 months is a decent time frame but please be sure give us some headroom for subsequent PRs by not pulling in decent PRs at the last-minute if you're going to accept some more PRs for 4.1.0 before doing a feature freeze. Someone like me may have been waiting for certain others to go before submitting subsequent PRs.

It's good to see 4.1.0 is finally coming. The release of 4.0 was about 2 years ago and some of the decent PRs we felt have been in limbo for more than a year already. It's hard to watch them hanging. A "feature freeze" is a schedule thing and you haven't described the release calendar. This is something I'll want to know when to take a break for as long as you do. 😄

**Comment by Pentaphon** [comment]
> 2 months is a decent time frame but please be sure give us some headroom for subsequent PRs by not pulling in decent PRs at the last-minute if you're going to accept some more PRs for 4.1.0 before doing a feature freeze. Someone like me may have been waiting for certain others to go before submitting subsequent PRs.

I agree. There are many PRs in the 95 existing ones that need to be merged before beta 2 comes out.

**Comment by k0ste** [comment]
Thanks for this release 🎅
Compared with 4.0.6, the 4.1.0-beta gives performance boost 🚀
With version 4.0.6, if I start couple big torrents to download, the system becomes unusable (even ICMP drops). With this beta, I can download 25 torrents (~1.2T in total) in same time (300Mbit/s avg)

----
Screenshot 2024-12-23 at 19 45 48

Seems `cache-size-mb: 0` now really works 🤝

**Pull request merged**
