### PR TITLE
Increase the buffer size used in tr_moveFile

### PR DESCRIPTION
**Pull request by orf**
In some filesystems, including ones mounted on a network drive, using a small buffer size 
significantly hurts copy performance. Upping the buffer to 1024kb to increase copy performance.

For reference. while moving a torrent data file to a network share Transmission completely locks up until it's done, and it takes many, many hours to copy most files. The 128kb buffer used right now for copying files is way, way way too small!

### CODE REVIEW

**Comment by lps-rocks** [comment]
I wouldn't merge this - This copy function should be replaced with sendfile64 on Linux based systems - this makes the fs I/O stay within the kernel.  - https://linux.die.net/man/2/sendfile64

**Comment by andreygursky** [comment]
> This copy function should be replaced with sendfile64 on Linux based systems

Still this wouldn't be enough to fix https://github.com/transmission/transmission/issues/694.

**Comment by orf** [comment]
Using sendfile64 is a larger change that is perhaps more trouble than it's worth. Upping the buffer will make this faster with far, far less risk of breakage.

**Comment by RobCrowston** [comment]
> I wouldn't merge this - This copy function should be replaced with sendfile64 on Linux based systems - this makes the fs I/O stay within the kernel. - https://linux.die.net/man/2/sendfile64

This is a simple change that may have immediate benefits, and does not preclude work on replacing the copy mechanism with sendfile(2) for operating systems which implemented it.

128k does seem pretty small these days—the ZFS volume I use for storing media files has a block size of 1M, so effectively the kernel will wait for that buffer to fill up eight times before it even thinks about committing anything to disk. This seems inefficient.

**Comment by RobCrowston** [comment]
> > This copy function should be replaced with sendfile64 on Linux based systems
> 
> Still this wouldn't be enough to fix #694.

That's true on Linux, but on FreeBSD, thanks to Netflix sendfile(2) is asynchronous. Although there may be side effects in returning from the function before the copy is complete, I'll do some experimentation.

**Pull request merged**
