### PR TITLE
macOS preference window localization autolayout fixes

### PR DESCRIPTION
**Pull request by sweetppro**
Fixes: #3467

### CODE REVIEW

**Comment by ckerr** [comment]
Can someone give this a spin and review it? :)

**Comment by GaryElshaw** [comment]
Unfortunately this version is also giving me a one-bounce-in-the-dock result :-( The nightlies from Jenkins are working fine.

**Review by nevack — APPROVED** [review]
LGTM

**Comment by Oleg-Chashko** [comment]
> Can someone give this a spin and review it? :)

- #3467

Bandwidth, Turkish

- #3476

Remote, Spanish

- #3476

Remote, Italian

**Comment by sweetppro** [comment]
@ckerr this PR is ready :)

**Pull request merged**
