### PR TITLE
chore: iwyu

### PR DESCRIPTION
**Pull request by tearfur**

### CODE REVIEW

**Comment by Pentaphon** [comment]
@tearfur are we nearing a release?

**Comment by tearfur** [comment]
Sorry to disappoint, but I have no idea. Transmission's governance is very much a black box to me as well.

**Review by ckerr — APPROVED** [review]
:+1:

**Comment by ckerr** [comment]
> Sorry to disappoint, but I have no idea. Transmission's governance is very much a black box to me as well.

Generally the release decision is (a) are the changes worth a release? and (b) is there a time when me, @livings124, and @mikedld are all available to do the release? Generally I make a tarball, Mitchell does the macOS binaries, Mike does the Windows binaries, and Mike or I updates transmissionbt.com.

For [`4.0.x`](https://github.com/transmission/transmission/commits/4.0.x) yes there are probably enough fixes (esp from @tearfur) to make 4.0.5 worthwhile. If any @transmission/contributors want to look through the commit logs in `main` in search of fixes that need to be backported that would be very useful.

For 4.1.0... :man_shrugging: since `4.0.x` seems to be going well and since we don't have deadlines, I've been thinking more in terms of "how often are we landing good changes" rather than something release-focused like "what are the remaining issues for 4.1.0". But TBH I don't have much of an opinion about it. If a lot of contributors feel strongly about a timeline, I'd go along.

As far as governance goes... other @transmission/contributors, especially those landing commits on the regular like @Coeur, @tearfur, and @nevack should have a say if they want one. And there is currently a "bus factor" on releases -- e.g. I don't know if we could actually do macOS releases if @livings124 wasn't available.  In the past I'd've said let's follow this up in Team Discussions, but GitHub has sunsetted those. :thinking:

**Comment by nevack** [comment]
> In the past I'd've said let's follow this up in Team Discussions, but GitHub has sunsetted those. 🤔

I would definitely love to have some (probably private?) way of communication between maintainers and contributors to coordinate things. Maybe Matrix room or something else.
Emails and comments in unrelated PRs are way too difficult to use 😄 

>  e.g. I don't know if we could actually do macOS releases if @livings124 wasn't available.

I think you are fine if you have access to private keys to sign mac release binaries.

**Comment by Pentaphon** [comment]
> For 4.1.0... 🤷‍♂️ since `4.0.x` seems to be going well and since we don't have deadlines, I've been thinking more in terms of "how often are we landing good changes" rather than something release-focused like "what are the remaining issues for 4.1.0". But TBH I don't have much of an opinion about it. If a lot of contributors feel strongly about a timeline, I'd go along.

I am just a user but since everybody is being tagged and they will see this, I do hope that the next release is 4.1.0 and it resolves https://github.com/transmission/transmission/issues/5261 since that issue has received a LOT of attention and I think my fellow users are hungry to move to a minor release.

**Comment by Pentaphon** [comment]
> I would definitely love to have some (probably private?) way of communication between maintainers and contributors to coordinate things. Maybe Matrix room or something else.

At the very least you guys should open a private IRC.

**Comment by Coeur** [comment]
I agree with Pentaphon. We should make a 4.1.0 release as soon as we figured out the performance regression issue.

**Comment by tearfur** [comment]
> I would definitely love to have some (probably private?) way of communication between maintainers and contributors to coordinate things.

Yes!

> We should make a 4.1.0 release as soon as we figured out the performance regression issue.

We've already got a *lot* of work done for that on the `main` branch, in fact, I think we are overdue on a 4.1.0 release for those changes to get some real world testing.

**Comment by GaryElshaw** [comment]
> We've already got a _lot_ of work done for that on the `main` branch, in fact, I think we are overdue on a 4.1.0 release for those changes to get some real world testing.

Agreed

**Comment by tearfur** [comment]
I say we release as soon as possible, we have all the reasons for making a new release asap.

From the users' perspective, we have:
- Major enhancements (peer pool rework, WebUI facelift, stay connected to seeds for PEX, ...)
- Important fixes (jumbled strings in RPC, overly aggressive bandwidth clamping, `&ip=` parameter in udp announcement, ...)
- Many other fixes and performance improvements
- No stability regressions AFAICT

Under the hood, we've undergone several major refactors that changes the way we write new code. I see them as positive changes on their own, but they also make backporting a chore. So that's one more reason for me to want the `4.0.x` series to end and move on to `4.1.x`.

Here's my preference for what the project should do the next time all 3 maintainers are able to negotiate a schedule:
1. Release both `4.0.5` and `4.1.0` at the same time. We get the best of both worlds this way: The `4.0.x` series gets all its glaring issues taken care of, and we also get all the exciting new features in `main`.
2. Release `4.1.0`.
3. Release `4.0.5`.

In any case, I think the `4.0.x` series should end with the next release, and we focus fully on `4.1.x`.

**Comment by Coeur** [comment]
OK with Tearfur schedule. And we can always fix the performances in 4.1.1 if we figure out something useful.

**Comment by Pentaphon** [comment]
> 1. Release both `4.0.5` and `4.1.0` at the same time.

My only disagreement with this possible scenario is that from a user's perspective, very few, if any, users will care to install the 4.0.5 release once 4.1.0 is out. Users always want the latest and greatest. Even Debian users, who are used to being stuck on older releases, will clamor to get the 4.1.0 release over the 4.0.5 release. 

I see only 2 possible scenarios: 

1) Release 4.0.5 ASAP and then 4.1.0 whenever it is ready. 

2) Disregard 4.0.5 and focus all efforts on releasing 4.1.0.

Personally, I think Option 2 is the best way forward. 4.0.x was a huge undertaking and a necessary step, but it's time to focus on a minor release rather than patches. Users will be relieved to see a 4.1.0 release that fixes most if not all their issues with 4.0.x

I think the best course of action right now is to go through all the PR's, especially the ones marked 4.1.0, and update the status of the PRs marked "decide after 4.0.0" as those are getting quite old.

**Comment by Coeur** [comment]
@Pentaphon: the benefit of double-release is in case someone finds something has regressed in 4.1.x that was working in 4.0.x

**Comment by Pentaphon** [comment]
> the benefit of double-release is in case someone finds something has regressed in 4.1.x that was working in 4.0.x

Sure, but even if the team goes directly to releasing 4.1.0 and something regresses, people will either go back to 4.0.4 or 3.0

I have personally seen a lot of people in the wild switch back to 3.0 because of https://github.com/transmission/transmission/issues/5261 and they are just waiting for the 4.x series to meet or exceed their speed expectations from 3.0

I don't see the benefit in a double release and I think it would spread the team too thin, working on 2 goals at the same time.  Considering how many regular contributors the project has, I think it makes much more sense to do things 1 at a time, albeit on a faster, more carefully planned schedule. I'm not opposed to seeing 4.0.5 come out, but I think the users won't value 4.0.5 as much you think they would if 4.0.5 came out the same time as 4.1.0...

**Comment by GaryElshaw** [comment]
The more i think about it, the more i think @Pentaphon is right. The last several months have been a mess of pr's going to the separate branches without a lot of thought about the 4.0 branch as everyone races ahead with zero backwards compatibility changes. That's fine. But while the project keeps pushing forward, the significant changes become irrelevant to 4.0.

I'm also frustrated as a contributor. Pr's that sit in limbo, issues unaddressed that require focus. I get that everyone has their own priorities to fix or move the project forward, but it feels like it's in the hope it addresses past issues.

I have multiple pr's addressing issues raised by users. #4973 and #4421 address a user complaint about a theme-related issue in linux where, unlike most applications, a monochrome icon was unavailable in the systray. After working on it, it's now a one line code change sitting in limbo since December.

#5340 is in response to some of the concerns @Pentaphon raised that i've tried to address in April.

#4376 is finishing what Mike started in draft form in 2021 that has been in limbo since December. 

I've just pushed #5961 into draft because the commits to the webui have been out of alignment, necessitating having to go back to #5762 in August for a change i submitted in September.

**Comment by Pentaphon** [comment]
@GaryElshaw I totally agree but I think the next step to take ASAP is for somebody like you or @tearfur to really push for a private method of communication and coordination that the entire contributing group can agree on like Matrix, IRC, XMPP, Mattermost, etc and then I think the ball will roll, so to speak, from there. It sounds like right now, Github is the only means of keeping everybody in sync and Github is simply not enough for that purpose.

**Comment by tearfur** [comment]
My preference would be a Discord server. I think they will fit us since they offer admistrative functions such access control, and Markdown formatted chat (most importantly, syntax highlighted code blocks are supported).

**Comment by ckerr** [comment]
Woo there is a lot of scrollback to go through :smile_cat: 

One quick thought about @tearfur's idea of releasing 4.0.5 and 4.1.0 at the same time: given how much refactoring has gone on in `main`, we might want to consider a `4.1.0-beta.1` first.

And that opens up another question -- IIRC there was some complication in the macOS client's there-is-a-new-beta-release notification code that @Coeur and @nevack probably remember / understood better than I do, but I _think_ the upshot was that we needed to get a fix into a `4.0.x` macOS client before releasing a `4.1.0-beta.x`. If I'm remembering that correctly, then that should probably be the top priority as a release blocker

**Comment by ckerr** [comment]
> The more i think about it, the more i think @Pentaphon is right. The last several months have been a mess of pr's going to the separate branches without a lot of thought about the 4.0 branch as everyone races ahead with zero backwards compatibility changes.

This is untrue and ignores the existence of the [4.0.x milestone label](https://github.com/transmission/transmission/pulls?q=+is%3Apr+milestone%3A4.0.x+) and the [4.1.0 milestone label](https://github.com/transmission/transmission/pulls?q=+is%3Apr+milestone%3A4.1.0). Quite a bit of work has gone into ensuring that fixes affecting 4.0.x have been backported.

The claim that no care is given to backwards compatibility is risably inaccurate. For example, the reason #3823 stayed in review for so long was specifically _because of_ concerns about backward compatibility.

Lastly the pejorative phrasing "mess of prs" ... I just don't see anything productive in that line of discussion.

The project accepts _far more_ contributor PRs than it ever has before. _Many_ people have spent ***many*** hours on the work that's gone into `main` and your dismissive tone of it honestly makes me angry.  Since I don't want to have Yet Another Argument with you, I'll just ask that you consider whether writing  "mess of prs ... without a lot of thought ... with zero backwards compatibility" is helpful to your goals, and leave it at that.

> I'm also frustrated as a contributor. Pr's that sit in limbo ... #5340 is in response to some of the concerns @Pentaphon raised that i've tried to address in April.

- PR went up April 1.
- You first @'ed the web ui reviewers for feedback on July 25.
- Looks like the period between Aug 15 and Sept 12 had productive back & forth with reviews & code updates.
- You never @'ed Rukario for a re-review after your last set of changes two months ago.

**Comment by ckerr** [comment]
> I have personally seen a lot of people in the wild switch back to 3.0 because of https://github.com/transmission/transmission/issues/5261 and they are just waiting for the 4.x series to meet or exceed their speed expectations from 3.0

TBH I never know how seriously to take these bug reports. EVERY new release for as long as I remember has had some complaints that it's slower than the previous release. I honestly can't tell if there's anything actionable in 5261 or not. The main benefit for issues like 5261 is to surface discussion like the one that turned into #5667.

**Comment by ckerr** [comment]
@Coeur + @nevack can you two take point on looking into what it takes to get the hey-a-new-beta-is-available notification working in the macOS client? If there's not already a ticket, please open one

**Comment by tearfur** [comment]
> @Coeur + @nevack can you two take point on looking into what it takes to get the hey-a-new-beta-is-available notification working in the macOS client for 4.0.5 so that it will be in place before 4.1.0-beta.1 goes out?
> 
> If there's not already a ticket, please open one

@ckerr Is #5263 what you are looking for?

**Comment by ckerr** [comment]
Yes, that's the one! Thank you!

**Comment by tearfur** [comment]
> One quick thought about @tearfur's idea of releasing 4.0.5 and 4.1.0 at the same time: given how much refactoring has gone on in `main`, we might want to consider a `4.1.0-beta.1` first.

I say go for it if the maintainers' schedules can line up for a couple of closely-packed releases.

> And that opens up another question -- IIRC there was some complication in the macOS client's there-is-a-new-beta-release notification code that @Coeur and @nevack probably remember / understood better than I do, but I _think_ the upshot was that we needed to get a fix into a `4.0.x` macOS client before releasing a `4.1.0-beta.x`. If I'm remembering that correctly, then that should probably be the top priority as a release blocker

So the implications are, if we go for the beta, we will have to release `4.0.5` first, then the beta(s), then `4.1.0`. Again, I say go for it if the maintainers' schedules allow for it.

**Comment by ckerr** [comment]
IMO the diffs between `main` and `4.0.x` are large enough to warrant a beta release.

If we're doing a beta, we kind of _need_ to have a `4.0.5` release for the sake of 5263. So that becomes the next task + a release blocker

**Comment by ckerr** [comment]
@ilikepeaches I hear what you're saying, but are you able to guarantee that 4.1.0 is stable and ready to go right now without a beta test cycle? :smile_cat:

**Comment by Pentaphon** [comment]
> but the current stable version of Transmission remains 3.0

I'm also thinking about going back to 3.0 for the time being but again, I really think you can do a lot more to help confirm whether the contributors have made any progress on your issue. You can't expect people to do the work without doing something in return. Please consider going the extra mile for this project and grabbing another machine to test the nightlies on public, private and any tracker you can find.

**Comment by Pentaphon** [comment]
> Excuse me?

@ilikepeaches I'll keep the discussion in the other thread. I didn't expect you to show up here.

**Comment by GaryElshaw** [comment]
> Lastly the pejorative phrasing "mess of prs" ... I just don't see anything productive in that line of discussion.

That's my colloquial expression for truckload, boatload, a lot, murder of crows etc.

**Pull request merged**
