### PR TITLE
macOS fix some autolayout issues in Info window

### LINKED ISSUE #3491: [macOS] UI-Torrent Inspector, Clipping, German and Russian
- German
German

- Russian
Russian

### PR DESCRIPTION
**Pull request by sweetppro**
Fixes #3491

### CODE REVIEW

**Comment by Oleg-Chashko** [comment]
Checked, fixed

- German
German

- Russian
Russian

**Comment by Oleg-Chashko** [comment]
Clipping, German:

Bildschirmfoto 2022-07-21 um 09 57 17

**Comment by GaryElshaw** [comment]
Depending on the length, that seems acceptable to truncate.

**Comment by Oleg-Chashko** [comment]
No, that's not acceptable:
1. In all other localizations there is no clipping.
2. You have to stick to one standard.
3. Especially since there is plenty of free space for this.

**Comment by GaryElshaw** [comment]
I'm not disagreeing with you per se, just saying that depending on the length, it makes sense to truncate rather than expand the window, especially if there is sufficient information to recognise what parameter is effected. My Deutsch is rusty, but i can determine what the setting is for.

**Comment by Oleg-Chashko** [comment]
Also, there is no clipping in the current release version. 

Example: v.3.00.f4489c982e

v 3 00 (f4489c982e)

**Comment by sweetppro** [comment]
It’s no problem, I’ll fix it when I get home. Autolayout is a complex beast… every element affects all other elements. And we have 8? different locales to test against

**Comment by Oleg-Chashko** [comment]
> It’s no problem, I’ll fix it when I get home. Autolayout is a complex beast… every element affects all other elements. And we have 8? different locales to test against

It is better to look at the size of the German localization. Because German has the longest words. Of the localizations that are available in this app.

But you already know that without me.

**Comment by GaryElshaw** [comment]
@Oleg-Chashko If i understand correctly, it wasn't truncated, but had the appearance of being truncated?

**Comment by Oleg-Chashko** [comment]
> @Oleg-Chashko If i understand correctly, it wasn't truncated, but had the appearance of being truncated?

You may be right.

**Comment by GaryElshaw** [comment]
Off-topic. https://www.youtube.com/watch?v=Nv0efmUKP9s

**Comment by sweetppro** [comment]
> It is better to look at the size of the German localization. Because German has the longest words. Of the localizations that are available in this app.

If only it were that easy :)

**Comment by Oleg-Chashko** [comment]
> Off-topic. https://www.youtube.com/watch?v=Nv0efmUKP9s

But I understood what they were singing about. :)

The Sex Pistols, I didn't catch that time, I was too young. 
I started listening to music with Iron Maiden - The Number of the Beast.

**Comment by GaryElshaw** [comment]
> > Off-topic. https://www.youtube.com/watch?v=Nv0efmUKP9s
> 
> But I understood what they were singing about. :)
> 
> The Sex Pistols, I didn't catch that time, I was too young. I started listening to music with Iron Maiden - The Number of the Beast.

Hush your mouth, they are not the same! ;-)

**Comment by Oleg-Chashko** [comment]
Checked, fixed https://github.com/transmission/transmission/pull/3497#issuecomment-1191172616

Bildschirmfoto 2022-07-21 um 13 43 25

**Pull request merged**
