### PR TITLE
Updated icon for ActionHover on MacOS

### PR DESCRIPTION
**Pull request by GaryElshaw**
A secondary change to, arguably, make the MacOS iconography more in keeping with the modern MacOS environment, and to make it clear that we're differentiating a menu item from a button.

Complementary to #3178, they both signify to the user that additional options are available to the user from a menu. Unlike the global speed changes in #3178, this is for adjusting individual torrent speeds using an Apple SF Symbols icon (chevron.down.circle.fill).

SCR-20220614-scb

SCR-20220614-sby

### CODE REVIEW

**Comment by Coeur** [comment]
I'm not in favour of this iconographic change. A checkmark is for a "success/done".
I'm happy with the present settings wheel.

**Comment by GaryElshaw** [comment]
> I'm not in favour of this iconographic change. A checkmark is for a "success/done". I'm happy with the present settings wheel.

If you look closer, it's a chevron, not a tick. I'm looking at other colours right now, this doesn't have the right appearance.

**Comment by GaryElshaw** [comment]
Okay, i'm happy with this.

**Comment by RobFog** [comment]
The black on blue thing is pretty ugly. I'd prefer the "subtle iteration".

**Comment by Oleg-Chashko** [comment]
I'm sorry I couldn't contain myself. 
This icon looks very ugly. In modern macOS, everything is rounded or round at the moment. 
Either leave the old one or the round one. 

Example:
172763013-502e32c7-b693-4c4d-85e6-7fc644df5b04

**Comment by GaryElshaw** [comment]
> I'm sorry I couldn't contain myself. This icon looks very ugly. In modern macOS, everything is rounded or round at the moment. Either leave the old one or the round one.
> 
> Example: 172763013-502e32c7-b693-4c4d-85e6-7fc644df5b04

I did try that Oleg, but because the positioning is so janky, at least with the rectangle it looks a little better in its alignment.

**Comment by Oleg-Chashko** [comment]
Here are a couple more examples, but these are the worst alternatives. 
The circle is better, after all. If you leave the square, it would be better to round the corners more.

**Comment by Oleg-Chashko** [comment]
Drawn in the Sketch app. 
The source code is in the archives. 
Created by me, no license required. 
If you need to use and change as you please.

[White_&_Black_Triangle.zip](https://github.com/transmission/transmission/files/8870023/White_._Black_Triangle.zip)
[White_&_Black_Сhevron.zip](https://github.com/transmission/transmission/files/8870024/White_._Black_.hevron.zip)

Example_Black_Сhevron
Example_Black_Сhevron
Example_Black_Triangle
Example_Black_Triangle
Example_White_Сhevron
Example_White_Сhevron
Example_White_Triangle
Example_White_Triangle

**Comment by GaryElshaw** [comment]
Thanks Oleg, i really like this!

https://user-images.githubusercontent.com/62497891/172841113-d77369c2-8e92-4578-8d94-b1aeddd743cf.png

**Comment by Oleg-Chashko** [comment]
> Thanks Oleg, i really like this!
> 
> SCR-20220610-go

Glad to help.

**Comment by GaryElshaw** [comment]
> @GaryElshaw Black_Сhevron ?

I don't think so, unfortunately. It's going to have to be something more drastic :-(

**Review by sweetppro — COMMENTED** [review]
Does this need shadow?
There’s no shadows anywhere else in the UI

**Comment by GaryElshaw** [comment]
> Does this need shadow? There’s no shadows anywhere else in the UI

Possibly not, but have a look at the top, i just updated the images. Let me know whether you think it's an improvement or not.

**Comment by GaryElshaw** [comment]
> The shadow is clipped in your image. Personally I think it’s unneeded, and goes against Apples HIG

I'll revert.

**Comment by sweetppro** [comment]
Look here for inspiration, semi transparent grey with white icon
https://developer.apple.com/design/human-interface-guidelines/components/selection-and-input/color-wells

**Comment by GaryElshaw** [comment]
That's great, but i can equally see how it could be abused from overuse.

**Comment by sweetppro** [comment]
here you go:
chevron down circle fill@2x
chevron down circle fill

**Comment by GaryElshaw** [comment]
Thank you, but i feel a bit overwhelmed with all of the grey at the moment. Something sharper feels more appropriate somehow. Probably a personal thing on my part.

**Comment by sweetppro** [comment]
> Thank you, but i feel a bit overwhelmed with all of the grey at the moment. Something sharper feels more appropriate somehow. Probably a personal thing on my part.

it matches the one it is replacing....

**Comment by GaryElshaw** [comment]
I know, but i don't think moving away is a necessarily bad thing.

**Comment by Coeur** [comment]
- I like the present grey gear
- I like the suggested grey inverted chevron
- I like the suggested white inverted chevron
- I like the suggested blue inverted chevron

So don't ask me which one is best. 😸

**Comment by GaryElshaw** [comment]
Ha! Well at least one of us is easy to please :-)

**Comment by Oleg-Chashko** [comment]
- I like the present grey gear
- I like the suggested grey inverted chevron
- I like the suggested blue inverted chevron

P.S.: Can everyone give their opinion so that we can close this issue?

**Comment by GaryElshaw** [comment]
I like the simple white one, obviously. Especially if it was centred for directories/folders 👎🏼

**Comment by Oleg-Chashko** [comment]
> I like the simple white one, obviously. Especially if it was centred for directories/folders 👎🏼

On that basis, I did not choose him in my vote.

**Comment by Oleg-Chashko** [comment]
> Just a theory, but I imagine that Apple adopted a lot of greyish icons to be friendly with colour-blind people? If that's the case, we better stay away from the blue one.

People with complete color blindness have problems with all colors, so it's better to stay away from any colors.

**Review by sweetppro — CHANGES_REQUESTED** [review]
this icon has weird border artefacts on the arrows, is that intentional?

**Comment by sweetppro** [comment]
@GaryElshaw here's some inn= that style without the border, and with transparency
arrow up and down circle fill@2x
arrow up and down circle fill

**Comment by GaryElshaw** [comment]
> this icon has weird border artefacts on the arrows, is that intentional?

No, and i hadn't noticed any.

**Comment by sweetppro** [comment]
> > this icon has weird border artefacts on the arrows, is that intentional?
> 
> No, and i hadn't noticed any.
Screen Shot 2022-06-12 at 8 53 28 am

**Comment by GaryElshaw** [comment]
> > > this icon has weird border artefacts on the arrows, is that intentional?
> > 
> > 
> > No, and i hadn't noticed any.
> 
> Screen Shot 2022-06-12 at 8 53 28 am

Oh, yes. It was just to give the arrow more definition.

**Comment by sweetppro** [comment]
I don't of anywhere in macOS where icons have borders...
https://developer.apple.com/design/human-interface-guidelines/guidelines/overview

**Comment by GaryElshaw** [comment]
Equally happy w/ yours!

**Review by sweetppro — APPROVED** [review]

**Comment by GaryElshaw** [comment]
@ckerr Approved! --^

**Comment by nevack** [comment]
Honestly I couldn't figure out action just by looking at this icon.
Are there any other ideas?
Maybe UX itself needs tweaking here?

**Comment by GaryElshaw** [comment]
> I thought based on [#3239 (comment)](https://github.com/transmission/transmission/pull/3239#issuecomment-1154111536) there was still pending discussion?

I am purposely overlooking that comment. No malice at all, but without a number of other changes within what needs to be coded, there is not a lot of choice on this matter. The icon is literally the basis of the Transmission icon - up and down, for a function that controls the bandwidth for individual torrents - up and down.

**Comment by Oleg-Chashko** [comment]
I associate the vertical double arrow with vertical scrolling.
It seems to me that it doesn't belong here. And I've already expressed my opinion, see above.

**Comment by GaryElshaw** [comment]
I am and have been open to suggestion. As stated at the top, the current icon indicates, generally, preference changes. This PR is trying to indicate that specific per torrent bandwidth changes are available. It's aim is a greater level of specificity than the generic 'preferences' icon.

**Comment by Oleg-Chashko** [comment]
Okay, the application has an icon that is an automatic transmission lever. The lower position of the automatic transmission lever, this is reverse (Moving the vehicle to the rear, opposite to the main movement). This has nothing to do with the throughput. But this is my opinion about automatic transmission operation.

**Comment by Oleg-Chashko** [comment]
I like the present grey gear
I like the suggested grey inverted chevron

**Comment by GaryElshaw** [comment]
The inverted chevron is absolutely fine by me, it indicates a menu.

**Comment by Oleg-Chashko** [comment]
@GaryElshaw
I'm leaving on a call, I'll be there in 1.5-2 hours.

**Comment by Oleg-Chashko** [comment]
@GaryElshaw, [Revert to grey chevron] 👍🏻

Now I completely agree with your choice.
chevron down circle fill

**Comment by GaryElshaw** [comment]
That was the original plan, but the target area is so small...ugh. The lack of centre bothers me, but in the interim it is better.

**Comment by Oleg-Chashko** [comment]
> That was the original plan, but the target area is so small...ugh. The lack of centre bothers me, but in the interim it is better.

Or put the gear back in. I don't see any other option yet.

Screen Shot 2022-06-14 at 10 16 44

P.S.: We need to listen to our community and close this issue. Because we are like girls in a store choosing shoes and we can't choose. :)

**Comment by GaryElshaw** [comment]
E hoa, I am completely unwilling to put the gear back in, it is entirely inappropriate for this function. It is a menu option, it's not a button, and if it were, it does not change a global preference.

**Comment by Oleg-Chashko** [comment]
> E hoa, I am completely unwilling to put the gear back in, it is entirely inappropriate for this function. It is a menu option, it's not a button, and if it were, it does not change a global preference.
> 
> PS. There are only two shoes in the world: Doc Marten 8-ups, and John Fluevog Derby Swirls.

 I completely agree with you.

**Comment by ckerr** [comment]
Is there consensus on this PR now? It looks like @sweetppro and @Oleg-Chashko are in favor, and @nevack was opposed but to a previous design.

**Comment by Oleg-Chashko** [comment]
- Voting results:
[Grey Chevron] -> GaryElshaw, SweetPPro,  Coeur: (I like the suggested grey inverted chevron (4 days ago)), Oleg-Chashko.
[ ? ] -> ckerr, nevack, RobFog.

**Comment by ckerr** [comment]
> [ ? ] -> ckerr, nevack, RobFog.

As per [this discussion](https://github.com/transmission/transmission/discussions/3225) I don't really have opinions on the macOS UI on its own & would rather get consensus from actual macOS app contributors / users and then merge or decline PRs based on that consensus. :slightly_smiling_face: I'd mostly only vote on UI changes if they have other factors, e.g. if they fix a bug / improve a feature / increase maintainability.

From @Oleg-Chashko's summary it sounds like people mostly approve of this iteration or have disapproved of a _previous_ iteration and/or are silent. Since we're a group of people online in different timezones, let's emoji-vote. It's easy and I've found it to work very well on other projects, and I think it could map onto the kind of thing the group of us have going on here too.

How it works: add a reaction to this comment:

:+1: PR should be merged as-is
:eyes: I haven't tried this yet but will do so soon; please don't merge yet
:confused: More discussion / more change needed
:-1: PR should not be merged

In 24 hours I'll merge if there are "enough"  :+1:  and iff there are no :confused: :eyes: :-1:

CC @transmission/contributors

**Comment by GaryElshaw** [comment]
> I also don't understand the point of changing this icon at this time.

It's a tidy-up of macOS iconography for the macOS 11 - 12 age. The recent addition of the ellipsis icon in the bar at the bottom was about introducing an actual default macOS icon that Apple uses for that function; this is a similar change. The current icon does or doesn't do the following:

1. It doesn't indicate a menu option.
2. The current icon is an outdated 'global preferences' button, and this function is not a button feature.
3.  The current icon is not a global 'preference' change, but an individual torrent bandwidth change using a menu, that should be indicated.

**Comment by Coeur** [comment]
So we all agree on the gray ellipsis? :trollface:

**Comment by GaryElshaw** [comment]
Wait, what? I thought we agreed on doc.append.fill because the googly eyes were amusing?

doc-append-fill

**Comment by ckerr** [comment]
I'm not sure how to handle PRs like this -- I try to not make macOS UI calls myself and try to get consensus from macOS contributors / users, but it doesn't look like anyone else has strong opinions on this PR.

I think I'll merge this one and see if anyone complains.

**Pull request merged**
