### PR TITLE
fix: remove unnecessary locking in global ip cache

### LINKED ISSUE #6368: Transmission can't quit anymore: stuck on closed_future.wait() + is_updating_cv_[type].wait + std::this_thread::sleep_for(100ms)
### What is the issue?

I'm systematically unable to close the app. Here are my threads, with three waits:

https://github.com/transmission/transmission/blob/4037726150b4e508d099a676440a99869b15c6a8/libtransmission/session.cc#L1416
https://github.com/transmission/transmission/blob/4037726150b4e508d099a676440a99869b15c6a8/libtransmission/global-ip-cache.cc#L367
https://github.com/transmission/transmission/blob/4037726150b4e508d099a676440a99869b15c6a8/libtransmission/web.cc#L717

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000182b4d06c in __psynch_cvwait ()
#1	0x000000010234dc20 in _pthread_cond_wait ()
#2	0x0000000182ab14dc in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) ()
#3	0x0000000182ab1fec in std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) ()
#4	0x0000000182ab2090 in std::__1::__assoc_sub_state::wait() ()
#5	0x0000000100d3702c in std::__1::future<void>::wait[abi:v160006]() const at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/future:1256
#6	0x0000000100d3a0b8 in tr_sessionClose(tr_session*, unsigned long) at /Users/User/Developer/transmission/libtransmission/session.cc:1416
#7	0x0000000100b83738 in -[Controller applicationWillTerminate:] at /Users/User/Developer/transmission/macosx/Controller.mm:1078
#8	0x0000000182c5c570 in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#9	0x0000000182cf065c in ___CFXRegistrationPost_block_invoke ()
#10	0x0000000182cf05a4 in _CFXRegistrationPost ()
#11	0x0000000182c2b1dc in _CFXNotificationPost ()
#12	0x0000000183d1dff0 in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#13	0x0000000186650258 in -[NSApplication terminate:] ()
#14	0x00000001867785e4 in -[NSApplication _terminateFromSender:askIfShouldTerminate:saveWindows:] ()
#15	0x00000001867784dc in __52-[NSApplication(NSAppleEventHandling) _handleAEQuit]_block_invoke ()
#16	0x000000018687d764 in ___NSMainRunLoopPerformBlockInModes_block_invoke ()
#17	0x0000000182c675e4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ ()
#18	0x0000000182c674f8 in __CFRunLoopDoBlocks ()
#19	0x0000000182c66330 in __CFRunLoopRun ()
#20	0x0000000182c659ac in CFRunLoopRunSpecific ()
#21	0x000000018d214448 in RunCurrentEventLoopInMode ()
#22	0x000000018d2140d8 in ReceiveNextEventCommon ()
#23	0x000000018d213fdc in _BlockUntilNextEventMatchingListInModeWithFilter ()
#24	0x00000001864428a4 in _DPSNextEvent ()
#25	0x0000000186c1c980 in -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] ()
#26	0x0000000186435d50 in -[NSApplication run] ()
#27	0x000000018640d014 in NSApplicationMain ()
#28	0x0000000100b791e8 in main at /Users/User/Developer/transmission/macosx/main.mm:17
#29	0x00000001828090e0 in start ()

Thread 5#0	0x0000000182b4d06c in __psynch_cvwait ()
#1	0x000000010234dc20 in _pthread_cond_wait ()
#2	0x0000000182ab14dc in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) ()
#3	0x0000000100cf3fbc in void std::__1::condition_variable::wait<tr_global_ip_cache::set_is_updating(tr_address_type)::$_3>(std::__1::unique_lock<std::__1::mutex>&, tr_global_ip_cache::set_is_updating(tr_address_type)::$_3) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__mutex_base:400
#4	0x0000000100cf2b6c in tr_global_ip_cache::set_is_updating(tr_address_type) at /Users/User/Developer/transmission/libtransmission/global-ip-cache.cc:367
#5	0x0000000100cf1e8c in tr_global_ip_cache::update_source_addr(tr_address_type) at /Users/User/Developer/transmission/libtransmission/global-ip-cache.cc:263
#6	0x0000000100cf1d9c in tr_global_ip_cache::update_addr(tr_address_type) at /Users/User/Developer/transmission/libtransmission/global-ip-cache.cc:220
#7	0x0000000100cf6c58 in tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0::operator()() const at /Users/User/Developer/transmission/libtransmission/global-ip-cache.cc:140
#8	0x0000000100cf6c2c in decltype(std::declval<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0&>()()) std::__1::__invoke[abi:v160006]<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0&>(tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/invoke.h:394
#9	0x0000000100cf6be4 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0&>(tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/invoke.h:487
#10	0x0000000100cf6bc0 in std::__1::__function::__alloc_func<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0, std::__1::allocator<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0>, void ()>::operator()[abi:v160006]() at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/function.h:185
#11	0x0000000100cf5a08 in std::__1::__function::__func<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0, std::__1::allocator<tr_global_ip_cache::tr_global_ip_cache(tr_global_ip_cache::Mediator&)::$_0>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/function.h:356
#12	0x0000000100e02604 in std::__1::__function::__value_func<void ()>::operator()[abi:v160006]() const at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/function.h:510
#13	0x0000000100e02160 in std::__1::function<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/function.h:1156
#14	0x0000000100ff609c in libtransmission::EvTimer::handleTimer() at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:151
#15	0x0000000100ff5c94 in libtransmission::EvTimer::onTimer(int, short, void*) at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:143
#16	0x00000001010443a8 in event_persist_closure at /Users/User/Developer/transmission/third-party/libevent/event.c:1623
#17	0x0000000101043874 in event_process_active_single_queue at /Users/User/Developer/transmission/third-party/libevent/event.c:1682
#18	0x000000010103d20c in event_process_active at /Users/User/Developer/transmission/third-party/libevent/event.c:1783
#19	0x000000010103be28 in event_base_loop at /Users/User/Developer/transmission/third-party/libevent/event.c:2006
#20	0x0000000100e019f8 in tr_session_thread_impl::sessionThreadFunc(event_base*) at /Users/User/Developer/transmission/libtransmission/session-thread.cc:239
#21	0x0000000100e03158 in decltype(*std::declval<tr_session_thread_impl*>().*std::declval<void (tr_session_thread_impl::*)(event_base*)>()(std::declval<event_base*>())) std::__1::__invoke[abi:v160006]<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/invoke.h:359
#22	0x0000000100e030cc in void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/thread:288
#23	0x0000000100e02d20 in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>>(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/thread:299
#24	0x0000000102349628 in _pthread_start ()

Thread 6#0	0x0000000182b4ce68 in __semwait_signal ()
#1	0x0000000182a2c2f8 in nanosleep ()
#2	0x0000000182abf81c in std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>> const&) ()
#3	0x0000000100edf9b4 in void std::__1::this_thread::sleep_for[abi:v160006]<long long, std::__1::ratio<1l, 1000l>>(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000l>> const&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/thread:387
#4	0x0000000100efa5bc in tr_web::Impl::curlThreadFunc() at /Users/User/Developer/transmission/libtransmission/web.cc:717
#5	0x0000000100efbae0 in decltype(*std::declval<tr_web::Impl*>().*std::declval<void (tr_web::Impl::*)()>()()) std::__1::__invoke[abi:v160006]<void (tr_web::Impl::*)(), tr_web::Impl*, void>(void (tr_web::Impl::*&&)(), tr_web::Impl*&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/__functional/invoke.h:359
#6	0x0000000100efba60 in void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>&, std::__1::__tuple_indices<2ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/thread:288
#7	0x0000000100efb70c in void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (tr_web::Impl::*)(), tr_web::Impl*>>(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include/c++/v1/thread:299
#8	0x0000000102349628 in _pthread_start ()

com.apple.NSEventThread (70)#0	0x0000000182b49874 in mach_msg2_trap ()
#1	0x0000000182b5bcf0 in mach_msg2_internal ()
#2	0x0000000182b524b0 in mach_msg_overwrite ()
#3	0x0000000182b49bf8 in mach_msg ()
#4	0x0000000182c67bf4 in __CFRunLoopServiceMachPort ()
#5	0x0000000182c664bc in __CFRunLoopRun ()
#6	0x0000000182c659ac in CFRunLoopRunSpecific ()
#7	0x000000018656c510 in _NSEventThread ()
#8	0x0000000102349628 in _pthread_start ()

Thread 98#0	0x0000000182b4b524 in __workq_kernreturn ()

Thread 99#0	0x0000000102353aac in start_wqthread ()
```

### Which application of Transmission?

macOS app

### Which version of Transmission?

4037726150b4e508d099a676440a99869b15c6a8

### PR DESCRIPTION
**Pull request by tearfur**
Fixes #6368.

### CODE REVIEW

**Comment by Coeur** [comment]
No regressions observed so far.

**Comment by Coeur** [comment]
@ckerr

1. Kindly merge this present PR early on: macOS users are recently experiencing frequent freeze/hang, and this PR seems the solution to it. I would even recommend back-porting it to 4.0.6 if that's relevant.
2. Then kindly merge #6364, otherwise many magnet links are unable to start, which is also a pain.
3. Then kindly merge #6321, otherwise the autosizing issue on macOS is causing the bottom controls (like Turtle mode) to be unreachable behind the Dock of the system.
4. Then kindly merge #5102, which is code-reviewed and approved
5. Then kindly look at #3926, which "looks like a low hanging fruit" according to latest comment.

Thank you

**Comment by Coeur** [comment]
Notes: fix some deadlocks situations, particularly on recent versions of macOS

**Comment by tearfur** [comment]
This deadlock was never released, so I think we don't need a release note here.

**Comment by Coeur** [comment]
OK, can you change the title and replace "refactor" with "fix"?
Seems that it was a regression introduced with #5329, and that started to surface with either ipv6 users or macOS 14.2.

**Pull request merged**
