### PR TITLE
refactor: use libpopcnt in bitfield + some misc cleanup

### PR DESCRIPTION
**Pull request by goldsteinn**
See: #2938 

Note this PR is based on [this PR](https://github.com/transmission/libpopcnt/pull/1) and expects the code to go on branch names `popcnt32`. See: https://github.com/goldsteinn/libpopcnt/tree/popcnt32

Without the changes to [tranmissions' libpopcnt](https://github.com/transmission/libpopcnt) this code does not work.

One more note, have an experimental branch that also changes the bitfield to use a larger underlying word type. I've tested on x86 but the serializing/deserializing functions (`setRaw`/`raw`) may have some issues, especially on systems with different byte orders so figure it better to just this patch out first and work up to extending word size later.

All tests either pass or are skipped:

```
[----------] 5 tests from Bitfield
[ RUN      ] Bitfield.count
[       OK ] Bitfield.count (711 ms)
[ RUN      ] Bitfield.ctorFromFlagArray
[       OK ] Bitfield.ctorFromFlagArray (0 ms)
[ RUN      ] Bitfield.setRaw
[       OK ] Bitfield.setRaw (0 ms)
[ RUN      ] Bitfield.bitfields
[       OK ] Bitfield.bitfields (0 ms)
[ RUN      ] Bitfield.hasAllNone
[       OK ] Bitfield.hasAllNone (0 ms)
[----------] 5 tests from Bitfield (712 ms total)
...
[ RUN      ] CompletionTest.createPieceBitfield
[       OK ] CompletionTest.createPieceBitfield (1 ms)
...
[----------] Global test environment tear-down
[==========] 270 tests from 37 test suites ran. (21320 ms total)
[  PASSED  ] 252 tests.
[  SKIPPED ] 18 tests, listed below:
[  SKIPPED ] JSON/JSONTest.testElements/1
[  SKIPPED ] JSON/JSONTest.testElements/2
[  SKIPPED ] JSON/JSONTest.testElements/3
[  SKIPPED ] JSON/JSONTest.testUtf8/1
[  SKIPPED ] JSON/JSONTest.testUtf8/2
[  SKIPPED ] JSON/JSONTest.testUtf8/3
[  SKIPPED ] JSON/JSONTest.test1/1
[  SKIPPED ] JSON/JSONTest.test1/2
[  SKIPPED ] JSON/JSONTest.test1/3
[  SKIPPED ] JSON/JSONTest.test2/1
[  SKIPPED ] JSON/JSONTest.test2/2
[  SKIPPED ] JSON/JSONTest.test2/3
[  SKIPPED ] JSON/JSONTest.test3/1
[  SKIPPED ] JSON/JSONTest.test3/2
[  SKIPPED ] JSON/JSONTest.test3/3
[  SKIPPED ] JSON/JSONTest.unescape/1
[  SKIPPED ] JSON/JSONTest.unescape/2
[  SKIPPED ] JSON/JSONTest.unescape/3
```

### CODE REVIEW

**Comment by goldsteinn** [comment]
Hi,

Just wondering if there is an issue with the approach (the test failures are ugly and all).

**Comment by GScottElshaw** [comment]
I thought i'd see how far i could get with the library...

'-- Configuring done
CMake Error: CMake can not determine linker language for target: libpopcnt
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.'

Feel free to grab anything from my fork if it's useful. https://github.com/GScottElshaw/transmission

I haven't found a way to edit the git modules in the repository, but locally is fine (I added a return at the end of the new entry). Lots of hit and miss cmake files editing, because i don't really know what i'm doing) to even get to this stage; and i've added libpopcnt to the .xcodeproj. Cheers.

**Comment by goldsteinn** [comment]
> I thought i'd see how far i could get with the library...

Hmm.

Any chance you guys have some usage data on the expected size of the bitfields? Unless expected size is > ~512-1024 there would be no need for the vectorized count implementations.

If thats the case it might just easier to write out own portable popcnt api.

> 
> '-- Configuring done CMake Error: CMake can not determine linker language for target: libpopcnt -- Generating done CMake Generate step failed. Build files cannot be regenerated correctly.'

Maybe the issue is related to [adding it as a library](https://github.com/GScottElshaw/transmission/commit/91763d0b94dc170ab7c3e78d2651197f4068f5de#diff-90266d9a3b54ba29da7797c85d78a1880fe2c99612b0bde1b0500d0746d5261dR1430) when in fact its just a header?

I don't have macos / no experience with xcode so can't say for certain.

> 
> Feel free to grab anything from my fork if it's useful. https://github.com/GScottElshaw/transmission
> 
> I haven't found a way to edit the git modules in the repository, but locally is fine (I added a return at the end of the new entry). Lots of hit and miss cmake files editing, (because i don't really know what i'm doing) to even get to this stage; and i've added libpopcnt to the .xcodeproj. Cheers.

The submodule stuff I added with just from:
```
git submodule add git@github.com:transmission/libpopcnt.git third-party/libpopcnt
```

Then added `popcnt32` branch for the changes to expose a 32-bit API

**Comment by ckerr** [comment]
I should have responded sooner, but I've been  kind of busy with non-Tranmsission things.

I appreciate the work of adding #2950 to the mix; but if we can figure out what's going wrong in this PR, my preference would be to use this one instead. The appeal to me is that if / when libpopcnt comes out with future bugfixes, we can draw them in just by bumping the submodule dependency instead of having to port them over into a bespoke header.

**Comment by ckerr** [comment]
Looks like we're pointing to an invalid commit?

```
git submodule update --init --recursive 
Submodule 'third-party/arc4' (https://github.com/transmission/arc4) registered for path 'third-party/arc4'
Submodule 'third-party/dht' (https://github.com/transmission/dht) registered for path 'third-party/dht'
Submodule 'third-party/fmt' (https://github.com/transmission/fmt.git) registered for path 'third-party/fmt'
Submodule 'third-party/googletest' (https://github.com/google/googletest.git) registered for path 'third-party/googletest'
Submodule 'third-party/libb64' (https://github.com/transmission/libb64) registered for path 'third-party/libb64'
Submodule 'third-party/libdeflate' (https://github.com/transmission/libdeflate) registered for path 'third-party/libdeflate'
Submodule 'third-party/libevent' (https://github.com/transmission/libevent) registered for path 'third-party/libevent'
Submodule 'third-party/libnatpmp' (https://github.com/transmission/libnatpmp) registered for path 'third-party/libnatpmp'
Submodule 'third-party/libpopcnt' (git@github.com:transmission/libpopcnt.git) registered for path 'third-party/libpopcnt'
Submodule 'third-party/libpsl' (https://github.com/transmission/libpsl.git) registered for path 'third-party/libpsl'
Submodule 'third-party/libutp' (https://github.com/transmission/libutp) registered for path 'third-party/libutp'
Submodule 'third-party/miniupnpc' (https://github.com/transmission/miniupnpc) registered for path 'third-party/miniupnpc'
Submodule 'third-party/utfcpp' (https://github.com/transmission/utfcpp) registered for path 'third-party/utfcpp'
Cloning into '/tmp/popcnt/transmission/third-party/arc4'...
Cloning into '/tmp/popcnt/transmission/third-party/dht'...
Cloning into '/tmp/popcnt/transmission/third-party/fmt'...
Cloning into '/tmp/popcnt/transmission/third-party/googletest'...
Cloning into '/tmp/popcnt/transmission/third-party/libb64'...
Cloning into '/tmp/popcnt/transmission/third-party/libdeflate'...
Cloning into '/tmp/popcnt/transmission/third-party/libevent'...
Cloning into '/tmp/popcnt/transmission/third-party/libnatpmp'...
Cloning into '/tmp/popcnt/transmission/third-party/libpopcnt'...
Cloning into '/tmp/popcnt/transmission/third-party/libpsl'...
Cloning into '/tmp/popcnt/transmission/third-party/libutp'...
Cloning into '/tmp/popcnt/transmission/third-party/miniupnpc'...
Cloning into '/tmp/popcnt/transmission/third-party/utfcpp'...
Submodule path 'third-party/arc4': checked out '6c8a5dd7e5e3fafcf0afef74cdf71f9d20cb9a54'
Submodule path 'third-party/dht': checked out '25e12bb39eea3d433602de6390796fec8a8f3620'
Submodule path 'third-party/fmt': checked out 'b6f4ceaed0a0a24ccf575fab6c56dd50ccf6f1a9'
Submodule path 'third-party/googletest': checked out 'af29db7ec28d6df1c7f0f745186884091e602e07'
Submodule path 'third-party/libb64': checked out '8456a5b5c99ef4544a2ed8e8f20a2fb673dd4192'
Submodule path 'third-party/libdeflate': checked out '0b8349a7ee3c5d6cb0def3c668a9079ce82af9b5'
Submodule path 'third-party/libevent': checked out 'e91a51eb5daba37418cc8426bd1f786f303ddbb1'
Submodule path 'third-party/libnatpmp': checked out '4d3b9d87bbe7549830c212ce840600619abcf887'
fatal: remote error: upload-pack: not our ref 677ecdd425a4494116b65571b16f08ad96efb5fb
fatal: Fetched in submodule path 'third-party/libpopcnt', but it did not contain 677ecdd425a4494116b65571b16f08ad96efb5fb. Direct fetching of that commit failed.
```

**Comment by goldsteinn** [comment]
> I should have responded sooner, but I've been kind of busy with non-Tranmsission things.
> 
> I appreciate the work of adding #2950 to the mix; but if we can figure out what's going wrong in this PR, my preference would be to use this one instead. The appeal to me is that if / when libpopcnt comes out with future bugfixes, we can draw them in just by bumping the submodule dependency instead of having to port them over into a bespoke header.

Okay, although it's worth keeping in mind that the main branch of `libpopcnt` will be inefficient  #2950 



> Looks like we're pointing to an invalid commit?
> 
> ```
> git submodule update --init --recursive 
> Submodule 'third-party/arc4' (https://github.com/transmission/arc4) registered for path 'third-party/arc4'
> Submodule 'third-party/dht' (https://github.com/transmission/dht) registered for path 'third-party/dht'
> Submodule 'third-party/fmt' (https://github.com/transmission/fmt.git) registered for path 'third-party/fmt'
> Submodule 'third-party/googletest' (https://github.com/google/googletest.git) registered for path 'third-party/googletest'
> Submodule 'third-party/libb64' (https://github.com/transmission/libb64) registered for path 'third-party/libb64'
> Submodule 'third-party/libdeflate' (https://github.com/transmission/libdeflate) registered for path 'third-party/libdeflate'
> Submodule 'third-party/libevent' (https://github.com/transmission/libevent) registered for path 'third-party/libevent'
> Submodule 'third-party/libnatpmp' (https://github.com/transmission/libnatpmp) registered for path 'third-party/libnatpmp'
> Submodule 'third-party/libpopcnt' (git@github.com:transmission/libpopcnt.git) registered for path 'third-party/libpopcnt'
> Submodule 'third-party/libpsl' (https://github.com/transmission/libpsl.git) registered for path 'third-party/libpsl'
> Submodule 'third-party/libutp' (https://github.com/transmission/libutp) registered for path 'third-party/libutp'
> Submodule 'third-party/miniupnpc' (https://github.com/transmission/miniupnpc) registered for path 'third-party/miniupnpc'
> Submodule 'third-party/utfcpp' (https://github.com/transmission/utfcpp) registered for path 'third-party/utfcpp'
> Cloning into '/tmp/popcnt/transmission/third-party/arc4'...
> Cloning into '/tmp/popcnt/transmission/third-party/dht'...
> Cloning into '/tmp/popcnt/transmission/third-party/fmt'...
> Cloning into '/tmp/popcnt/transmission/third-party/googletest'...
> Cloning into '/tmp/popcnt/transmission/third-party/libb64'...
> Cloning into '/tmp/popcnt/transmission/third-party/libdeflate'...
> Cloning into '/tmp/popcnt/transmission/third-party/libevent'...
> Cloning into '/tmp/popcnt/transmission/third-party/libnatpmp'...
> Cloning into '/tmp/popcnt/transmission/third-party/libpopcnt'...
> Cloning into '/tmp/popcnt/transmission/third-party/libpsl'...
> Cloning into '/tmp/popcnt/transmission/third-party/libutp'...
> Cloning into '/tmp/popcnt/transmission/third-party/miniupnpc'...
> Cloning into '/tmp/popcnt/transmission/third-party/utfcpp'...
> Submodule path 'third-party/arc4': checked out '6c8a5dd7e5e3fafcf0afef74cdf71f9d20cb9a54'
> Submodule path 'third-party/dht': checked out '25e12bb39eea3d433602de6390796fec8a8f3620'
> Submodule path 'third-party/fmt': checked out 'b6f4ceaed0a0a24ccf575fab6c56dd50ccf6f1a9'
> Submodule path 'third-party/googletest': checked out 'af29db7ec28d6df1c7f0f745186884091e602e07'
> Submodule path 'third-party/libb64': checked out '8456a5b5c99ef4544a2ed8e8f20a2fb673dd4192'
> Submodule path 'third-party/libdeflate': checked out '0b8349a7ee3c5d6cb0def3c668a9079ce82af9b5'
> Submodule path 'third-party/libevent': checked out 'e91a51eb5daba37418cc8426bd1f786f303ddbb1'
> Submodule path 'third-party/libnatpmp': checked out '4d3b9d87bbe7549830c212ce840600619abcf887'
> fatal: remote error: upload-pack: not our ref 677ecdd425a4494116b65571b16f08ad96efb5fb
> fatal: Fetched in submodule path 'third-party/libpopcnt', but it did not contain 677ecdd425a4494116b65571b16f08ad96efb5fb. Direct fetching of that commit failed.
> ```

This PR needs to be merged:
https://github.com/transmission/libpopcnt/pull/1

**Comment by goldsteinn** [comment]
> I should have responded sooner, but I've been kind of busy with non-Tranmsission things.
> 
> I appreciate the work of adding #2950 to the mix; but if we can figure out what's going wrong in this PR, my preference would be to use this one instead. The appeal to me is that if / when libpopcnt comes out with future bugfixes, we can draw them in just by bumping the submodule dependency instead of having to port them over into a bespoke header.

Alright (obv your the maintainer) but worth noting:

1. This patch expects a modified `libpopcnt` adding a 32-bit API so upgrading bugfixes will require a real merge.
2. The header in #2950 will likely be more efficient, especially on non x86_64 architectures.

**Comment by ckerr** [comment]
xpects a modified `libpopcnt` adding a 32-bit API so upgrading bugfixes will require a real merge (also AFAICT there is a bug currently in `libpopcnt` as the check for using `popcnt` doesn't ensure SSE. clang/GCC at least need more than just x86_64 to emit it: https://godbolt.org/z/7cGxGT8W6).
> 2. The header in [Refactor: use popcnt in bitfield and cleanup warnings #2950](https://github.com/transmission/transmission/pull/2950) will likely be more efficient, especially on non x86_64 architectures.

From what https://github.com/kimwalisch/libpopcnt#speedup says, it looks like the most gains are to be had when we feed libpopcnt a long array of bytes ... and that fits the hot paths of tr_bitfield pretty well. 7a46c30 attempts to use this span interface and the tests are passing on my machine, but I'm still new to this library and would like a second opinion -- does this approach make sense?

_If_ this is the right way to go, then migrating to `std::popcount` might not make sense in the future, since it maxes out at 64-bit widths

**Comment by ckerr** [comment]
I may have spoken too soon.

Looks like out-of-the-box libpopcnt [FTBFS on NetBSD](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_NetBSDAmd64/202721?showRootCauses=true&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=202721_1065_327.1065) due to naming conflicts with system functions, which could've been solved by namespacing the library, and our code that uses libpopcnt [returns inaccurate counts](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_GentooS390xCrossdev/202727?showRootCauses=true&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&showLog=202727_45116_2973.42896.45116) when run on Gentoo/s390x. The latter could probably be fixed with some careful #ifdeffing in bitfield.cc, but that still wouldn't solve the former problem.

Adding this library as a submodule dependency may be more trouble than it's worth.

**Comment by goldsteinn** [comment]
> xpects a modified `libpopcnt` adding a 32-bit API so upgrading bugfixes will require a real merge (also AFAICT there is a bug currently in `libpopcnt` as the check for using `popcnt` doesn't ensure SSE. clang/GCC at least need more than just x86_64 to emit it: https://godbolt.org/z/7cGxGT8W6).
> 
> > 2. The header in [Refactor: use popcnt in bitfield and cleanup warnings #2950](https://github.com/transmission/transmission/pull/2950) will likely be more efficient, especially on non x86_64 architectures.
> 
> From what https://github.com/kimwalisch/libpopcnt#speedup says, it looks like the most gains are to be had when we feed libpopcnt a long array of bytes ... and that fits the hot paths of tr_bitfield pretty well. [7a46c30](https://github.com/transmission/transmission/commit/7a46c30f8813a10204a8ef52e3bce455c9d32b53) attempts to use this span interface and the tests are passing on my machine, but I'm still new to this library and would like a second opinion -- does this approach make sense?
> 
> _If_ this is the right way to go, then migrating to `std::popcount` might not make sense in the future, since it maxes out at 64-bit widths

Got it. As long as larger bitfields are expectation then the vectorized API is the right call. There is a regression for smaller sizes.

**Comment by goldsteinn** [comment]
> I may have spoken too soon.
> 
> Looks like out-of-the-box libpopcnt [FTBFS on NetBSD](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_NetBSDAmd64/202721?showRootCauses=true&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&showLog=202721_1065_327.1065) due to naming conflicts with system functions, which could've been solved by namespacing the library, and our code that uses libpopcnt [returns inaccurate counts](https://trtc.mikedld.com/buildConfiguration/Transmission_Sanity_GentooS390xCrossdev/202727?showRootCauses=true&expandBuildChangesSection=true&expandchucktcpluginBuild=false&expandBuildProblemsSection=true&expandBuildTestsSection=true&showLog=202727_45116_2973.42896.45116) when run on Gentoo/s390x. The latter could probably be fixed with some careful #ifdeffing in bitfield.cc, but that still wouldn't solve the former problem.
> 
> Adding this library as a submodule dependency may be more trouble than it's worth.

What about #2950?

If not I can change the patch to only include the fixes for warnings (also LUT should be `uint8_t` not `size_t`)

**Comment by ckerr** [comment]
> What about #2950?

Yes, let's continue the discussion there.

**Pull request closed without merging**
