### PR TITLE
Use a map container to store peers in `tr_swarm`

### LINKED ISSUE #5610: transmission-daemon goes 100% cpu after some time
### What is the issue?

After a day or less `transmission-daemon` starts eating 100% of one core and responds to the Web UI very slowly. Restart fixes it. 

I'm building it from the source on Ubuntu 22, tried 4.0.3 and then just latest master, no changes.

Built using:
```
cmake .. -DENABLE_DAEMON=ON -DENABLE_GTK=OFF -DENABLE_QT=OFF -DENABLE_MAC=OFF -DINSTALL_WEB=ON -DINSTALL_DOC=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/transmission
```

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.3 and 0ef58c2a20019096aed0ab639f2207b8e1c1b248

### PR DESCRIPTION
**Pull request by tearfur**
(Partially? Hopefully?) fixes #5610.

1. To address the high CPU usage of `tr_swarm::get_existing_atom()`, the member `pool` of `tr_swarm` was changed from a dequeue to a map.
2. Refactored related functions to streamline function calls.

Notes: Made internal peer bookkeeping more efficient.

### CODE REVIEW

**Review by ckerr — CHANGES_REQUESTED** [review]
@tearfur looks like this PR is coupling two unrelated topics, the `std::map` use here and the followup to the atom+port PR. Could you move the second category into a standalone PRs?

**Comment by tearfur** [comment]
@ckerr Re-opened https://github.com/transmission/transmission/pull/5644#issuecomment-1599058398

**Comment by tearfur** [comment]
@ckerr PR's ready.

**Review by ckerr — APPROVED** [review]

**Comment by blind-oracle** [comment]
Works as expected I guess

**Comment by tearfur** [comment]
Look at the code again, there is really no need for `tr_swarm::get_existing_atom()` anymore when there is `std::map::find()`. Will remove it.

**Comment by tearfur** [comment]
@ckerr Just letting you know I did a small refactor to prevent traversing the `tr_swarm.swarm` twice in `tr_swarm::ensure_atom_exists()`.

**Review by ckerr — APPROVED** [review]

**Pull request merged**
