### PR TITLE
Update nl.po

### PR DESCRIPTION
**Pull request by gvmelle**
translated the non-translated strings with poedit

### CODE REVIEW

**Comment by ckerr** [comment]
@gvmelle thank you for the update!

Translations for Mac, Qt and GTK+ clients are managed on Transifex. To help localize, or add your new localization, you'll need to [register on Transifex and join the translation team](https://docs.transifex.com/getting-started/translators) for [Transmission project](https://www.transifex.com/transmissionbt/transmissionbt).

I'm going to close this PR because of the project's workflow: I don't want your changes to get overwritten the next time we sync translations in `transmission/transmission` from Transifex.

Please submit your changes there so that they don't get lost! Thanks!

**Comment by gvmelle** [comment]
No reaction on transiflex whatsoever. Ciao,Gideon~~o<#\,()/()Op 8 feb. 2023 om 18:19 heeft Charles Kerr ***@***.***> het volgende geschreven:﻿
@gvmelle thank you for the update!
Translations for Mac, Qt and GTK+ clients are managed on Transifex. To help localize, or add your new localization, you'll need to register on Transifex and join the translation team for Transmission project.
I'm going to close this PR because of the project's workflow: I don't want your changes to get overwritten the next time we sync translations in transmission/transmission from Transifex.
Please submit your changes there so that they don't get lost! Thanks!

**Comment by mikedld** [comment]
@gvmelle, I don't think I saw any requests from you, what's your username there?

**Comment by gvmelle** [comment]
DingoeCiao,Gideon~~o<#\,()/()Op 23 feb. 2023 om 12:07 heeft Mike Gelfand ***@***.***> het volgende geschreven:﻿
@gvmelle, I don't think I saw any requests from you, what's your username there?

**Comment by mikedld** [comment]
Transifex says that "Dingoe" is either a private profile or an account that doesn't exist, so I can't invite you myself. Since I don't remember seeing a join request from you, please try again and make sure you're requesting it in a proper project, i.e. https://www.transifex.com/transmissionbt/transmissionbt/.

**Comment by gvmelle** [comment]
I again clicked on join this project (transmission & transmission web control for Dutch nl. My mailaddress for GitHub and transfix is ***@***.*** username: Dingoe
Ciao,

Gideon

￼

**Pull request closed without merging**
