### PR TITLE
Delete macosx/Images/Images.xcassets/ActionOn.imageset and /QuitBadge.imageset directories

### PR DESCRIPTION
**Pull request by GaryElshaw**
Changes to TorrentCell.mm have made it redundant, i think.

Old version of TorrentCell.mm:
SCR-20220626-kmf

Current:
SCR-20220626-k7x

Also in this PR, deletion of QuitBadge. This has been redundant since https://github.com/transmission/transmission/pull/2495

### CODE REVIEW

**Review by sweetppro — APPROVED** [review]

**Comment by fxcoudert** [comment]
I think the overall diff is ok, but the individual commits are all over the place. Could you squash into a single commit?

**Comment by fxcoudert** [comment]
@GaryElshaw you've removed the `QuitBadge.imageset` directory but, like in the previous PR (https://github.com/transmission/transmission/pull/3361), haven't updated `macosx/CMakeLists.txt`.

Also, the comment above about squashing so the individual commits make sense still applies.

**Comment by GaryElshaw** [comment]
That was why we crossed wires in the previous PR, i think. I was saying that QuitBadge hasn't been in the CMakeLists file for several months, there is nothing to delete.

I don't understand what you mean about the individual commits being squashed.

**Comment by nevack** [comment]
> I don't understand what you mean about the individual commits being squashed.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing

**Comment by nevack** [comment]
> I was saying that QuitBadge hasn't been in the CMakeLists file for several months, there is nothing to delete. As i said previously, the directory is an orphan.

https://github.com/transmission/transmission/blob/main/macosx/CMakeLists.txt#L317

**Comment by GaryElshaw** [comment]
> > I don't understand what you mean about the individual commits being squashed.
> 
> https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing

I have advanced degrees in literature, i'm afraid that went over my head :-(

**Comment by nevack** [comment]
> > > I don't understand what you mean about the individual commits being squashed.
> > 
> > 
> > https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_squashing
> 
> I have advanced degrees in literature, i'm afraid that went over my head :-(

Basically you need :
1. `git fetch <origin> main` where `<origin>` is remote pointing to https://github.com/transmission/transmission
2. `git rebase -i <origin>/main`, where `-i` means interactively. This should open editor with list of commits and actions.
3.  Change `pick` to `squash` for every commit other than the first and close editor.
4. `git push --force <fork>`, where `<fork>` is remote, pointing to your fork https://github.com/GaryElshaw/transmission

**Comment by GaryElshaw** [comment]
`fatal: not a git repository (or any of the parent directories)`

My god how much i hate git when sleep-deprived.

**Pull request closed without merging**
