### PR TITLE
Set stock icon for speed, options and statistics buttons in qt

### LINKED ISSUE #2174: transmission-qt doesn't make full use of system icon set
transmission-qt uses built-in PNG icons for the status bar and a few other areas (encryption status).  These icons don't scale well and look bad compared to parts of the UI that do use system icons (menus, filterbar, status bar).  See screenshots for an example and a mockup of transmission using equatable system icons.

Built-in icons:
Screenshot_20211115_115057

System icons mockup:
Screenshot_20211115_185727

### PR DESCRIPTION
**Pull request by buckmelanoma**
This PR sets stock system icons for the alt-speed, options and statistics buttons on the status bar in transmission-qt, replacing the poorly scaled PNG icons when possible.  This essentially fixes #2174 

Screenshot_20211115_185727

### CODE REVIEW

**Comment by varlesh** [comment]
@buckmelanoma Please added for this PR another icon name for **Open URL** button. On Qt it's looking very ugly:
image
`addEmblem(icon_open, QStringList() << QStringLiteral("emblem-web") << QStringLiteral("applications-internet")));`
Emblems used for folders, but not for actiions icons on toolbar and overlay icons.
On all icon themes (Adwaita, Breeze, Faenza) available normal icon for that `insert-link`:
`ui_.action_AddURL->setIcon(getStockIcon(QStringLiteral("insert-link"), QStyle::SP_DesktopIcon));`

**Comment by buckmelanoma** [comment]
@varlesh I have a second PR in the works that fixes the menu and toolbar icons.  For AddUrl I think the proper icon is `document-open-remote`.

**Review by ckerr — CHANGES_REQUESTED** [review]
I agree with the problem and most of this PR, but have a soft spot for that turtle icon. It's been with Transmission from the very beginning on all platforms so I'd rather see it get replaced with a well-scaled / high-contrast friendly version of the same turtle.

Could you update this PR to leave the existing turtle (or, if you're a graphics artist, to update it with a better revision of it)?

**Comment by buckmelanoma** [comment]
I tried an upscale of the turtle in Krita but it didn't turn out too well.  I've updated PR to revert system override of the classic turtle.

**Comment by ckerr** [comment]
Thank you for trying!

Yeah, we will probably need to redo the image from scratch in svg.

**Review by ckerr — APPROVED** [review]

**Pull request merged**
