### PR TITLE
Added ability to filter on error status.

### PR DESCRIPTION
**Pull request by alimony**
This implements an error filter on the filter bar in the Mac client.

https://trac.transmissionbt.com/ticket/5460

### CODE REVIEW

**Comment by alimony** [comment]
Still looking for a review on this one…

**Comment by alimony** [comment]
Just rebased this on top of master again, anyone wants to have a look yet?

**Comment by alimony** [comment]
Still hoping for this to be reviewed someday…

**Comment by alimony** [comment]
Rebased on top of master.

**Comment by alimony** [comment]
Rebased on top of master.

**Comment by alimony** [comment]
Rebased again.

**Comment by alimony** [comment]
@ckerr I think this is a good candidate for a good first issue. I've kept it up to date since August 2016 and it should still be good to go. 🙂

**Comment by ckerr** [comment]
I appreciate the ping but I've done very little with the Mac client. Pinging @livings124 and @mikedld, both of whom have done much more on the Mac client than I have.

**Comment by ckerr** [comment]
I know how long this PR has been in limbo and am going through old, untouched PRs to try and get them either merged or closed. 

@alimony are you still interested in getting this landed; and if so, could you update this PR to resolve merge conflicts with the current codebase?

**Review by ckerr — COMMENTED** [review]
The code mechanics look alright to me, but I am definitely not the right person to review how UI changes in the Mac client feel to a Mac person.

No changes requested, but I don't feel comfortable approving this PR without signoff from a Mac person as well

**Comment by livings124** [comment]
Seems good to me, just needs a rebase to resolve conflicts (that's on me- sorry for the delay here).

**Comment by alimony** [comment]
I have some issues with the XIB file here, I'm gonna get this up and running on my new computer soon and will push another update to the PR.

**Comment by alimony** [comment]
OK, I've updated the PR so it builds properly, and tested the built client with the filtering. Should be all good to go now @ckerr @livings124

**Review by livings124 — APPROVED** [review]
Looks good. I would also add a note in NEWS.md

**Comment by alimony** [comment]
> Looks good. I would also add a note in NEWS.md

Should I add that as a separate commit in this PR, or as a separate PR once this has landed?

**Comment by livings124** [comment]
> > Looks good. I would also add a note in NEWS.md
> 
> Should I add that as a separate commit in this PR, or as a separate PR once this has landed?

I'd add it to this.

**Comment by alimony** [comment]
Thank you! Exciting to finally get this landed after more than six years :)

I also noted some missing end parentheses in NEWS, so you might want to fix those when adding the entries.

**Pull request merged**
