### PR TITLE
adding three missing transmission targets

### PR DESCRIPTION
**Pull request by Coeur**
Three executables were missing when building from Xcode:
- transmission-edit
- transmission-create
- transmission-show

### CODE REVIEW

**Comment by ckerr** [comment]
IDK how many macOS users will care about these command line utils, but sure why not :smile:

**Review by ckerr — APPROVED** [review]

**Comment by ckerr** [comment]
CC @DevilDimon even though this isn't really a code change :slightly_smiling_face:

**Comment by Coeur** [comment]
> IDK how many macOS users will care about these command line utils, but sure why not 😄

Developers need the targets for awareness of code dependencies and code analysis. Example: I had to do a change to show.cc in #2914, which I missed originally due to the absence of target.

**Comment by GScottElshaw** [comment]
I always thought these were unavailable for MacOS; well, well, well.... Thanks @Coeur

**Pull request merged**
