### PR TITLE
WebUI: Progress bar colour changes

### PR DESCRIPTION
**Pull request by GaryElshaw**
Part of an effort to unify the colours across clients. More discussion in #5648.

Down/seeding colours now have parity with macOS client, and the high contrast ui is almost exclusively B&W.

Dark theme

Screenshot from 2023-07-28 09-20-00-obfuscated

Light theme

Screenshot from 2023-07-28 09-21-24-obfuscated

Dark style high contrast ui

Screenshot from 2023-07-28 08-20-33-obfuscated

Light style high contrast ui

Screenshot from 2023-07-28 08-22-13-obfuscated

### CODE REVIEW

**Comment by Pentaphon** [comment]
screenshots?

**Comment by tearfur** [comment]
Disclaimer: Not an UI guy.

The lighter green colour from your screenshot looks quite bright. The same same colour in GTK is much more faint. 🤔

**Comment by GaryElshaw** [comment]
> Disclaimer: Not an UI guy.
> 
> The lighter green colour from your screenshot looks quite bright. The same same colour in GTK is much more faint. thinking

I spent a massive amount of time today in the GTK client trying to get things working, and they're just not :-( I have 5 different versions of TorrentCellRenderer.cc (hex, rgb, rgba, named colours) that will compile, but make zero changes or just have the default silver in place. It's heart-breaking, really, so i've made the ostensible changes to GTK in the pr draft.

My background is web, graphics and ui design - i'm not actually a coder, but are reasonably good, sometimes, at working things out when i get _determined_.

Yep, the colours in the web client are a little in flux today while I try to find the right foreground and background combination that best resembles the macOS client values.

**Comment by Rukario** [comment]
The green shades of finished and unfinished pieces are a little too close to each other. May I suggest the unfinished pieces to be near-transparent white.

**Comment by Pentaphon** [comment]
> The green shades of finished and unfinished pieces are a little too close to each other. May I suggest the unfinished pieces to be near-transparent white.

@GaryElshaw I have to agree with this, but the unfinished part should be a paler shade of green or the finished part a bolder shade of green. Especially considering the length of the bar.

**Comment by GaryElshaw** [comment]
So the previous version that ha more contrast? @Pentaphon @Rukario  https://github-production-user-asset-6210df.s3.amazonaws.com/69029666/253170301-bf000748-5b4e-42df-a5f6-92859d857b6e.png

**Comment by Pentaphon** [comment]
> So the previous version that had more contrast?

Yeah that seemed like it had better contrast. 

How about the blue and red colors?

**Comment by GaryElshaw** [comment]
The blue makes me think the conrast from the macOS client is sufficient. 

Screenshot from 2023-07-16 17-57-13-obfuscated

**Comment by Pentaphon** [comment]
> The blue makes me think the conrast from the macOS client is sufficient.

You may be right, but you can always just change the selection color to whatever you want. It's more important to see what the blue (downloading) and red (magnetizing) progress bars look like with the rest of the webui.

**Comment by GaryElshaw** [comment]
Screenshot from 2023-07-16 18-17-28-obfuscated

Screenshot from 2023-07-16 18-17-37-obfuscated

**Comment by Pentaphon** [comment]
Gary, not sure if you agree, but I think the bold blue selection color is "overpowering" the rest of the fairly muted dark WebUI, especially the Blue downloading progress bar, so that may have to be changed as well. Perhaps a light shade of grey? What would the selection color be on the Mac client in dark mode? I don't have a Mac, but I think the Mac client gets the most attention UI-wise and would be your reference point for changing other colors to harmonize with the unified progress bar colors you are bringing from the Mac client to all the other clients. 

Otherwise, the Blue progress bar on that screenshot looks great. I hope more people get a look at this progress bar color unification progress so people can see where it is going. Whoever did the Mac client had good instincts to make more use of the rather large progress bar it has compared to other clients.

**Comment by GaryElshaw** [comment]
I've added highere contrast to the greens in the High Contrast UI option. The colours in the web ui are the macOS client colours.

Screenshot 2023-07-16 at 1 13 15 PM-obfuscated

Screenshot 2023-07-16 at 1 18 42 PM

**Comment by GaryElshaw** [comment]
High contrast ui option.

Screenshot from 2023-07-16 19-07-52-obfuscated

**Comment by Pentaphon** [comment]
I've added higher contrast to the greens in the High Contrast UI option. 

Looking great. I especially like the white outline you added around the progress bar for some added "pop".

>The colours in the web ui are the macOS client colours.

Ah, forgive my ignorance then. Glad we have a Mac guy like you to make all this happen.

**Comment by Rukario** [comment]
I'm not sure how those other colors came to be, they look a little too toned down and boring.

rgba(255, 255, 255, 0.1) is near-transparent white. Use it where the bright green would've been. I don't think the unfinished pieces should be colored at all, but if it needs to be then try 0.1 opacity of the finished piece color.

**Comment by Pentaphon** [comment]
> I'm not sure how those colors came to be, they look a little too toned down and boring.

Gary says they came from the Mac client. Not everybody may like them but just the fact that all the UI's (this one being the web client) are getting the Mac progress bar colors is something that is long overdue. Besides, if the community wants to, we can just tweak the colors later if need be. Maybe open up a discussion to see what other people think?

**Comment by Rukario** [comment]
Didn't realized there's screenshot immediately above that is Mac client, I thought it's part of web UI. It seems there's UI variation of Mac clients as I've seen a better screenshot...

**Comment by dareiff** [comment]
OK, looking at it now locally. 

First, your css changes are totally fine.

Dark mode, default web (not high contrast): good, except for the selected-torrent color. (Too out of place, too bright)
Light mode, default web (not high contrast): good, can’t even read it with the selected-torrent color.
Screenshot 2023-07-27 at 8 29 45 AM

High contrast modes: I don’t think these downloading colors are high contrast in light mode. They can kind of work in dark mode. Have we ran a contrast checker on them? Since the Mac client doesn’t have a high contrast mode, perhaps we _should_ just use something like the Dracula theme (https://github.com/transmission/transmission/issues/4304#issuecomment-1633741665) since we don’t need to specifically match the client.

**Comment by GaryElshaw** [comment]
@dareiff Reverted the highlight colours and took the high contrast to the logical(?).

**Comment by dareiff** [comment]
> @dareiff Reverted the highlight colours and took the high contrast to the logical(?).

Do you have screenshots before I pull and update locally?

**Comment by GaryElshaw** [comment]
Screenshot from 2023-07-28 07-31-32-obfuscated

**Comment by Rukario** [comment]
Never liked the yellow so any changes to it is a good change! The final screenshot looked better although it'll probably need to borrow contrast's style (1st pic) before it starts to be a legibility problem on a blue background.

Alternatively the yellow could become more orange. Visual Studio seems to have it #F5CC84

**Comment by GaryElshaw** [comment]
Dark style high contrast ui

Screenshot from 2023-07-28 08-03-29-obfuscated

**Comment by Rukario** [comment]
Would you provide a screenshot for non-high-contrast colors again? The high-contrast UI looks good!

**Comment by GaryElshaw** [comment]
Sure thing.

Screenshot from 2023-07-28 09-20-00-obfuscated

Screenshot from 2023-07-28 09-21-24-obfuscated

**Comment by Rukario** [comment]
Hmm, it could be better. The blue highlight is the only improvement. Problems remain:

> The green shades for finished vs unfinished pieces are still having problem too close to each other.
> The somewhat of a legibility problem for text on a blue background.

There are several other visual problems but I think that'll be for a separate PR e.g. icons.

**Comment by GaryElshaw** [comment]
cc @dareiff

**Comment by dareiff** [comment]
Not that it matters too much here, but I see seeding progress levels as a little more background than other progress bars. As in: being slightly more similar to each other is fine, and they should blend in a bit more?
Not necessarily a hard stance I’m taking, just the thought when choosing colors in the first place.
But I defer to others here!

**Comment by GaryElshaw** [comment]
Do you think it's an improvement?

**Comment by dareiff** [comment]
I like it! 

(Sorry, I tend to go straight to the last reply on these.)

**Comment by GaryElshaw** [comment]
No worries!

**Pull request merged**
