### PR TITLE
MacOS lock icon

### PR DESCRIPTION
**Pull request by GaryElshaw**
A native MacOS lock icon.

SCR-20220529-s60

SCR-20220529-s5m

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Next steps:

1. A lock icon for the top of the table
2. An unlock icon for unencrypted peers

**Comment by GaryElshaw** [comment]
@ckerr Charles, can you please merge this and #3148 so i can work on next steps?

**Comment by GaryElshaw** [comment]
@sweetppro Playing around with some builds and wondered what it would look like if encrypted peers might have a different visual representation instead of a lock.

SCR-20220529-5cu

**Comment by GaryElshaw** [comment]
An update with how it looks in practice.

SCR-20220529-nve

**Comment by ckerr** [comment]
> @ckerr Charles, can you please merge this and #3148 so i can work on next steps?

No; I can't test this firsthand and there are no other reviews or approvals from macOS contributors. As I've said in other PRs I'm very hesitant to merge look-and-feel changes, particularly macOS ones, without reaching some consensus.

**Comment by ckerr** [comment]
> @ckerr Charles, can you please merge this and #3148 so i can work on next steps?

No; I can't test this firsthand and there are no other reviews or approvals from macOS contributors. As I've said in other PRs I'm very hesitant to merge look-and-feel changes, particularly macOS ones, without reaching some consensus.

**Pull request closed without merging**
