### PR TITLE
Refresh web interface across desktop and mobile

### PR DESCRIPTION
**Pull request by dareiff**
Almost all functionality stays the same, but some outdated colors and icons get updates. 

It should be noted! I don't consider myself a designer, but I'm pretty pleased with the current state of the UI. There are a few colors I'd like to nail down (some grays/blacks are darker than I'd like, notably outlines) and icons to potentially update, but this is a great start that could use some eyes. Several older issues could be closed with this PR, too.

- https://github.com/transmission/transmission/issues/3895
- https://github.com/transmission/transmission/issues/3894
- https://github.com/transmission/transmission/issues/3893
- https://github.com/transmission/transmission/issues/3834
- https://github.com/transmission/transmission/issues/3983

## In this PR:

- move toolbar icons over to [feather icons.com](https://feathericons.com)
  - these icons are MIT, and look great
  - the `i` icon in the toolbar was a simple graphic by me
- move from gradients to flatter design
- move older segmented controls to flatter design
- moved some icons from the app to the web (turtle being one)
- pulled down bigger sizes of torrent-type icons
- I'm sure I've missed a few potential ui variants (torrent errors, for example)
- updated IMG README as best as I could
- updated packages
- moved from icons to text for most segmented controls (tabs)

## Suggestions

- move file type icons to https://feathericons.com
  - I think there's an icon for each type..

## Negatives:

- transmission-app.js is 200kb bigger than the previous version (related to picking bigger file-type icons)
  - in my opinion, this isn't a huge deal (see suggestions above)
- I'd like to further nail down exact styles for both light and dark modes. Currently, I'm picking and choosing from a palette.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Exciting! Can you please include some screenshots @dareiff

**Comment by dareiff** [comment]
> Exciting! Can you please include some screenshots @dareiff

Sure! I'm considering backing out the icon changes, but this is the current interface:

Screenshot 2022-10-18 at 1 42 13 PM
Screenshot 2022-10-18 at 1 42 19 PM
Screenshot 2022-10-18 at 1 42 21 PM
Screenshot 2022-10-18 at 1 42 28 PM
Screenshot 2022-10-18 at 1 42 32 PM
Screenshot 2022-10-18 at 1 42 35 PM

**Comment by nevack** [comment]
> > Exciting! Can you please include some screenshots @dareiff
> 
> Sure! I'm considering backing out the icon changes, but this is the current interface:

This is really great, also much more accessible with improved contrast.
BTW, next time hide screenshots under Spoiler/Collapsible content (you still can edit your comment :smiley:)

**Comment by ckerr** [comment]
This looks pretty great. The code looks fine, the documentation is updated, and even the deps got bumped.

I'm not sure about embedding svg images into index.html -- sems like it would be more flexible to put those in assets/ and let webpack bundle them together?

**Comment by dareiff** [comment]
> This looks pretty great. The code looks fine, the documentation is updated, and even the deps got bumped.
> 
> I'm not sure about embedding svg images into index.html -- sems like it would be more flexible to put those in assets/ and let webpack bundle them together?

Yeah, I thought about that, but they're pretty small, size-wise, and I'm using fill colors in css to change path and fill depending on color-pref (light/dark modes). I _think_ I could maybe use them masked, but this was easier. Happy to look into it, of course.

**Comment by ckerr** [comment]
some new stylelint warnings:

```
$ stylelint --fix assets/css/*scss

assets/css/transmission-app.scss
   20:1   ✖  The variable "$purple-000" is not referenced.     primer/no-unused-vars                     
   21:1   ✖  The variable "$purple-100" is not referenced.     primer/no-unused-vars                     
   30:1   ✖  The variable "$subtle-bt-red" is not referenced.  primer/no-unused-vars                     
  466:9   ✖  --color-fg-name is not defined                    primer/no-undefined-vars                  
  557:7   ✖  --color-fg-name is not defined                    primer/no-undefined-vars                  
 1091:3   ✖  --default-border is not defined                   primer/no-undefined-vars                  
 1496:11  ✖  Unexpected value "none" for property "border"     declaration-property-value-disallowed-list
```

**Comment by dareiff** [comment]
> some new stylelint warnings:
> 
> ```
> $ stylelint --fix assets/css/*scss
> 
> assets/css/transmission-app.scss
>    20:1   ✖  The variable "$purple-000" is not referenced.     primer/no-unused-vars                     
> ```

Thanks for that! I had not been running lint. All good to go, in my opinion, for merging and more eyes!

**Comment by ckerr** [comment]
@dareiff thanks again for this PR! :green_heart:

**Comment by TorsteinVin** [comment]
@dareiff I'm so excited for this! The new webui looks amazing and modern, and follows @ckerr idea that it should be OS-independent. Any ETA for when beta2 with this webui will be available?

**Comment by 1100101** [comment]
I'm getting make errors when trying to build Transmission after this PR was pushed:
```
make[2]: *** No rule to make target 'web/assets/img/team.svg', needed by 'web/CMakeFiles/trweb'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:1589: web/CMakeFiles/trweb.dir/all] Error 2
```
The PR removed a couple of image assets, but these images remain listed in the `CMakeLists.txt`.


Note to @ckerr: It seems the CI jobs do not build the `trweb` code, otherwise they would've run into the same issue.

**Comment by dareiff** [comment]
> I'm getting make errors when trying to build Transmission after this PR was pushed:
> 
> ```
> make[2]: *** No rule to make target 'web/assets/img/team.svg', needed by 'web/CMakeFiles/trweb'.  Stop.
> make[1]: *** [CMakeFiles/Makefile2:1589: web/CMakeFiles/trweb.dir/all] Error 2
> ```
> 
> The PR removed a couple of image assets, but these images remain listed in the `CMakeLists.txt`.
> 
> Note to @ckerr: It seems the CI jobs do not build the `trweb` code, otherwise they would've run into the same issue.

On it! Sorry about that - thought I had gotten that file in alignment with what I removed.

**Comment by GaryElshaw** [comment]
This is really lovely work @dareiff. Mostly on macOS, I often drift between platforms and noticed this on Ubuntu, and laying this at their feet, i think. Notice how the '1' is rendered?

Screenshot from 2022-10-23 13-49-39

**Comment by dareiff** [comment]
> This is really lovely work @dareiff. Mostly on macOS, I often drift between platforms and noticed this on Ubuntu, and laying this at their feet, i think. Notice how the '1' is rendered?

Interesting — wonder which version of Ubuntu you’re on, and whether you have the Ubuntu system font.

Here’s mine: 
Screenshot 2022-10-22 at 6 17 32 PM

I just updated this server to 22.10, and the Ubuntu font is present (and presumably I haven't changed anything on this system).

**Comment by GaryElshaw** [comment]
I'm using the Kinetic beta, and that was on Firefox; i haven't messed with any of the default fonts (as of yet!).

**Comment by trippleflux** [comment]
```
ninja: error: 'web/assets/img/analytics.svg', needed by 'web/CMakeFiles/trweb', missing and no known rule to make it
```
Missing, should I delete it from CMakeLists.txt ?

**Pull request merged**
