### PR TITLE
White chevrons for Light theme web ui

### PR DESCRIPTION
**Pull request by GaryElshaw**
Some white chevron icons for someone along the line. I noticed tonight that the default chevrons in the web ui are black. That's not so great when in Dark mode. 

If you have some time, @dareiff? 

image

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Not sure why Solaris would object to no-code-change addition of two svg's?

**Comment by dareiff** [comment]
Was there an issue for this already? I’ll work on it today!

**Comment by dareiff** [comment]
I implemented this in a css way here:

Add readme with light setup instructions; minor UI tweaks #5814

**Comment by GaryElshaw** [comment]
Closing in favour of #5814

**Pull request closed without merging**
