### PR TITLE
Added snap package support for transmission-daemon

### PR DESCRIPTION
**Pull request by simos**
*Snap packages* is one of the new package format that runs on many Linux distrubutions and also developer boards like the Raspberry Pi. They provide confinement of the snapped package and work especially well with Ubuntu Core. Confinement is good, because if somehow the daemon is compromised, it will not affect the rest of the system.

This PR has the configuration file for a snap specifically for the *transmission-daemon*.
To create the snap package yourselves: 

1. Install snap support, if your Linux distro does not have it already (https://docs.snapcraft.io/core/install)
2. Install the *snapcraft* snap creation tool, with `sudo snap install snapcraft --classic`
3. Enter the _transmission_ directory and run `snapcraft`. This will generate the snap package *transmission-daemon_2.94_amd64.snap*. (To clean up, run `snapcraft --clean`)
4. You can then publish this snap to the Ubuntu Snap Store. See some instructions at https://tutorials.ubuntu.com/tutorial/create-your-first-snap

I went ahead and published an unofficial snap for `transmission-daemon`, and you can test it now.

`sudo snap install transmission-daemon-simosx`     (only for `amd64`)

Then, you can run all the _daemon_ commands like this:
`transmission-daemon-simosx.transmission-daemon`
It looks a bit awkward with the repetition, but this happens because it's an unofficial snap (note the -`simosx`). The PR has the proper name so that you can run straight away `transmission-daemon`.

A note on confinement: The snap has `strict` confinement, which means that it is very much confined and can only access 1) the home directory and any mounted partitions, 2) can make connections to the Internet, 3) can bind to network ports.

The rest of the utilities (like `transmission-create`) have no access to the network.

### CODE REVIEW

**Comment by simos** [comment]
The error on target _Gentoo/x86_64 (glibc)_ is not related to this pull request.

**Comment by simos** [comment]
Here are the adoption stats of my unofficial transmission-daemon snap package
https://snapcraft.io/transmission-daemon-simosx

There are people interested in such a snap package. Once you add this pull request,
and then make your official snap package for tranmission-daemon, I am happy to remove my unofficial version.

**Comment by albertodonato** [comment]
Hi @simos, I have some additinonal changes on top of your PR on [this branch].(/albertodonato/transmission/tree/snap-transmission-daemon)
Would you consider merging them to yours?

These are the changes:
 - base the snap on `core18` (the new core based on Ubuntu 18.04)
 - add configuration hook and a few config options via `snap config`
 - renamed the commands so that you don't have "transmission" twice in the name.
 - added the `transmission-remote` command as well

Also, the snap is now built (and versioned) on the current tree. This is useful for instance for automatically building and pushing the snap (for intance to the edge channel) on build.snapcraft.io.

**Comment by albertodonato** [comment]
@mikedld hi, could this PR be merged?

**Comment by simos** [comment]
@albertodonato I merged your commits to my branch.

@mikedld Can you please look into this?

**Comment by mikedld** [comment]
I have some stuff I've been working on during recent SnapCraft summit last year, based in part on what you guys have here, will look into merging everything in in a few days.

**Comment by albertodonato** [comment]
FTR it's now possible to build `core18`-based snaps on build.snapcraft.io now, so it'd be nice to switch to the new base (as it provides more recent dependencies)

**Comment by simos** [comment]
> @simos, thank you for working on this! I'd be happy to have transmission-daemon support snaps out-of-the box.
> 
> This patch has a lot of seemingly-unrelated changes in it, e.g. changes to the mac code that shouldn't be needed for transmission-daemon.
> 
> If that's intentional, could you write up in the PR why these changes are necessary?
> 
> If it's not intentional -- I suspect this is the case -- could you update this PR to only include the changes necessary for snapification?
> 
> Thanks!

Hi @ckerr,

How do I clean up the PR from the indeed unintended changes?
Is there a way to clean everything up and start over? 
In order the add in the changes from @albertodonato I ended up doing a `git push --force`. Which is not supposed to be good on PRs. 
I googled on this but did not a definitive answer. If there is a link on this, I'll gladly follow it.

**Comment by albertodonato** [comment]
@simos I think your best bet is to create another branch, cherry-pick the relevant commits from this one (yours and mine) and then force-push it over the current one

**Comment by albertodonato** [comment]
@simos @ckerr I cherry-picked the relevant commits on top of the current master to https://github.com/albertodonato/transmission/tree/snap-test

@simos I think you could do the following to update this PR:

```
git remote add alb https://github.com/albertodonato/transmission
git fetch alb
git co snap-test
git push --force origin snap-test:snap-transmission-daemon
```

This will force-update your branch with the cherry-picked commits

**Comment by simos** [comment]
@albertodonato I performed the commands that you listed above. 
From looking at the image from `gitg`, I think the issue has been resolved. 
@ckerr Can you please check that those unrelated commits are not gone from the branch?

**Comment by albertodonato** [comment]
@ckerr @mikedld any chance this could be merged?

**Comment by albertodonato** [comment]
hi, any update on snap packaging for transmission?

**Comment by ckerr** [comment]
I know how long this PR has been in limbo and am going through the PRs to try and reduce the project's PR backlog.

@simos, @albertodonato, is this PR still up-to-date with how snap does things? That is, could this PR be merged?

**Comment by albertodonato** [comment]
It'd be good to move the snap to the `core20` base at least, since it's the current one.

**Comment by ckerr** [comment]
I'm closing this PR for the same reasons I declined the [flatpak package](https://github.com/transmission/transmission/issues/64) -- the maintainer team is small and doesn't have either the bandwidth or the domain expertise to maintain this, so it probably shouldn't go in `electron/electron`. I love the idea of having more ways for people to get & use Transmission, I just don't want to have to maintain it.

If there is a maintained third-party package, please make a PR in the `transmission/transmission` [docs](https://github.com/transmission/transmission/blob/main/docs/README.md) adding a link to it so that users will be more able to find it. Thank you!

**Pull request closed without merging**
