### PR TITLE
Reworked images for Message Log w/ added bonus 'Empty' Group icon

### PR DESCRIPTION
**Pull request by GaryElshaw**
I was never particularly happy with the last lot of images i created, particularly the outer edges, so an update. I've also included White and Grey icon sets for any future project needs.

With #3065 a new circular 'Empty' icon was needed for Group.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
@mikedld Mike, could you give some TLC to TC please?

**Comment by Coeur** [comment]
This PR is, presently, a combination of two changes:
1. `GroupsNoneTemplate.png`, which is the empty group icon;
2. `*DotFlat.png`, which are the message logs icons (which users rarely visit).

One issue from the usage of .png files is that it's not ideal for supporting both light mode and dark mode.
Considering the uniform content of those icons, I feel we can simply render them programmatically.

**Comment by GaryElshaw** [comment]
Sheesh Antoine, thanks for minimising my contributions :-(

**Comment by Coeur** [comment]
Hi @GaryElshaw 
Thanks to you, I'm discovering features and ways to improve them.
I'll give a try to the icons generation.

**Comment by GaryElshaw** [comment]
@Coeur I totally agree with you that this would be great if it was done in code, especially for the OS versions with Light and Dark options. Which raises a discussion i've wanted to have with contributors and maintainers alike for a while, because i have too much time on my hands...

**Pull request closed without merging**
