### PR TITLE
fix: build when compiling with GTKMM-4

### LINKED ISSUE #6392: 4.0.5 fails to build with gtkmm-4
### What is the issue?

Hello,

I am trying to build Transmission 4.0.5 within the GNU Guix package management system.

It fails to build with these error messages:

```
[ 86%] Building CXX object tests/libtransmission/CMakeFiles/libtransmission-test.dir/handshake-test.cc.o
cd /tmp/guix-build-transmission-4.0.5.drv-0/build/tests/libtransmission && /gnu/store/5lqhcv91ijy82p92ac6g5xw48l0lwwz4-gcc-11.3.0/bin/c++ -DFMT_EXCEPTIONS=0 -DFMT_HEADER_ONLY=1 -DHAVE_GETTEXT -DHAVE_NGETTEXT -DLIBTRANSMISSION_TEST_ASSETS_DIR=\"/tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/tests/libtransmission/assets\" -D__TRANSMISSION__ -I/tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/libtransmission/.. -I/tmp/guix-build-transmission-4.0.5.drv-0/build/libtransmission/.. -isystem /tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/cmake/../third-party/fmt/include -isystem /tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/third-party/googletest/googletest/include -isystem /tmp/guix-build-transmission-4.0.5.drv-0/build/third-party/dht.bld/pfx/include -isystem /tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/cmake/../third-party/wide-integer -O2 -g -DNDEBUG -W -Wall -Wextra -Wcast-align -Wduplicated-cond -Wextra-semi -Wfloat-equal -Winit-self -Wint-in-bool-context -Wlogical-op -Wmissing-format-attribute -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wredundant-move -Wrestrict -Wshadow -Wsign-compare -Wsuggest-override -Wuninitialized -Wunreachable-code -Wunused -Wunused-const-variable -Wunused-parameter -Wunused-result -Wwrite-strings -Wno-sign-compare -std=gnu++17 -MD -MT tests/libtransmission/CMakeFiles/libtransmission-test.dir/handshake-test.cc.o -MF CMakeFiles/libtransmission-test.dir/handshake-test.cc.o.d -o CMakeFiles/libtransmission-test.dir/handshake-test.cc.o -c /tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/tests/libtransmission/handshake-test.cc
In file included from /tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/gtk/OptionsDialog.cc:10:
/tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/gtk/OptionsDialog.cc: In member function ‘void TorrentFileChooserDialog::onOpenDialogResponse(int, Glib::RefPtr<Session>&)’:
/tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/gtk/OptionsDialog.cc:341:38: error: ‘get_files2’ was not declared in this scope; did you mean ‘get_files’?
  341 |         auto const files = IF_GTKMM4(get_files2, get_files)();
      |                                      ^~~~~~~~~~
/tmp/guix-build-transmission-4.0.5.drv-0/transmission-4.0.5/gtk/GtkCompat.h:42:41: note: in definition of macro ‘IF_GTKMM4’
   42 | #define IF_GTKMM4(ThenValue, ElseValue) ThenValue
      |                                         ^~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-exit-time-destructors’ may have been intended to silence earlier diagnostics
make[2]: *** [gtk/CMakeFiles/transmission-gtk.dir/build.make:353: gtk/CMakeFiles/transmission-gtk.dir/OptionsDialog.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

We are using gtkmm 4.6.1 with GTK 4.8.1.

Please let me know if I can provide any more information, assist with debugging, etc.

### Which application of Transmission?

GTK+ app on Linux, BSD, etc.

### Which version of Transmission?

4.0.5

### PR DESCRIPTION
**Pull request by Coeur**
Fix #6392

### CODE REVIEW

**Comment by mikedld** [comment]
This makes no sense, at least not in `main` — as noted by @GaryElshaw, minimum is 4.11.1 so checking for 4.10 is pointless. If applicable to `4.0.x` (where minimum is lower), feel free to retarget.

**Comment by Coeur** [comment]
@mikedld retarget done

**Comment by GaryElshaw** [comment]
@Coeur Yep, this needs to be done on the 4.0 branch. This is from the 4.1 branch, i'm wondering if those 3 and 4 designations need to be included in the 4.0 branch cmakelists file.

`set(GTKMM3_MINIMUM 3.24.0)
set(GTKMM4_MINIMUM 4.11.1)`

**Comment by mikedld** [comment]
`get_files()` in 4.0-4.10 returns a model, not a vector, so IIUC this won't compile. I thought we had `get_files2()` reverted in `4.0.x`, looking at #6144, why would it still be there?..

**Comment by mikedld** [comment]
I think @ckerr may have unnecessarily cherry-picked https://github.com/transmission/transmission/commit/bd31d805003909bd5927f26a02eb60b78a82355b (seeing how there was no PR and the one referred to in commit subject line is against `main`), reverting it should do the trick.

**Comment by ckerr** [comment]
@mikedld yes, agreed. I think I goofed that one.

**Review by mikedld — APPROVED** [review]

**Comment by ckerr** [comment]
Notes: Fixed build when compiling with GTKMM 4.

**Pull request merged**
