### PR TITLE
Add labels support into web client.

### PR DESCRIPTION
**Pull request by vchimishuk**
Implementation adds next features:

1. Display labels in torrents list. Both compact and non-compact modes are supported. Labels are separated by comma and prefixed with label emoji.
labels-list-non-compact
labels-filter

2. Display labels in torrent inspector. New `Labels:` item has been added into `Details` section.
labels-inspector

3. Adds `labels` keyword into filter. Filter input box allows user to filter torrents by labels. To do that search language has been extended with `labels` keyword. Syntax is pretty standard: `[labels:label1,[label2,[label3,...]][ text to search]`.
Some examples:
* `labels:foo,bar` -- search for torrents having both labels `foo` and `bar`.
* `labels:foo bar` -- search for torrents having label `foo` and containing text `bar` in name.   

labels-filter

4. Adds `Set Labels...` menu item and `Set torrent labels` dialog. Using context menu in torrents list user can call dialog window to edit labels list. Input is a comma-separated list of labels.
labels-menu
labels-dialog

### CODE REVIEW

**Comment by vchimishuk** [comment]
@mikedld, is there any chance this PR can be merged (sure, after conflicts resolution) into master? I use this code for the last year it it looks stable and convenient. Labels is a great feature and it will be good if we can have it out of the box.

**Comment by LaserEyess** [comment]
@vchimishuk are you interested in rebasing this? It would likely get a review at the very least, and has a high chance of being merged since it reduces feature disparity between clients.

**Comment by vchimishuk** [comment]
@LaserEyess, it would be great. I just need to find some time to do it. Let's say 1-2 weeks. I'll get back when it will be ready.

**Comment by GScottElshaw** [comment]
Any news on this @vchimishuk?

**Comment by vchimishuk** [comment]
@GScottElshaw , yes. I'm almost done. Looks like the only thing is left for me is CSS part. I'll try to spend some evening and finish it during this week.

**Comment by vchimishuk** [comment]
@LaserEyess , @GScottElshaw, I've updated PR. Performed some tests locally -- no issues found. Here is how it looks now.
tr-full
tr-compact

Shouldn't we completely delete `web/public_html/transmission-app.js*` files from Git? They are regenerated on build time anyway.

**Comment by FluxState** [comment]
@vchimishuk the merge removed latest changes from https://github.com/transmission/transmission/commit/b11cf4ca00e97153e2d2c8ab44b879bffb719d2b (magnet link).

**Comment by vchimishuk** [comment]
@FluxState , oops. Restored. 
Thanks for the catch.

**Review by ckerr — APPROVED** [review]
This looks great. Thank you for the PR!

**Comment by ckerr** [comment]
> Shouldn't we completely delete web/public_html/transmission-app.js* files from Git? They are regenerated on build time anyway.

Yeah we probably should. If someone wants to make a separate PR for that, that would make sense IMO

**Comment by ckerr** [comment]
oops well, apparently I should test things out more often before merging.

@vchimishuk this fails to build for me because `web/src/labels-dialog.js` doesn't exist in the PR, probably you forgot to `git add` it. No big deal, but even though I've reverted this commit I'm not able to reopen this PR -- so you'll need to file a new PR instead to followup with the dialog js file.

**Pull request merged**
