### PR TITLE
removing unreachable code

### PR DESCRIPTION
**Pull request by Coeur**
This change will also have the benefit to reduce the number of strings to localize once @mikedld sync the translations again.

### CODE REVIEW

**Review by nevack — APPROVED** [review]
LGTM for `stringForFileSizeLion:` part.
No opinion about removing `break`s, maybe it's needed for linters.

**Comment by Coeur** [comment]
Linters don't complain of the removal. On the contrary, compiler does complain of the extra presence; see this screenshot:
Capture d’écran 2022-11-03 à 10 57 35

**Comment by Coeur** [comment]
I'm not sure who or what is "cooling"?
The return+break warning is from #3986.

**Comment by ckerr** [comment]
Notes: none

**Pull request merged**
