### PR TITLE
WebUI: Fix overflow-menu and context-menu positioning for small viewports

### LINKED ISSUE #5299: WebUI: Hamburger menu is not scrollable if window is too small
### What is the issue?

grafik
The scrollbar on the right scrolls just a tiny bit. The top 1/3 of the menu contents is basically missing with no means to access it.
Seen in Firefox on Windows

### Which application of Transmission?

Web client

### Which version of Transmission?

4.0.2

### PR DESCRIPTION
**Pull request by Rukario**
Allows main menu accessible on smaller browser window.

Fixes #5299

Additional fix made for context menu.

### CODE REVIEW

**Comment by GaryElshaw** [comment]
Can we please have a screenshot of the proposed changes?

**Comment by Rukario** [comment]
transmission screenshot
Left: new, right: old

However I'm not sure the buildbot will regenerate the file or should it be done manually, I can upload one if necessary

**Comment by Rukario** [comment]
Closing in favor of #5820

**Comment by Rukario** [comment]
Oh my , this didn't go as planned, I wanted to create a new pull request for different things but I'm pretty noob right now.

**Pull request closed without merging**
