### PR TITLE
Fix building on macOS Mojave

### PR DESCRIPTION
**Pull request by Coeur**
Fix a build regression from #4195.

And I hope to get Transmission 4.0 released soon: I don't want to maintain Mojave forever. :)

### CODE REVIEW

**Comment by Coeur** [comment]
@ckerr it's a rollback of my change, so you can merge it directly.

**Comment by ckerr** [comment]
Notes: Fixed various XCode and CMake build issues.

**Comment by GaryElshaw** [comment]
Notes: Fixed various Xcode and CMake build issues.

**Comment by Coeur** [comment]
Notes: Fixed various Xcode and CMake build issues.

**Pull request merged**
