### PR TITLE
Replace some instances of -UTF8String with -fileSystemRepresentation

### PR DESCRIPTION
**Pull request by MaddTheSane**
`-[NSString fileSystemRepresentation]` is better for passing paths to UNIX file APIs than using `-[NSString UTF8String]`.

Also use `[[NSFileManager defaultManager] stringWithFileSystemRepresentation:length:]` when creating a path for an `NSString`.

### CODE REVIEW

**Comment by livings124** [comment]
Thanks!

**Comment by livings124** [comment]
I had to revert this because it was causing https://github.com/transmission/transmission/issues/1183

@MaddTheSane would you be able to update with nil checks?

**Comment by MaddTheSane** [comment]
Will do. Didn't know that could happen.

**Comment by MaddTheSane** [comment]
New pull request created at #1191.

**Pull request merged**
