### PR TITLE
Adopting .clang-format-include and .clang-format-ignore

### PR DESCRIPTION
**Pull request by Coeur**
This is two things:

1. Extraction of the clang-format included and ignored files for potential reusability by other tools; the adopted format is the one used by Meson (https://mesonbuild.com/Code-formatting.html) which uses .clang-format-include and .clang-format-ignore. Together with this, I'm adding the untracked file `libtransmission/version.h` explicitly to .clang-format-ignore, so that may help anyone who had this file auto generated.

2. A convenience change for users of SourceTree (like me), which executes `code_style.sh` from `extras/pre-commit` but this scenario lacks proper environment PATH. This adds to the PATH `/opt/homebrew/bin` (for Apple Silicon Mac) and `/usr/local/bin` (for Intel Mac) and allows clang-format and yarn to be found.

Together, those two changes should hopefully help other contributors as well like @bitigchi as seen in https://github.com/transmission/transmission/issues/3039#issuecomment-1114644541

### CODE REVIEW

**Comment by GScottElshaw** [comment]
@Coeur Antoine, any idea if these changes will help with similar issues using [GitHub Desktop](https://desktop.github.com/)?

**Comment by Coeur** [comment]
> @Coeur Antoine, any idea if these changes will help with similar issues using [GitHub Desktop](https://desktop.github.com/)?

I just tested it, and GitHub Desktop isn't affected by the PATH issue, so I've updated the comment to explain that it's only for SourceTree.
This change should have no impact on GitHub Desktop.

**Comment by GaryElshaw** [comment]
I get all of these upstream error messages and was hoping it might help.

`checking code format

                                            ^
./macosx/Torrent.mm:1878:57: error: code should be clang-formatted [-Wclang-format-violations]
            [self insertPathForComponents:pathComponents
                                                        ^
./macosx/Torrent.mm:1879:44: error: code should be clang-formatted [-Wclang-format-violations]
                       withComponentIndex:1
                                           ^
./macosx/Torrent.mm:1880:51: error: code should be clang-formatted [-Wclang-format-violations]
                                forParent:tempNode
                                                  ^
./macosx/Torrent.mm:1881:54: error: code should be clang-formatted [-Wclang-format-violations]
                                 fileSize:file.length
                                                     ^
C/C++ code needs formatting
/Users/gary/Documents/GitHub/transmission/code_style.sh: line 85: yarn: command not found
JS code could not be checked -- "yarn install" failed`

**Comment by Coeur** [comment]
@GaryElshaw CocoaCompatibility.h was fixed three days ago with #3027. Try to rebase your code.

**Comment by GaryElshaw** [comment]
Yep, i got yard installed, but that clang-format issue remains. I'll keep trying.

**Pull request merged**
