### PR TITLE
chore: bump small

### PR DESCRIPTION
**Pull request by tearfur**
https://github.com/alandefreitas/small/pull/46

### CODE REVIEW

**Comment by Coeur** [comment]
I'd prefer to only bump to tagged released, unless the dependency is abandoned. Don't you think **small** is going to have a patch release for this?

**Comment by ckerr** [comment]
It's not a dealbreaker IMO, but +1 a tagged version would be better

**Comment by tearfur** [comment]
I remember seeing some classes that didn't need a default constructor end up having one anyway to workaround this `small` bug. So IMO this should be merged asap so we can start cleaning those up.

**Review by Coeur — APPROVED** [review]
We now have a tag for this release: https://github.com/alandefreitas/small/releases/tag/v0.2.2
So, approving.

**Review by reardonia — APPROVED** [review]

**Comment by mikedld** [comment]
Seems to still point to a non-release commit in `develop` (https://github.com/transmission/small/commit/8a814c07a83cfd1dfd9147581b54b0cefb5308c8) and not a `v0.2.2` tag in `master` (https://github.com/transmission/small/commit/46bb00342b052b76a7b95ef639fcc601e80e2988).

**Comment by tearfur** [comment]
Huh, their previous releases are on the `develop` branch, so I just assumed that it's the same for `v0.2.2` too.

Now updated the submodule to the release tag.

**Review by mikedld — APPROVED** [review]

**Pull request merged**
