### PR TITLE
fixup! perf: use small::max_size_vector in tr_torrentGetMetadataPiece

### LINKED ISSUE #5815: Segmentation fault (Build #11516 Jul 18, 2023, 3:23:17 PM)
### What is the issue?

build in docker alpine:latest, with following packages: build-base clang cmake curl-dev dbus-glib-dev gtkmm4-dev libdeflate-dev libevent-dev libpsl-dev llvm miniupnpc-dev openssl-dev qt6-qtsvg-dev qt6-qttools-dev samurai lld

successfully build, but failed to run transmission-daemon
QQ截图20230722212839

tried Build #11516, both report the same error.

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1.0-dev (Build #11516 Jul 18, 2023, 3:23:17 PM)

### PR DESCRIPTION
**Pull request by ckerr**
reduce sizeof(VariantWalker)

Fixes #5815.

### CODE REVIEW

**Comment by tearfur** [comment]
@ckerr You may want to merge #5822 before this one, so that the CI can catch anything else.

**Comment by ckerr** [comment]
> @ckerr You may want to merge #5822 before this one, so that the CI can catch anything else.

The CI changes in that PR make sense but I don't understand why that new `FIXME` comment in is in there. Also -- superficially -- I didn't want to merge the red branch first :smile_cat: even though it's just exposing a pre-existing bug

I've added [a4ed60c](https://github.com/transmission/transmission/pull/5830/commits/a4ed60c9a4498c404297d872f258e1d86abdf1a4) with you as author to pull the CI changes into this branch. If this goes green, we could merge the fix & the new CI protection here.

**Comment by ckerr** [comment]
Notes: Avoid unnecessary heap memory allocations.

**Comment by tearfur** [comment]
@ckerr I think this is stack allocation instead of heap.

**Pull request merged**
